### ISSUE TITLE
Setup MKDocs to to uphrade and publish documentation.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#1005]
### Describe the feature

For now, this project uses its `README.md` and other files combined as primary documentation. As we have covered a few modules, I look forward to adding and publishing documentation like `FastAPI` [Link](https://fastapi.tiangolo.com/).

For the initial setup, I want someone to
- Setup basic layout using Materials for MkDocs
- Build the navbar section with details about GitHub
- You can use the current readme to display on the primary page.
- Plan about how we can add the rest of the documentation.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/7fa40644-1394-4992-893c-43a35d1e6fc5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by nikhil25803** [comment]
**Note** - I have already set up the MkDocs.
You can use the following command to run and test the documentation files.
```bash
## Commands

* `mkdocs new [dir-name]` - Create a new project.
* `mkdocs serve` - Start the live-reloading docs server.
* `mkdocs build` - Build the documentation site.
* `mkdocs -h` - Print help message and exit.

## Project layout

    mkdocs.yml    # The configuration file.
    docs/
        index.md  # The documentation homepage.
        ...       # Other markdown pages, images and other files.

```

**Comment by adishgarg** [comment]
Can i work on this issue under GSSoc'24? @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @adishgarg

**Comment by Daksh-khandelwal-1495** [comment]
Would love to work on this issue when available ! 
 Looking forward to it .

**Comment by nikhil25803** [comment]
Hey @Daksh-khandelwal-1495, you can coordinate with @adishgarg and can work on other feature related to MkDocs.

Make sure to raise different PRs

**Comment by adishgarg** [comment]
@nikhil25803 do we want to replicate the Fast API doc completely or just use it as a reference because they employ a lot of external css and js

**Comment by nikhil25803** [comment]
For reference only @adishgarg
