### ISSUE TITLE
Feat: Improvement in steam Scraper

### ISSUE THREAD

**Issue by SudoSu-bham** [Clueless-Community/scrape-up#1006]
### Describe the feature

The scraper is currently not able to use multiple tags(filters) at once.
When we provide multiple tags(filters) we get separate output for each of them. 
Now we want to include an option to use multiple tags(filters). 

for example
if we pass 5 with two tags in Scraper function  
`Scraper(5, ['Discounts', 'F2P'])`
we get 10 outputs 5 for `Discount` and 5 for `F2P`

You may include a 3rd parameter for using multiple tags(filters) at once.

### Add ScreenShots

![Screenshot from 2024-05-18 11-38-40](https://github.com/Clueless-Community/scrape-up/assets/55135022/6fde7072-9a91-4817-a08d-1155393fd54a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by iABn0rma1** [comment]
Please assign this issue to me, as I've already been exploring a solution that doesn't require a new parameter, by simply passing multiple _filter_tags_. For your reference, please see the attached image:
<img width="450" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/75512370/c4b37ca3-13f9-4c71-a8e6-16af083c7a4c">

This approach avoids creating additional parameters and allows for more flexibility in passing multiple tags to the `Scraper function`

### Record

- [ ]  I agree to follow this project's Code of Conduct
- [ ]  I'm a GSSoC'24 contributor
- [ ]  I want to work on this issue

**Comment by sreesti07** [comment]
Hello @iABn0rma1, I would like to work on this issue as a contributor at GSSOC'24. Please assign this to me.
