### ISSUE TITLE
Feat:Add module for idealist.org and scrape internship page

### ISSUE THREAD

**Issue by agastya3636** [Clueless-Community/scrape-up#1008]
### Describe the feature

Add module for idealist.org and scrape internship page

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/124435030/b2475df4-09ae-4336-9398-3d29453d30ef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @agastya3636
