### ISSUE TITLE
Feat: I would like to scrape the job page of idealist.org

### ISSUE THREAD

**Issue by agastya3636** [Clueless-Community/scrape-up#1009]
### Describe the feature

 I would like to scrape the job page of idealist.org

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/124435030/63412d44-8e9e-475e-b66a-a64e3add4f48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @agastya3636
