### ISSUE TITLE
Get Followers List

### ISSUE THREAD

**Issue by PalaVenkiReddy** [Clueless-Community/scrape-up#101]
### Description
returns list of followers for given github username

### Example Usage
```python
# Import the required module
from scrape_up import github

# Instantiate an object with username provided.
user =  github.Users(username="nikhil25803")

# Cal the followers function
print(user.get_followers_list())

# Output: Returns List of Followers
```

Please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Sounds good, go ahead.
While making a PR, do not forget to upload a screenshot of output on a username. @PalaVenkiReddy
