### ISSUE TITLE
Feat: Extraction of LinkedIn Jobs 

### ISSUE THREAD

**Issue by kumargautam02** [Clueless-Community/scrape-up#1022]
### Describe the feature

Describe the feature
[Linkedin ](https://www.linkedin.com/jobs)can be scraped to obtain publicly available info about a job like....

Job Role:
Location:
Experience:
Mandatory Skills :
Apply link:
Pay Range:

Under GSsoC'24, i would like to contribute to this repo under this issue @nikhil25803

Add ScreenShots

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/141772614/181f25ee-7e6f-4f19-bb49-1f22092ed8a4)

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSoC'24 contributor
- [x] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @kumargautam02 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
