### ISSUE TITLE
Feat:Scraper for Glassdoor 

### ISSUE THREAD

**Issue by manishh12** [Clueless-Community/scrape-up#1024]
### Describe the feature

Glassdoor: Scrape data and job description from Glassdoor website to help job seekers analyze companies and prepare for interviews.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/97523900/29403043-83ff-468e-ae2f-1263f98df600)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by manishh12** [comment]
@nikhil25803 I want to contribute this Under GSSOC'24 kindly assign me.

**Comment by nikhil25803** [comment]
Go ahead @manishh12 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
