### ISSUE TITLE
Feat: Add new module for Letterboxd

### ISSUE THREAD

**Issue by arpy8** [Clueless-Community/scrape-up#1028]
### Describe the feature

I would like to scrape the user profile page on letterboxd, which is a popular social network for grass-roots film discussion and discovery.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/74809468/69da96af-8d24-4011-aaaa-f05edcb09bd4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @arpy8 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
