### ISSUE TITLE
Feat: Automate greeting when PR is made using Github bot 🤖

### ISSUE THREAD

**Issue by shubhammjha22** [Clueless-Community/scrape-up#1038]
### Describe the feature

As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

I would like to add a github bot , which would greet the user whenever there is a PR request

For PR
" Great job, @ username 🎉 , Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project. Our team will review your changes shortly."

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/68507333/98dd15d5-d3b0-4597-acb1-46ce9a2d4b49)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @shubhammjha22

**Comment by shubhammjha22** [comment]
@nikhil25803 I have made the PR. Kindly review it and  i would request you to add the apt level and labels

**Comment by shubhammjha22** [comment]
@nikhil25803  i have add the demo video , kindly review it
