### ISSUE TITLE
Feat: Scrape Ticket Prices, Movie Reviews, and Ratings from BookMyShow

### ISSUE THREAD

**Issue by revanth1718** [Clueless-Community/scrape-up#1048]
### Describe the feature

 A web scraping script to extract data from BookMyShow, specifically focusing on ticket prices, movie reviews, and ratings. This data will be used for analyzing movie trends and pricing strategies. The script should handle dynamic content loading, ensure compliance with the website's terms of service, and store the extracted data in a structured format.

### Add ScreenShots

![Screenshot (548)](https://github.com/Clueless-Community/scrape-up/assets/109272714/9f3537b9-2b92-44d5-b351-370391cc209a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Great work @revanth1718  !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Comment by anushkasaxena07** [comment]
@nikhil25803  please assign this issue to me

**Comment by AnjuMau8418** [comment]
@nikhil25803 please assign this issue  to me.

**Comment by SanskariWolf** [comment]
@nikhil25803 Can you please assign this issue to me

**Comment by Kimforee** [comment]
@nikhil25803 please assign this issue to me !
