### ISSUE TITLE
Get avatar of a GitHub organization.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#105]
## Proposed Method:
`.avatar()`

### Description
Create a method to scrape the URL of a GitHub organization

## To what class it belongs?: 
`Organization`

### Note
+ Make all the changes in the `github/organization.py` file.
+ Use a private method ` __scrape_page` to scrape the page.
+ Include the method in the `documentation.md` file.
+ Upload a screenshot with the PR, demonstrating the method.

**Comment by PalaVenkiReddy** [comment]
Please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Go ahead @PalaVenkiReddy.
