### ISSUE TITLE
Feat: Add new module for Last.fm

### ISSUE THREAD

**Issue by arpy8** [Clueless-Community/scrape-up#1054]
### Describe the feature

I would like to scrape the user profile page on last.fm, which is a popular social network for grass-roots film discussion and discovery.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/74809468/0b273cf8-3c71-4d50-9306-b77992f3dcdd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @arpy8 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
