### ISSUE TITLE
Feat: Test files for Zomato

### ISSUE THREAD

**Issue by aRUsh-codes** [Clueless-Community/scrape-up#1056]
### I want to add test files for Zomato 

I intend to do the following
- Test all the methods of the Zomato module.
- Add test file in directory src/test.
- Check the zomato.py file as a reference to follow the structure of the code given.

PS- please assign "gssoc" and appropriate "level_" labels to this as well.

Thank You.

### Add ScreenShots

![Screenshot (129)](https://github.com/Clueless-Community/scrape-up/assets/98696069/7568f480-c6cc-48dc-9949-bc28e1888404)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @aRUsh-codes 
- Add test file in directory `src/test`.
- Use `unittest` only.

**Comment by aRUsh-codes** [comment]
@nikhil25803 Thank you for assigning me. Can you also add the appropriate level label to this. 
Thank You

**Comment by itssiddhantjain** [comment]
Hello @nikhil25803 , please assign this issue to me as I have already worked on this kind of problem in the past.
