### ISSUE TITLE
Number of followers of an organization.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#106]
### Proposed Method
`.followers()`

### Description
Create a method to scrape the number of followers an organization has.

## To what class it belongs?
`Organization`

### Note
+ Make all the changes in the `github/organization.py` file.
+ Use a private method ` __scrape_page` to scrape the page.
+ Include the method in the `documentation.md` file.
+ Upload a screenshot with the PR, demonstrating the method.

**Comment by PalaVenkiReddy** [comment]
Please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Go ahead.
