### ISSUE TITLE
DOC: Fix error in output of method

### ISSUE THREAD

**Issue by ShreeluSantosh** [Clueless-Community/scrape-up#1064]
### What's wrong with the existing documentation

In the documentation.md, the following code snippet gives an error (given in screenshots)

```
# Import the required module
from scrape_up import github

# Instantiate an object with the username provided.
user = github.Users(username="nikhil25803")

# Call the followers function - it will return the number of followers
per user.followers()
```

The reason is that **per** keyword doesn't exist in Python.

So, I've corrected it to use print function instead.

```
# Import the required module
from scrape_up import github

# Instantiate an object with the username provided.
user = github.Users(username="nikhil25803")

# Call the followers function - it will return the number of followers
print(user.followers())
```

### Add ScreenShots

The output for the code snippet in the documentation.md
![Screenshot 2024-05-26 222706](https://github.com/Clueless-Community/scrape-up/assets/94289402/e347517b-8e1b-4c1c-b6bc-1214e6da6f3e)

Output after replacing per with print function
![Screenshot 2024-05-26 222725](https://github.com/Clueless-Community/scrape-up/assets/94289402/c0709e29-8c04-4df8-bcf8-7a670c24e87c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @ShreeluSantosh

**Comment by ShreeluSantosh** [comment]
Pull request: #1071
