### ISSUE TITLE
Feat: Adding scraping module for Zillow Website

### ISSUE THREAD

**Issue by piyush-poddar** [Clueless-Community/scrape-up#1066]
### Describe the feature

As a part of GSSOC'24, I would like to add a module for [zillow.com](https://www.zillow.com) which would serve the following functionalities:
- Fetch details of **Homes For Sale** based on search location:
    - Price
    - Area
    - Numbers of rooms, beds, etc.
    - Location
    - Listed by
- Fetch details of **Rental Listings** based on search location:
    - Price
    - Name
    - Location

Expected Level: **Level 2**

@nikhil25803 Please assign me this issue and add **`gssoc`** and **`level2`** labels. Thanks!!

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/143445461/aa7f616e-65a1-405a-ad4d-830ae3bd138b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @piyush-poddar 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
