### ISSUE TITLE
DOC: Want to scrap football information from official websites of each league from webistes like fbref

### ISSUE THREAD

**Issue by Prathamg001** [Clueless-Community/scrape-up#1067]
### What's wrong with the existing documentation

No existing document present for this idea

### Add ScreenShots

[https://fbref.com/en/comps/9/Premier-League-Stats](url)

Scrapt the table of premier league with each team stats and do for every league

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Prathamg001** [comment]
I want to work on this issue...please give me access to work

**Comment by Prathamg001** [comment]
<img width="944" alt="Screenshot 2024-05-27 161219" src="https://github.com/Clueless-Community/scrape-up/assets/85290399/51c1cdd7-4b75-444e-b530-075cd32b87dd">


Want to extract this table from the following webiste and do the same for other leagues too

**Comment by nikhil25803** [comment]
Go ahead @Prathamg001 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by Prathamg001** [comment]
I have given in a pull in request

**Comment by Prathamg001** [comment]
I have turned in a pull request in patch 1
