### ISSUE TITLE
Feat: Add support for SteamDB

### ISSUE THREAD

**Issue by KunalG-Zol** [Clueless-Community/scrape-up#1068]
### Describe the feature

SteamDB contains a variety of info regarding games, like their current/lowest prices in all countries, general info about the game and much more, which can be scraped using a module.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/94951050/31d3bf8d-bc97-4b96-9fb3-cb991e734e03)
![image](https://github.com/Clueless-Community/scrape-up/assets/94951050/375fba99-9ed7-4dd7-8c2e-c5c4da615d27)
![image](https://github.com/Clueless-Community/scrape-up/assets/94951050/a55f58a6-3073-4cfb-93ef-bb1533403c4b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by PragyaChauhan1401** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSoC'24 contributor
 I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @KunalG-Zol 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
