### ISSUE TITLE
Peoples in an organization.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#107]
### Proposed Method
`.peoples()`

### Description
Create a method to scrape the number of peoples who are the part of the orgnaization.

![image](https://user-images.githubusercontent.com/93156825/220551784-d45a8067-a8cd-47ee-b5ad-e7ea345ab11e.png)

## To what class it belongs?
`Organization`

### Note
+ Make all the changes in the `github/organization.py` file.
+ Use a private method ` __scrape_page` to scrape the page.
+ Include the method in the `documentation.md` file.
+ Upload a screenshot with the PR, demonstrating the method.

**Comment by neokd** [comment]
I would like to work on this issue.

**Comment by nikhil25803** [comment]
Go ahead @neokd

**Comment by codesleep-Beperfect** [comment]
I would like to work on this issue.Under JWOC

**Comment by nikhil25803** [comment]
Go ahead @neokd.

**Comment by nikhil25803** [comment]
Hey @codesleep-Beperfect, this issue has already been assigned.
