### ISSUE TITLE
Feat: want to add dark/light theme

### ISSUE THREAD

**Issue by Aditijainnn** [Clueless-Community/scrape-up#1073]
### Describe the feature

please assign me this task of adding dark/light theme button 

### Add ScreenShots

![Screenshot 2024-05-28 at 22-05-08 scrape-up](https://github.com/Clueless-Community/scrape-up/assets/144632601/d8d7ec98-045d-469e-928f-960263587a66)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by PadmaSri08** [comment]
Please  assign this task to me. I can do it.
