### ISSUE TITLE
Top languages used in an organization.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#108]
### Proposed Method
`.top_languages()`

### Description
Create a method that returns the list of top languages used in an organization.

## To what class it belongs?
`Organization`

### Note
+ Make all the changes in the `github/organization.py` file.
+ Use a private method ` __scrape_page` to scrape the page.
+ Include the method in the `documentation.md` file.
+ Upload a screenshot with the PR, demonstrating the method.

**Comment by madmaverickminion** [comment]
Hi, Please assign this issue to me .

**Comment by nikhil25803** [comment]
Go ahead @madmaverickminion :))
