### ISSUE TITLE
Feat: Add Scraping for Twitch.tv Website

### ISSUE THREAD

**Issue by andrewperezledo** [Clueless-Community/scrape-up#1081]
### Describe the feature

I would like to add the scraping of user information from the [Twitch](https://www.twitch.tv/) live streaming website such as followers, maybe live viewers, or live status.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/104042824/6a2d8dfe-4550-487c-b115-67561e012824)
![image](https://github.com/Clueless-Community/scrape-up/assets/104042824/00d6dd4f-9efe-492a-8900-54b8b8d1326b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @andrewperezledo 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by Rajrishi07** [comment]
I want to work on this issue. i am a GSSoC'24 contributor.
