### ISSUE TITLE
Feat: Add a scraper for the gssoc webstie

### ISSUE THREAD

**Issue by arpy8** [Clueless-Community/scrape-up#1084]
### Describe the feature

I would like to create a scraper for the gssoc website. I am planning to add the following functions:
- ongoing projects
- leaderboard data

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/74809468/34edde71-4578-434a-ab88-7186a6d2b0a3)

![image](https://github.com/Clueless-Community/scrape-up/assets/74809468/c8f7ac3b-0232-4243-bfef-00145faf817f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Deepanshi-Gupta** [comment]
@arpy8  Will you please assign me this, I really want to make it one of my first PRs under GSSOC - 24
I am a GSSOC 24 Contributor 
I want to work on this issuse

**Comment by arpy8** [comment]
@nikhil25803,  could you please let me know why this has been marked as completed? thanks
