### ISSUE TITLE
Feat: Add test files for WHO module

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [Clueless-Community/scrape-up#1089]
### Describe the feature

- Test all the methods of the who module and add a test file.
- Will add test file in directory src/test.
- Will Check the WHO.py file as a reference to get an idea about structuring the code.
- Will use unittest only.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/103999924/61e054f7-e0b0-4993-bb99-87ed6145c815)

Similar to above files

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Santhosh-Siddhardha 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
