### ISSUE TITLE
Most used topic of an organization.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#109]
### Proposed Method
`.top_topics()`

### Description
Create a method that returns the list of most used topics used in an organization.

## To what class it belongs?
`Organization`

### Note
+ Make all the changes in the `github/organization.py` file.
+ Use a private method ` __scrape_page` to scrape the page.
+ Include the method in the `documentation.md` file.
+ Upload a screenshot with the PR, demonstrating the method.

**Comment by vhadzhiev** [comment]
Can I get the assignment?

**Comment by nikhil25803** [comment]
Sure, go ahead @vhadzhiev :))
