### ISSUE TITLE
Feat: Adding new module for Walmark

### ISSUE THREAD

**Issue by VesperAkshay** [Clueless-Community/scrape-up#1095]
### A web scraping module that can be used to retrieve information from the Walmart website. Specifically, this module is designed to gather two types of data:

1. **List of Products**: The module will fetch a list of products available on the Walmart website.
2. **Special Products with Discounts**: The module will also identify and retrieve information about products that are currently on sale or have a discount applied to them.

### Add ScreenShots

![Screenshot (92)](https://github.com/Clueless-Community/scrape-up/assets/118452811/519dc382-cb8a-4034-8b35-0d85ba240fbe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @VesperAkshay 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
