### ISSUE TITLE
DOC: Enhance README file

### ISSUE THREAD

**Issue by Ojas-Arora** [Clueless-Community/scrape-up#1097]
### What's wrong with the existing documentation

I want to add some more features to the README file. Kindly assign this issue to me @nikhil25803 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Samik123Mit** [comment]
pls assign me the issue. i will make sure the task is done. to make it more detailed and better understood
