### ISSUE TITLE
Feat: Add scraper for Omdena Dashboard

### ISSUE THREAD

**Issue by arpy8** [Clueless-Community/scrape-up#1099]
### Describe the feature

I would like to scrape the user profile page on omdena website.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/74809468/1aa16c1f-fd8c-4fd1-b483-08b77ff3d837)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @arpy8 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by mahika-jain** [comment]
I'm eager to contribute! Could you please assign me an issue to work on?

Thank you!
