### ISSUE TITLE
Pinned repositories of an organization.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#110]
### Proposed Method
`.pinned_repository()`

### Description
Create a method that returns the details of pinned repository of an organization.

![image](https://user-images.githubusercontent.com/93156825/220553211-187d079b-0e9d-4edb-bfe3-55a3730b0637.png)

-----

### Output Sample 
```python
[
    {
        "name":"",
        "link":"https://github.com/Clueless-Community/clueless-official-website",
        "detail":"This is Clueless official website where you can make your developer profile as well as meet new people across the world.",
        "top_lang":"TypeScript",
        "stars":"60",
        "forks":"129"

    },
    ....
]
```

## To what class it belongs?
`Organization`

### Note
+ Make all the changes in the `github/organization.py` file.
+ Use a private method ` __scrape_page` to scrape the page.
+ Include the method in the `documentation.md` file.
+ Upload a screenshot with the PR, demonstrating the method.

**Comment by ayushanand308** [comment]
Please assign me this issue under JWOC

**Comment by nikhil25803** [comment]
Sure @ayushanand308, go ahead.

**Comment by ayushanand308** [comment]
On it?

**Comment by madmaverickminion** [comment]
Hi @nikhil25803 is this issue still open. Please assign it to me. 
Thank you !!

**Comment by ayushanand308** [comment]
@nikhil25803  I am almost done working on it and I will be soon making a PR.

**Comment by ayushanand308** [comment]
@nikhil25803  I have made a PR. Can you review and tell me if you want any changes?
