### ISSUE TITLE
Feat : scraping customer review analysis 

### ISSUE THREAD

**Issue by A-Ashh** [Clueless-Community/scrape-up#1106]
By using Beautiful Soup (Python’s open-source library) as it will allow you to crawl the website and extract the review from the Amazon website using HTML tags.
This will provide a quick and easier way for a customer to review products .

**Comment by A-Ashh** [comment]
I want to work on this. can u assign it to me

**Comment by adityasingh-0803** [comment]
i wan to work on this can u assign it to me under gssoc24
