### ISSUE TITLE
Feat: Want to scrape events from the BookMyShow

### ISSUE THREAD

**Issue by abckhush** [Clueless-Community/scrape-up#1110]
### Describe the feature

I want to scrape events from a city based on date from BookMyShow

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/127378920/bc7b0bd7-908a-427f-97fb-6900d8bbd28a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by abckhush** [comment]
Could you add the level?

**Comment by apoorva813** [comment]
I am a contributor for Gssoc'24. I wish to work on this issue. Could you please assign me this issue?
