### ISSUE TITLE
improve the footer 

### ISSUE THREAD

**Issue by jayanththalla** [Clueless-Community/scrape-up#1114]
### Describe the feature

In the footer, the alignment of the text and the underline is to be removed 
Hove the text with color

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/121346142/2ae1e701-1b0f-477c-a0a2-28d8190538b6)
please assign me @pa
please label it under the gssoc and add level

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by TWmin13** [comment]
Please assign me this issue under GSSoC'24. Thank you!
