### ISSUE TITLE
Feat: want to add Address-Book 

### ISSUE THREAD

**Issue by pallasivasai** [Clueless-Community/scrape-up#1115]
### Describe the feature

Address book using python in which the user can add a new contact, edit and delete existing contact and view all the contact using Tkinter and SQlite. Tkinter library for rendering graphics and SQlite is used for database.

### Add ScreenShots

I will add it in PR

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by pallasivasai** [comment]
@SudoSu-bham can u please assign me this issue please

**Comment by SudoSu-bham** [comment]
> @SudoSu-bham can u please assign me this issue please

Done. Start working on your idea.

**Comment by pallasivasai** [comment]
@SudoSu-bham  please checkout my [PR](https://github.com/Clueless-Community/scrape-up/pull/1140) at once
