### ISSUE TITLE
BUG: Codeforces scrapper has a problem

### ISSUE THREAD

**Issue by Shraman-jain** [Clueless-Community/scrape-up#1121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Codeforces.py has a problem in its class name and object. I can resolve this please assign this to me and add gssoc label

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by mahika-jain** [comment]
I'm eager to contribute! Could you please assign me an issue to work on?

Thank you!

**Comment by Shraman-jain** [comment]
I have already found the issue and raised it and also wants to solve this but the admin hasn't assigned me yet
