### ISSUE TITLE
Add test files for LinkedIn module

### ISSUE THREAD

**Issue by KrishnaPriyaKanduri** [Clueless-Community/scrape-up#1123]
This feature request involves adding test files for the LinkedIn module. The purpose of these test files is to ensure the functionality of the LinkedIn module is thoroughly validated and performs as expected. The tests should cover various scenarios, including data extraction, error handling, and integration with other components.

**Comment by krishk2** [comment]
Hi @KrishnaPriyaKanduri , I would to like to work on this this issue, could you please assign it to me?
