### ISSUE TITLE
Feat: Add test file for Udemy Course

### ISSUE THREAD

**Issue by Divyanshi1002** [Clueless-Community/scrape-up#1130]
### Involves :

- adding test files for the Udemy module. 
- to ensure the functionality of the Udemy module is validated and performs as expected. 
- The tests will cover scenarios:
      - data extraction
      -  error handling
      -  integration with other components.

### Add ScreenShots

![Screenshot 2024-06-18 132637](https://github.com/Clueless-Community/scrape-up/assets/157373233/69163ce2-d967-4153-b354-853ed83e9a47)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by anjaliyadavks** [comment]
hi @Divyanshi1002 
I would love the opportunity to contribute and work on this project.
Could you please assign the issue to me? I'm eager to drive in and make a meaningful impact. Thank you for considering my request!
