### ISSUE TITLE
Feat:  Redesign the logo

### ISSUE THREAD

**Issue by sanskritisahu21** [Clueless-Community/scrape-up#1133]
### Describe the feature

The new design should be more align with the project.

### Add ScreenShots

Current logo can be improve.
![Screenshot 2024-06-22 114100](https://github.com/Clueless-Community/scrape-up/assets/134837879/535f308f-1a8f-4f23-b709-faaaf40e4c3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sanskritisahu21** [comment]
@nikhil25803 please assign me this issue under gssoc

**Comment by adityasingh-0803** [comment]
@nikhil25803 please assign
