### ISSUE TITLE
Contributions in last one year.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#12]
+ Write a method to fetch the numbers of contributions done by a user in the last year (a 365 days time frame)
+ Example
![image](https://user-images.githubusercontent.com/93156825/218851370-f1c85e8f-8b6f-4957-97fc-427c3f9102fc.png)

**Comment by ayushanand308** [comment]
Can you assign me this?

**Comment by TRohit20** [comment]
Hey guys, I'd like to work on this issue under JWOC. Can you kindly assign me the same? Thankyou

**Comment by nikhil25803** [comment]
Hey @TRohit20, as per the first come first assigned term, assigning this issue to @ayushanand308.

**Comment by TRohit20** [comment]
That's alright, You can assign it to me if the issue gets stale or after the limit
