### ISSUE TITLE
get_repositories of Organization

### ISSUE THREAD

**Issue by PalaVenkiReddy** [Clueless-Community/scrape-up#121]
### Description
returns all the repositories of given Organization

## To what class it belongs?: Organization

Please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Sounds good, go ahead.

**Comment by PalaVenkiReddy** [comment]
Bhaiya, as pinned repositories of Organization is hard, Ig it should be hard

**Comment by nikhil25803** [comment]
In the pinned repository, there are other details as well along with just the repository name
