### ISSUE TITLE
get status of an user

### ISSUE THREAD

**Issue by madmaverickminion** [Clueless-Community/scrape-up#125]
### Description
returns the status of an user

## To what class it belongs?:User
 
Please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Can you please explain this issue a bit more?

**Comment by madmaverickminion** [comment]
![image](https://user-images.githubusercontent.com/88222914/220745612-936bfd61-014d-4610-825e-3cb37057e3c0.png)
When we open the profile of any user we get the status of the user near the avatar. I was talking about scraping this status.

**Comment by nikhil25803** [comment]
Great idea, go ahead @madmaverickminion.
