### ISSUE TITLE
get recent organization name

### ISSUE THREAD

**Issue by codesleep-Beperfect** [Clueless-Community/scrape-up#129]
## Proposed Method: get_organization_name()

[Provide a brief description of the method and its purpose.]
return the organization in which a user is working.

### Example Usage
![Screenshot (40)](https://user-images.githubusercontent.com/118013086/220756978-e9c8a57c-bc58-42c3-88d5-44a090dc1c22.png)
In this case the output is joplin.

kindly assign me this issue under JWOC

**Comment by nikhil25803** [comment]
@codesleep-Beperfect, we already do have a method for `Users` class.
