### ISSUE TITLE
Number of stars and repositories of an user.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#13]
+ Create a method with the `Users` class to fetch the number of repositories and star count of a user.

+ For example, 45 repo count and 68 stars count as shown below for the user `nikhil25803`

![image](https://user-images.githubusercontent.com/93156825/218852312-e7764363-53b0-4d33-bb8c-ec6c333b83f9.png)

**Comment by JatinGera27aug** [comment]
i would like to be assigned on this issue. I have already noted the required tags for accessing them

**Comment by nikhil25803** [comment]
Great!! go ahead.
