### ISSUE TITLE
Get All details of each repository

### ISSUE THREAD

**Issue by PalaVenkiReddy** [Clueless-Community/scrape-up#131]
### Description
returns the details of all repositories of an organization.

### Example Usage
![image](https://user-images.githubusercontent.com/75984996/220852334-818a27ba-74f1-41e5-aa22-597f9e78238a.png)

### Output Sample 

```python

[
    {
        "name":"scrape-up",
        "link":"https://github.com/Clueless-Community/scrape-up",
        "detail":"A web-scraping-based python package that enables you to scrape data from various platforms like GitHub, Twitter, Instagram, or any useful website.",
        "top_lang":"Python",
        "stars":"11",
        "forks":"24"
    },
    ....
]
```

Please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Get it done for all the repositories of an organization.
