### ISSUE TITLE
Longest contribution streak of an user in the last year.

### ISSUE THREAD

**Issue by madmaverickminion** [Clueless-Community/scrape-up#137]
### Description
returns an integer, the longest contribution streak of an user

## To what class it belongs?: User

Hi, Kindly assign this issue to me under JWOC.

**Comment by nikhil25803** [comment]
How would you implement this feature @madmaverickminion? Can you please explain a bit about it?

**Comment by madmaverickminion** [comment]
We can scrape the last one year contributions of an user which we will get in this format. 
![image](https://user-images.githubusercontent.com/88222914/221640753-c89b200b-7768-46c6-a595-7b6bfc8540f5.png)
After which we can use a data structure like list to store whether a user has contributed on a particular day or not. Let's say if an user has contributed on a particular day then in our list we have 1 corresponding to that date else zero. So basically the problem gets reduced to finding the maximum number of consecutive ones in the list.

**Comment by nikhil25803** [comment]
What is the execution time?
Doesn't it take too long to execute?

**Comment by madmaverickminion** [comment]
I think it will take linear time complexity.

**Comment by nikhil25803** [comment]
Do you have the code ready?

**Comment by madmaverickminion** [comment]
Yess

**Comment by nikhil25803** [comment]
Okay, make a PR. We will take a look into it if any changes are needed.

**Comment by madmaverickminion** [comment]
Done!! @nikhil25803 kindly review it.

**Comment by madmaverickminion** [comment]
And please assign it to me under JWOC. Thank you :)

**Comment by nikhil25803** [comment]
Sure ser 👀
