### ISSUE TITLE
Get the content of the user's special repository

### ISSUE THREAD

**Issue by pooranjoyb** [Clueless-Community/scrape-up#141]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem, but it will be good if we scrape the `readme.md` of the special repository of the user considering the fact that the repo actually exists. 
If not, we return that special repo doesn't exist.

I am referring to the repo `github.com/username/username`

**Describe the solution you'd like**
I will be good to scrape the `readme.md` of special repository and serve it in the console.

### I would like to work on this issue under JWOC 2023. Please assign me. @nikhil25803

**Comment by nikhil25803** [comment]
Great idea, make it such that calling this function downloads it in the local root directory.

**Comment by pooranjoyb** [comment]
Ok bhaiyaa @nikhil25803 ❤️
