### ISSUE TITLE
method to scrape all the important website links related to an organization

### ISSUE THREAD

**Issue by madmaverickminion** [Clueless-Community/scrape-up#143]
### Description
returns a dictionary of links of popular social media handles,website and gmail of the organization.

### Example Usage
```
t=github.Organzation(organization_name="Clueless-Community")
print(t.get_organization_links())
```
Output-: 

> {
> 'twitter' : 'https://twitter.com/by_clueless',
> 'gmail': 'official.cluelesscommunity@gmail.com'
> 'website':'http://clueless.tech/'
>'instagram':' ',
>'facebook':' ',
>
> }

**Comment by nikhil25803** [comment]
Sounds great @madmaverickminion, go ahead.

**Comment by madmaverickminion** [comment]
Can I import regex module for pattern matching? 
@nikhil25803
