### ISSUE TITLE
get location of an Orgainzation

### ISSUE THREAD

**Issue by codesleep-Beperfect** [Clueless-Community/scrape-up#144]
### Description
Return the location of an Organization.

## To what class it belongs?:  Organization

kindly, assign me this issue.

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC

**Comment by nikhil25803** [comment]
Hey @Priyamakeshwari, it is first come first assigned terms at JWOC. So assigning this issue to @codesleep-Beperfect
