### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by pyGuru123** [Clueless-Community/scrape-up#145]
### Description
Instead of making request everytime to get certain user info, scrape it once and present all  the important data. A simple implementation is shown here : https://github.com/pyGuru123/GitScraper/blob/main/app/scraper.py

### Example Usage

```bash
user = User('pyguru123')
print(user.username)
print(user.fullname)
print(user.followers)
print(user.following)
print(user.bio)
print(user.location)
print(user.repositories)
print(user.readme)
print(user.contributions)
```

**Comment by nikhil25803** [comment]
Yes, I guess this will make it a bit faster as well.  Go ahead @pyGuru123, make the changes for `Users` class.
