### ISSUE TITLE
Scrape the list of branches in a Repository

### ISSUE THREAD

**Issue by pooranjoyb** [Clueless-Community/scrape-up#148]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem, but while working on the repos, a user might need to scrape the branches present in the Repository. 

I am referring to existing branches like `main`, `master`, `dev`, `feature`, `etc..`

**Describe the solution you'd like**
I will be scraping the branches from using a function `.get_branch()`

### I would like to work on this issue under JWOC 2023. Please assign me. @nikhil25803

**Comment by pooranjoyb** [comment]
I was also planning on returning all the commits of all branches in an `Array of Dictionary`
Let me know if you'd like to add this additional feature, else I'd go with the mentioned issue as of now. @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @pooranjoyb

**Comment by pooranjoyb** [comment]
Do you also want me to add the additional feature of getting list of commits in the repo? @nikhil25803

**Comment by nikhil25803** [comment]
Go as with the issue @pooranjoyb
