### ISSUE TITLE
github id of the user who has commited most number of times in last one month

### ISSUE THREAD

**Issue by madmaverickminion** [Clueless-Community/scrape-up#151]
### Description
returns a list, the github id and the number of commits 

## To what class it belongs?:Organization()

Kindly assign this issue to me under JWOC

**Comment by Priyamakeshwari** [comment]
Assign me this issue . I would like to contribute to this issue under jwoc

**Comment by nikhil25803** [comment]
I don't think it is much required @madmaverickminion.
