### ISSUE TITLE
To get the environments of a repository

### ISSUE THREAD

**Issue by neokd** [Clueless-Community/scrape-up#152]
### Description
To get the links of a hosted / production / environments of a repository on github if any.

### Example Usage

<img width="458" alt="Screenshot 2023-03-04 at 11 23 07 AM" src="https://user-images.githubusercontent.com/71772185/222878648-64a31ca4-a6a4-472d-8251-8cccb4941626.png">

**Comment by neokd** [comment]
I would like to work on this under JWOC

**Comment by nikhil25803** [comment]
Looks good @neokd, go ahead.

**Comment by neokd** [comment]
Thanks
