### ISSUE TITLE
Improve return type of the methods

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#153]
### Description
The aim is to generalize the return type in the methods of the `User` class

### Example 
In `followers()` method of the `User` class
```python
        try:
            followers = page.find(class_="text-bold color-fg-default")
            return {
                "data": followers.text,
                "message":f"Followers found for user {self.username}"
            }
        except:
            message = f"{self.username} not found !"
            return {
                "data":None,
                "message":message
            }

```

### Note
Change the return type of all the methods of all the classes according to the format mentioned above.

**Comment by codesleep-Beperfect** [comment]
I would like to work on this issue under JWOC.

**Comment by nikhil25803** [comment]
One issue at a time @codesleep-Beperfect

**Comment by PalaVenkiReddy** [comment]
Bhaiya please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Go ahead @PalaVenkiReddy

**Comment by PalaVenkiReddy** [comment]
![image](https://user-images.githubusercontent.com/75984996/222886638-6e110978-6292-4156-8d6d-4cf65e74c509.png)

Here Can I follow just as mentioned or change the message according to fun return type?

**Comment by nikhil25803** [comment]
Change the message accordingly.

**Comment by PalaVenkiReddy** [comment]
Ok bhaiya
