### ISSUE TITLE
Instagram module

### ISSUE THREAD

**Issue by SajeelHashmi** [Clueless-Community/scrape-up#160]
## Proposed Method: [Method Name]
Implementation of the Instagram module

### Description
The Instagram module is not implemented at all
this module could be used to scrape the pfp of the user account details like private/public account number of followers following
number of posts also a list of followers and following

### Example Usage
![image](https://user-images.githubusercontent.com/108219594/232776019-7c9e15ec-b33c-4bae-abd3-08c77dd1c670.png)

**Comment by alivia-ansari** [comment]
Could you assign this issue to me for GSSoC'23? I would like to work on this.

**Comment by shrish-shete20** [comment]
Hi @SajeelHashmi , Would you assign me this issue under GSSOC?

**Comment by A15h** [comment]
hi @nikhil25803 
I would really like to work on this issue. Please assign this issue to me. I am a contributor of GSSOC'23.

**Comment by adhikari-pratik** [comment]
hello @SajeelHashmi  
As a contributor of GSSOC'23 I would like to work on this. Can you assign this to me?

**Comment by urvi-swl** [comment]
Hi @SajeelHashmi 
I am a GSSoC'23 contributor andhave been exploring this particular domain of scraping already.Could you assign this issue to me?

**Comment by Swapnil-Singh-99** [comment]
I want to work on this issue.
@SajeelHashmi Please assign me this issue, I have been working on many projects to scrape websites for data using python.
Thanks.

**Comment by nikhil25803** [comment]
Great idea @urvi-swl, I have just added an Instagram module. With the fetch followers function of a user. I'll be raising more issues on this corresponding to each function. 

Propose the Method name as well while raising an issue, like `followers()`, or `following()`.

**Comment by nikhil25803** [comment]
@urvi-swl | @Swapnil-Singh-99 | @alivia-ansari | @adhikari-pratik | @shrish-shete20 | @A15h 

Closing this issue for now, please raise issues corresponding to each method, not whole at once.
