### ISSUE TITLE
Improving the readme file of this project 

### ISSUE THREAD

**Issue by harshsingh32** [Clueless-Community/scrape-up#161]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Ayush-Tibrewal** [comment]
Hey there @Akshat103 @Roshaen @Rubyseher ! I'm Ayush Tibrewal, a GSSOC'21 participant. . I'll provide concise, well-explained code and emphasize the crucial aspects as I am UI UX DESINER . Assigning me this issue would be a fantastic opportunity. Looking forward to hearing from you soon!

**Comment by nikhil25803** [comment]
@harshsingh32 | Please specify how will you improve the readme so that it will be easier for us to understand your motive as well.

**Comment by alivia-ansari** [comment]
I am a Web Designer. I would like to incorporate appropriate formatting, such as bullet points, code blocks, and tables, to improve readability and highlight key information. I will also focus on making the readme file visually appealing to capture the attention of readers. This includes using relevant and eye-catching images, logos, or illustrations that represent the project.
Could you assign this issue to me @nikhil25803 for GSSoC'23?

**Comment by nikhil25803** [comment]
Go  ahead @alivia-ansari

**Comment by harshsingh32** [comment]
Sir I would like to work on this issue,  I am web developer and designer and have relevant skillset to improve the readme file of this project, my adding expressive features to the readme and engaging with the users.

**Comment by harshsingh32** [comment]
Sir, please assign this issue to me under GSSoC'23.

**Comment by harshsingh32** [comment]
I would improve the readme through expressive information about the project that engage the users to contribute to the project.

**Comment by harshsingh32** [comment]
Using attractive phrases and engaging the users through symbols, being expressive to the users, which make them contribute to the project and increase the engagement of the repo, I will improve the readme of this project.

**Comment by nikhil25803** [comment]
Hey @harshsingh32 | This issue has already been assigned.

**Comment by harshsingh32** [comment]
Sir that's not fair that was my call.

**Comment by nikhil25803** [comment]
Calm down bro Calm down @harshsingh32 😅
Create another issue regarding improving the `documentation.md()` file, I'll assign you that
