### ISSUE TITLE
Most Used Language by User

### ISSUE THREAD

**Issue by sahilsapariya** [Clueless-Community/scrape-up#162]
### Solution
**There are two methods for implementing function**

- _Using API_
- _Calculating by lines of codes from all the files of all the repositories_

I can implement function by first method, second method is also possible but it would be more time consuming and difficult to implement.
So give me chance to implement this function during GSSoC'23.

**Comment by nikhil25803** [comment]
Great idea, add this in the `User` class with the `most_used_language()` method !!
**Note**
Do not use API, as we are trying to build an API alternative.

**Comment by sahilsapariya** [comment]
Anyone wants to advise me what would be the better approach for `most_used_language()` method

I have one idea that we have to scrap the lines of code from all the repos and files present in that, and find out language containing most number of lines. But I don't understand how to deal with it.

Please put your thoughts here !

**Comment by yash7raut** [comment]
Can't we do this by identifying the extensions of all the files present in that repo?

**Comment by BabarRasheed** [comment]
Hi,
I'm Babar Rasheed (Contributor GSSOC'23)
Many websites don't offer API so to tackle this we can use Web Scraping to access data in easy and structured manner.
Python libraries like bs4, BeautifulSoup, Scrapy, Selenium, etc. are generally used for web scraping.
Here I'm willing to apply these libraries and use an effective way of Multiprocessing to speed up Web Scraping.
Multiprocessing is very helpful when multiple URLs are scraped to get the data. It will perform scraping on multiple URLs thus saving our time.

**Comment by nikhil25803** [comment]
@sahilsapariya, any update?

**Comment by sahilsapariya** [comment]
I'm still confuse about What should be the method for calculation of most used language in repository?
and how to traverse through all the files of repository because there will be different folder structure in every repository
