### ISSUE TITLE
ADD NEWW LOOK TO THE README 

### ISSUE THREAD

**Issue by Ayush-Tibrewal** [Clueless-Community/scrape-up#163]
I have given your README a completely new look and added simplified text that is highly useful for new contributors. I incorporated the text you provided and made sure it enhances the overall appeal of the document. Please review my changes and let me know if there are any issues. If you have any concerns, feel free to assign me to the relevant issue, and I will address it as soon as possible.

**Comment by nikhil25803** [comment]
Go for it @Ayush-Tibrewal.
