### ISSUE TITLE
Name of an Instagram user

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#165]
### Proposed Method
`.name()`

### Description
Get the name of an Instagram user with the username provided.

## To what class it belongs?
`Users`

### Note
+ Make all the changes in the `src/scrape_up/instagram/users.py` file within the `User()` class.
+ Use a private method ` __scrape_page` to scrape the page.
+ Include the method in the `documentation.md` file.
+ Upload a screenshot with the PR, demonstrating the method.

**Comment by kruti002** [comment]
Hi @nikhil25803 I am Gssoc 2023 contributor and would like to work on this issue please do assign it to me .

**Comment by nikhil25803** [comment]
Go ahead @kruti002

**Comment by tanishkunigiri** [comment]
Isn't it a violation to web scrape a name according to Instagram?

**Comment by urgetolearn** [comment]
Hi @nikhil25803 I would like to work on this issue please do assign it to me .

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?

**Comment by nikhil25803** [comment]
Any update @
