### ISSUE TITLE
Get the following count of an Instagram user.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#166]
### Proposed Method
`.following()`

### Description
Create a method to fetch the numbers of people a user is following.

## To what class it belongs?
`Users`

### Note
+ Make all the changes in the `src/scrape_up/instagram/users.py` file within the `User()` class.
+ Use a private method ` __scrape_page` to scrape the page.
+ Include the method in the `documentation. md` file.
+ Upload a screenshot with the PR, demonstrating the method.

**Comment by dahakeadi15** [comment]
Hey @nikhil25803 I am a GSSoC'23 contributor. I would like to work on this issue. Please do assign me to this.

**Comment by Manikantan-S** [comment]
@nikhil25803 I am interested to work on this project .Please assign me with this issue

**Comment by swetha3456** [comment]
Hi @nikhil25803, I'd really like to work on this issue. It would be great if you could assign it to me.

**Comment by Yaswanth14** [comment]
Hey, @nikhil25803 I would like to work on this feature can you assign me so that I can start working

**Comment by nikhil25803** [comment]
Go for it @dahakeadi15 !!

**Comment by dahakeadi15** [comment]
Hi, **@nikhil25803** !
I have made the necessary changes and have created a PR. Please review it.
