### ISSUE TITLE
Ideation 💡

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#167]
### As we have covered GitHub, what platform we should cover next? 🤔
Do add a comment here and let us know 💫

## Platforms Decided
+ Twitter 🐥
+ LinkedIn 💼
+ Kaggle 🧠
------

![IHaveAnIdeaHomelanderGIF](https://github.com/Clueless-Community/scrape-up/assets/93156825/bf482932-902b-4b22-a6d9-20c2308cb9fa)

**Comment by Manikantan-S** [comment]
Twitter ,instagram,medium

**Comment by yash7raut** [comment]
We can scrape data from amazon.com

**Comment by swetha3456** [comment]
We can also scrape data from YouTube and Facebook in addition to the sites mentioned here.

**Comment by nikhil25803** [comment]
Guys, what about LinkedIn !!! 🤔

**Comment by Manikantan-S** [comment]
Nice idea 
Pls allow me to work on it

**Comment by VardaPanchal005** [comment]
Please assign me the project for flipkart,amazon,myntra

**Comment by nikhil25803** [comment]
Hey @VardaPanchal005, this issue will not be assigned to someone, this is a place to discuss ideas.

**Comment by infernalsaber** [comment]
maybe google images?

**Comment by nikhil25803** [comment]
> maybe google images?

Sounds good. So, like downloading images by keywords?
Like, `google.images(obj="computer")` ?

**Comment by infernalsaber** [comment]
yeah probably. does that sound like an issue worth working on? coz in that case, i'd like to

**Comment by VardaPanchal005** [comment]
> Hey @VardaPanchal005, this issue will not be assigned to someone, this is a place to discuss ideas.

Okay sir. But is that an idea worth working on?

**Comment by nikhil25803** [comment]
Yes, one more !! Kaggle will be an awesome choice to go 💫

**Comment by VardaPanchal005** [comment]
What about stock market analysis, Sports score and statistic ?

**Comment by infernalsaber** [comment]
@nikhil25803 so do I have the go ahead to make an issue?

**Comment by tusharv01** [comment]
Hi,

I'm a GSSoC 2023 contributor and would like to work on this issue. It would be great if you could assign it to me.

Thanks and regards,
tushar verma

**Comment by building-the-future** [comment]
Hey!!

I'm a contributor in GSSoC 2023 and would like to Contribute on this issue. It would be Awesome if you assign this work to me.

Thanks and regards,
Kunal shrivastava

**Comment by karthikbhandary2** [comment]
We can scrape the data from medium

**Comment by nikhil25803** [comment]
Great idea @karthikbhandary2

**Comment by karthikbhandary2** [comment]
So @nikhil25803 should I create a new issue to work on it?

**Comment by nikhil25803** [comment]
Yes, go ahead @karthikbhandary2

**Comment by karthikbhandary2** [comment]
yeah, where should I add the code along with the Instagram and GitHub ones? @nikhil25803

**Comment by hustler0109** [comment]
In my thought Reddit would be a good platform for web scraping as it consists of numerous communities - "subreddits" dedicated to specific interests, such as technology, news, gaming, fashion, and more. This diverse content makes Reddit a valuable source for scraping data on various subjects. Reddit is primarily driven by user-generated content in the form of posts, comments, and discussions. This provides a vast amount of data that can be scraped and analyzed for sentiment analysis, trend identification, opinion mining, or content aggregation. Most of the content on Reddit is publicly accessible, meaning that you don't usually need an account or special permissions to view the posts and comments. This accessibility makes it easier to scrape data from Reddit compared to platforms that require authentication or have strict access restrictions. Reddit follows a structured format for its content, with clear hierarchies of posts, comments, and replies. This structure simplifies the process of navigating and extracting data from Reddit using scraping techniques. Additionally, Reddit provides an API (Application Programming Interface) that allows developers to access data in a structured and controlled manner.Reddit has a large and active user community, resulting in a constant flow of new content and discussions. This makes Reddit a real-time source of information and opinions, which can be valuable for monitoring trends, gathering up-to-date data, or conducting sentiment analysis in real-time. Reddit provides an official API (known as the Reddit API) that allows developers to access and retrieve data from Reddit in a controlled and authorized manner. The API provides endpoints to fetch posts, comments, user information, and other data, making it easier to scrape Reddit content programmatically.

**Comment by Schefflera-Arboricola** [comment]
Hi! Just wanted to share [this](https://www.kaggle.com/datasets/aditijuneja/github-bipartite-graph-datasetdevelopersrepos/code?datasetId=3526115&sortBy=dateRun&tab=profile) dataset I created with the help of the scrape-up package. Feel free to play with it.

Thank you :)

**Comment by nikhil25803** [comment]
That's great @Schefflera-Arboricola | This is what our motive is, glad you shared.

Thank a lot ✨
