### ISSUE TITLE
Improving the documentation of readme file

### ISSUE THREAD

**Issue by harshsingh32** [Clueless-Community/scrape-up#168]
Sir, I would like to improve the documentation.md file by using catchy phrases and expressive information that engage the users to repo, so that they contribute to the Project.

**Comment by harshsingh32** [comment]
I would like to work on this issue please assign this issue to me under GSSoC'23.

**Comment by nikhil25803** [comment]
Go ahead @harshsingh32 :))

**Comment by VardaPanchal005** [comment]
I would like to work on the issue.
