### ISSUE TITLE
Lack of error handling

### ISSUE THREAD

**Issue by okaditya84** [Clueless-Community/scrape-up#170]
### Description
I have identified a potential vulnerability:

Lack of Error Handling: The code uses a try-except block to catch exceptions during the scraping process. However, the except block does not specify the specific exception being caught. This can make it difficult to handle specific errors and troubleshoot issues. It is generally recommended to catch specific exceptions or at least the base Exception class to provide more accurate error handling.

**Comment by nikhil25803** [comment]
Sounds good @okaditya84, go ahead :))
