### ISSUE TITLE
Feature Extend: Twitter

### ISSUE THREAD

**Issue by AlapanDas** [Clueless-Community/scrape-up#171]
**Is your feature request related to a problem? Please describe.**
Extending the feature to Twitter
 @nikhil25803

**Comment by nikhil25803** [comment]
Hey @AlapanDas, scraping data from Twitter is not easy. Please try it once, and get back to me. If you succeed, I'll assign you this issue.

**Comment by nikhil25803** [comment]
Okay @akuldeepj, go give it a try :))

**Comment by GayathriManeksha** [comment]
@nikhil25803 since @akuldeepj is also working on the Twitter API should I wait till he commits his work to make my commits?

**Comment by akuldeepj** [comment]
I might not be available for few days and there is like more than 40% work to do so in order to stop the further development of the project I will be leaving 
**Thank You 🙂**

**Comment by mridul45** [comment]
As a GSSOC 23 contributor I would like to work on the issue

**Comment by nikhil25803** [comment]
Go ahead @mridul45

**Comment by mridul45** [comment]
Thx alot

**Comment by mridul45** [comment]
Can you also assign the level to the issue

**Comment by mridul45** [comment]
@nikhil25803

**Comment by nikhil25803** [comment]
The levels are dependent upon the quality of changes you made, so will assign the level when you raise a PR.
