### ISSUE TITLE
contribution.md file : Spelling error

### ISSUE THREAD

**Issue by dikshapadi** [Clueless-Community/scrape-up#174]
### Description
Found a spelling error in the contribution.md file

### Example Usage
'teh' corrected as 'the'

**Comment by dikshapadi** [comment]
@nikhil25803 I would like to correct the spotted spelling error, could you assign me this please?

**Comment by nikhil25803** [comment]
Fix it @dikshapadi

**Comment by dikshapadi** [comment]
It has been fixed, kindly review my pull request
