### ISSUE TITLE
Sports Scores and Statistics

### ISSUE THREAD

**Issue by VardaPanchal005** [Clueless-Community/scrape-up#177]
It can be of two types-

Firstly it can provide the data to any newbie like if I'm new to football and I want to understand it, It can provide me relevant details instead of difficult and meaningless descriptions.

Secondly Creating a module that scrapes sports scores, player statistics, and team information from sports websites or APIs. Users can specify the sport, league, or teams of interest and gather data such as match results, player performance, standings, or upcoming fixtures.

I would like to work on the issue

**Comment by Veena4512** [comment]
@nikhil25803  can I know the exact issue like what you want to make us to do ?

**Comment by nikhil25803** [comment]
Great idea @Veena4512. But you have to choose one sports site which you will use to scrape data. Which website or platform are you ar looking to scrape? Do mention, please.

**Comment by Veena4512** [comment]
@nikhil25803  sir I guess you should tag @VardaPanchal005

**Comment by Veena4512** [comment]
@VardaPanchal005 if you want to collaborate please let me know.

**Comment by VardaPanchal005** [comment]
> @VardaPanchal005 if you want to collaborate please let me know.

Sure

> Great idea @Veena4512. But you have to choose one sports site which you will use to scrape data. Which website or platform are you ar looking to scrape? Do mention, please.


Maybe sites like NBA  or AFL.

**Comment by deep-poharkar** [comment]
can i take this up?

**Comment by VardaPanchal005** [comment]
> 

Should I go ahead ? @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @VardaPanchal005
