### ISSUE TITLE
Documentation.md File: Spelling Error

### ISSUE THREAD

**Issue by Vikash0122** [Clueless-Community/scrape-up#179]
### Description
[Found a spelling error in Documentation.md file]

### Example Usage
['cal' corrected as 'call']

**Comment by dikshapadi** [comment]
@nikhil25803 Kindly assign this task to me

**Comment by Vikash0122** [comment]
@nikhil25803 i would like to correct this mistake found. Assign me please

**Comment by nikhil25803** [comment]
Go ahead @Vikash0122

**Comment by rahulkothuri** [comment]
I would like to work on this issue. Assign me this issue as I'm a contributor in GSSOC'23.

**Comment by nikhil25803** [comment]
Hey @rahulkothuri, this issue has already been assigned.
