### ISSUE TITLE
Improve documentation of contributing.md file 

### ISSUE THREAD

**Issue by metabiswadeep** [Clueless-Community/scrape-up#180]
Improve the contributing.md file by using  better expressions and that make it easier for users contributing to the repo to be better informed about the guidelines and the manner in which they can contribute to this project.

I would like to do this as a part of GSSoC 23. Please assign this issue to me.

**Comment by nikhil25803** [comment]
It is good I guess, anyway, please specify what changes you will exactly bring to the table.

**Comment by metabiswadeep** [comment]
Mostly grammatical improvements.

**Comment by MeMeee1** [comment]
Hello!
 I'm excited to contribute to the project by improving the contributing.md file for GSSoC'23. A clear and contribution.md  is essential for both the contributor and project success. My plan is to review the current content and make enhancements. Here's what I intend to add:

- Coding Style and Conventions: I'll include a section on coding style and conventions to ensure consistency throughout the project.

- Brief Introduction: I'll provide a concise introduction of the project in the contribution readme, giving potential contributors the necessary context.

- Who Can Contribute: I'll specify who can contribute to the project, making it clear that all interested individuals are welcome.

- Link to Contribution.md: I'll add a link from the readme.md file to the contribution.md file, making it easy for contributors to access the guidelines.

- Types of Contributions: I'll list the types of contributions that are encouraged, such as bug fixes, feature enhancements, documentation improvements, performance optimizations, and code refactoring.

- Getting Started: I'll include the existing content from the getting started section, ensuring that users have the necessary information to start working on the project.

I'm dedicated to creating a comprehensive and user-friendly contribution file that will help contributors understand and engage with the project. If you have any specific requirements or suggestions for the contribution file, please let me know. I'm eager to contribute to the project's success!

**Comment by filza2112** [comment]
Hi, i would like to work on thiss issue, please assign it to me

**Comment by nikhil25803** [comment]
No need for this right now, the contribution guidelines are good enough.
