### ISSUE TITLE
Improving the contribution.md

### ISSUE THREAD

**Issue by harshsingh32** [Clueless-Community/scrape-up#183]
I would like to work on improving the contribution.md of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by nikhil25803** [comment]
Okay, @harshsingh32. Give it a try. Go ahead

**Comment by Anshikaa10** [comment]
Please assign this project to me for improvement.
