### ISSUE TITLE
[GSSoC '23] Spotify Suggestions by Artist

### ISSUE THREAD

**Issue by swetha3456** [Clueless-Community/scrape-up#185]
**Is your feature request related to a problem? Please describe.**
Even the best artists sometimes make bad music. It becomes difficult to find an artist's best music easily.

**Describe the solution you'd like**
When a user enters an artist's name, the script will use the spotipy module in Python to extract the artist's "best" songs, i.e. the songs most listened to by that artist.

**Comment by swetha3456** [comment]
Hi @nikhil25803, please assign this issue to me. I'd like to start working on it.

**Comment by nikhil25803** [comment]
Hey @swetha3456, it requires `SpotifyClientCredentials` right?
We are building alternatives to this stuff using scraping, where there is no rate limit and issue of credentials. Can you implement it using Scaping?

**Comment by swetha3456** [comment]
@nikhil25803 Sure, I can try to implement using scraping.

**Comment by swetha3456** [comment]
@nikhil25803 I did some research on this and simply finding soundtracks by an artist **does not require credentials**. However, the rate limit issue persists, so I'm not sure which would be a better solution. Please let me know what you think. Also, if you're ok with me taking this forward, then please assign the issue to me and add the GSSoC tag. Thanks a lot!

**Comment by nikhil25803** [comment]
Go ahead @swetha3456 , but remember, if this feature is not implemented through scraping. We will not merge it into the project. Go give it a try :))
