### ISSUE TITLE
Script to webscrape cousera

### ISSUE THREAD

**Issue by THEGAMECHANGER416** [Clueless-Community/scrape-up#188]
**Is your feature request related to a problem? Please describe.**
Another method of getting courses from coursera or similar websites

**Describe the solution you'd like**
Scraping coursera using beautifulSoup

**Describe alternatives you've considered**
Can also use scrapy and selenium

**Additional context**
Good first issue for gssoc'23

**Comment by SmritiJain6700** [comment]
Hi, I would like to contribute to this issue.

**Comment by nikhil25803** [comment]
Great idea @THEGAMECHANGER416 
Do remember to make a separate module for this as per the folder structure of the project. 
Do not add all methods at once, start with one method only and make a push :))

**Comment by BabarRasheed** [comment]
Hi,
I'm Babar Rasheed (Contributor GSSOC'23)
Many websites don't offer API so to tackle this we can use Web Scraping to access data in easy and structured manner.
Python libraries like bs4, BeautifulSoup, Scrapy, Selenium, etc. are generally used for web scraping.
Here I'm willing to apply these libraries and use an effective way of Multiprocessing to speed up Web Scraping.
Multiprocessing is very helpful when multiple URLs are scraped to get the data. It will perform scraping on multiple URLs thus saving our time.
