### ISSUE TITLE
Koo Scrapping

### ISSUE THREAD

**Issue by imshvishal** [Clueless-Community/scrape-up#189]
I would like to extend this scrap-up module to work with koo app as well as there are a lot of users on koo.

So please assign me this under GSSOC'23.

**Comment by anandanmukh** [comment]
@imshvishal  I would love to contribute to this project under the GSSoC'23. I will be using the beautiful soup & requests libraries primarily. Could you provide more information about the project's objectives and requirements? I'm eager to understand the current state and future goals.
