### ISSUE TITLE
 Enhancements for InstagramScraper class

### ISSUE THREAD

**Issue by anupammaurya6767** [Clueless-Community/scrape-up#190]
Description:

This proposal suggests enhancements for the InstagramScraper class to improve its functionality, error handling, and code modularity. The following changes have been made:

1. Added specific exception handling: Replaced the general except block with specific exception handling for requests and parsing errors. This ensures more targeted error handling and provides meaningful error messages to users.

2. Wrapped scraping process in a try-except block: The entire scraping process, from making the request to parsing the HTML, has been wrapped in a try-except block. This ensures that any unexpected exceptions during the process are handled gracefully.

3. Separated scraping logic: The scraping logic has been separated into separate functions, __scrape_page() and __parse_page(). This improves code modularity, making it easier to test and reuse the scraping functionality.

**Comment by anupammaurya6767** [comment]
@nikhil25803 I am a GSSOC contributor 
I want to work on this issue
Please assign it to me

**Comment by mohitcs46** [comment]
Hi @nikhil25803 I am Gssoc 2023 contributor and would like to work on this issue please do assign it to me .
