### ISSUE TITLE
Inconsistent Docstrings for methods in Users class of github module

### ISSUE THREAD

**Issue by dahakeadi15** [Clueless-Community/scrape-up#193]
**Is your feature request related to a problem? Please describe.**
I noticed that the methods in the Users class in the GitHub module need consistent doc strings.

**Describe the solution you'd like**
I want to see the doc strings tell what the method does.
E.g., instead of :

```python
def following(self):
    """ "
    Fetch the number of following of a GitHub users.
    """
```

It can be :

```python
def following(self) -> dict | str:
    """Fetch the number of users the GitHub user follows.

    Returns:
        `dict`: a dictionary with the response, data, and message.

        OR

        `str`: an error string
    """
```

**Comment by dahakeadi15** [comment]
Hey, @nikhil25803!

I am a GSSoC'23 contributor. I want to work on this issue.
Please assign me this and add the required tags to this issue.

**Comment by nikhil25803** [comment]
Go ahead @dahakeadi15, fix it :))
