### ISSUE TITLE
To get the current count of profile-views 

### ISSUE THREAD

**Issue by yyuvraj54** [Clueless-Community/scrape-up#195]
New Feature Description
lets suppose a person has created custom profile page( profile readme ) for his account and he has added a profile-views counter script in profile ,This profile views count is important so that other person who are fetching the current views of profile can do work with profile impression or profile importance.

Solution
I can check if the person has created a profile readme and if not created it will simply return 'none' or else if created i am going to check for 'profile views' in readme through beautifulsoup module and going to return the value if found or else 'none'

**Comment by anandanmukh** [comment]
@yyuvraj54  I would love to contribute to this project under the GSSoC'23. I will be using the beautiful soup & requests libraries, where we can find the profile views count in the parsed HTML using appropriate selectors or methods provided by BeautifulSoup. 
Could you provide more information about the project's objectives and requirements? I'm eager to understand the current state and future goals.

**Comment by nikhil25803** [comment]
Go ahead @yyuvraj54

**Comment by yyuvraj54** [comment]
Ok i am working on it.
