### ISSUE TITLE
Twitter - Convert numerical id to username and vice-versa 

### ISSUE THREAD

**Issue by GayathriManeksha** [Clueless-Community/scrape-up#196]
## Proposed Method
Create functions to convert numerical id to username and vice-versa

### Description
The functions can be called to pass username or numerical id as parameters returning the value 

### Example Usage
idtouname(44196397) 
unametoid(elonmusk)

I would like to work on this feature for the Twitter Scrape-up module on creation.
Kindly assign me this issue as part of Gssoc'23

**Comment by nikhil25803** [comment]
Looks good, go ahead @GayathriManeksha

**Comment by Akanksha038** [comment]
Hello @Clueless-Community,
I would like work on Twitter - Convert numerical id to username and vice-versa. 
Please assign me this issue. I would like to work on this issue under GSSOC'23. Please let me fix this issue #196 
Thanks, and regards,
Akanksha Gupta.
