### ISSUE TITLE
Adding examples to the methods in the documentation

### ISSUE THREAD

**Issue by karthikbhandary2** [Clueless-Community/scrape-up#197]
I would like to add some examples to the methods in the documentation.

**Comment by nikhil25803** [comment]
Go ahead @karthikbhandary2, but do not add more than 4/5

**Comment by karthikbhandary2** [comment]
Like not to add examples for more than 4 methods?

**Comment by nikhil25803** [comment]
yes @karthikbhandary2

**Comment by karthikbhandary2** [comment]
ok Understood!

**Comment by karthikbhandary2** [comment]
@nikhil25803 I think you can close this issue since it got merged!
