### ISSUE TITLE
[GSSOC'23] Adding Back to top link at the end of README

### ISSUE THREAD

**Issue by mkswagger** [Clueless-Community/scrape-up#200]
### Description
This issue proposes adding a "Back to Top" link at the end of the README file. The link will provide an easy way for readers to navigate back to the top of the README without scrolling manually. This small addition will enhance the user experience and improve accessibility.

### Example Usage
```markdown
## Table of Contents
- [Introduction](#introduction)
- [Installation](#installation)
- [Usage](#usage)
- ...

## Contributing
...
...

## License
...

---

*[⬆️ Back to Top](#table-of-contents)*

**Comment by Deepak297297** [comment]
Hi , I am a contributor in GSSOC'23, Please assign this issue to me. I have prior knowledge in markdown files and have done a lots of efficient and effective documentation work during my projects and internships.

**Comment by nikhil25803** [comment]
Add it @mkswagger :))

**Comment by mkswagger** [comment]
> Add it @mkswagger :))

Yes On it :)
