### ISSUE TITLE
Web scraper for YT vedios

### ISSUE THREAD

**Issue by Abhinavcode13** [Clueless-Community/scrape-up#208]

**Comment by nikhil25803** [comment]
Great idea @Abhinavcode13 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not add all methods at once, do add one or two methods only at first like, scrapping all the recently uploaded videos of a channel, say `freecodecamp` for example.

All the best

**Comment by BabarRasheed** [comment]
Hi,
I'm Babar Rasheed (Contributor GSSOC'23)
Many websites don't offer API so to tackle this we can use Web Scraping to access data in easy and structured manner.
Python libraries like bs4, BeautifulSoup, Scrapy, Selenium, etc. are generally used for web scraping.
Here I'm willing to apply these libraries and use an effective way of Multiprocessing to speed up Web Scraping.
Multiprocessing is very helpful when multiple URLs are scraped to get the data. It will perform scraping on multiple URLs thus saving our time.

**Comment by Mihan786Chistie** [comment]
@nikhil25803 assign me the issue

**Comment by PayalPadmalyaPrusty** [comment]
@nikhil25803 I want to contribute.Please assign me this issue

**Comment by nikhil25803** [comment]
Hey @PayalPadmalyaPrusty | @Mihan786Chistie is already assigned to this issue yesterday only. 
Please try adding some other feature or resolve a bug, if you found any.
