### ISSUE TITLE
To integrate scrape_up with website!

### ISSUE THREAD

**Issue by ombhojane** [Clueless-Community/scrape-up#211]
**Is your feature request related to a problem? Please describe.**
If you run GitHub username program, I've observed that it always run in terminal. Let's create something creative! Let's implement in a website

**Describe the solution you'd like**
Using Streamlit, I can create a user friendly portal, where, user can see list of Repositories, Stars on GitHub profile, List of Followers, List of Achievements, Pinned Repositories and much more...

**Describe alternatives you've considered**
We can host our website supported by Scrape-Up

Can you please assign this issue to me..
GSSOC 2023 :)

**Comment by nikhil25803** [comment]
It is not just for the terminals, when you work with Python frameworks or even cloud services like AWS lambda you can use this package to integrate it into that :))

The terminal ones are just an example.
