### ISSUE TITLE
Make ease of scraping tweets

### ISSUE THREAD

**Issue by Swetha-Baskaran** [Clueless-Community/scrape-up#212]
@nikhil25803  as there are some Python packages that provide this support, I feel it would be better scrape-up and can also offer the support of scaping tweets of a particular account easily.

**Comment by nikhil25803** [comment]
Great idea @Swetha-Baskaran, but Twitter does not allow scrapping and even if it does, it requires credentials. Also, we are not looking forward to adding more dependencies. If you can implement it with `bs4` or `scrappy`, you can try it.

**Comment by Swetha-Baskaran** [comment]
I'll try my best.

**Comment by nikhil25803** [comment]
Any update @Swetha-Baskaran?
