### ISSUE TITLE
Dataset of Movies by scrapping -[GSSOC'23]

### ISSUE THREAD

**Issue by Durga-Sowjanya-Sanku** [Clueless-Community/scrape-up#213]
**Is your feature request related to a problem? Please describe.**
1. Whenever I wanted to find the movies of particular rating at a one place it's difficult for me
2. When I wanted to find the movies of particular domain
3. When I wanted to find the movies of particular artist
It's really not easy to get all this information

**Describe the solution you'd like**
 I am thinking to create a dataset by scrapping all the information regarding the movies, rating, actors, so on.

Link from where I want to scrap: https://www.themoviedb.org/movie

## Please allow me to work on this under GSSOC'23

**Comment by nikhil25803** [comment]
Go ahead @Durga-Sowjanya-Sanku 
Great idea, go ahead.
**Note**
+ Create a separate module for this, as per the folder and project structure

All the best

**Comment by BabarRasheed** [comment]
Hi,
I'm Babar Rasheed (Contributor GSSOC'23)
Many websites don't offer API so to tackle this we can use Web Scraping to access data in an easy and structured manner.
Python libraries like bs4, BeautifulSoup, Scrapy, Selenium, etc. are generally used for web scraping.
Here I'm willing to apply these libraries and use an effective way of Multiprocessing to speed up Web Scraping.
Multiprocessing is very helpful when multiple URLs are scraped to get the data. It will perform scraping on multiple URLs thus saving our time.
