### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by VSatwika** [Clueless-Community/scrape-up#214]
- I would like to request the addition of a code of conduct to the repository.

 - Having a code of conduct is essential to establish a welcoming and inclusive environment for all contributors.

 - It provides clear guidelines for expected behavior and helps create a safe and respectful space for collaboration.

 - I am contributing under GSSoC'23. Could this issue be assigned to me?

**Comment by Pratham-Handa** [comment]
@nikhil25803 can i work on this issue cause its 3 days since she has been assigned
? i am contributing in GGsoc'23 too
