### ISSUE TITLE
Post count for Instagram

### ISSUE THREAD

**Issue by karthikbhandary2** [Clueless-Community/scrape-up#216]
**Is your feature request related to a problem? Please describe.**
Currently, the Instagram scrap_up only has two methods to get the followers' count and the following count. I would like to add a new method to get the post count. 

**Describe the solution you'd like**
I will be using beautiful soup to do this.

**Comment by BabarRasheed** [comment]
Hi,
I'm Babar Rasheed (Contributor GSSOC'23)
Many websites don't offer API so to tackle this we can use Web Scraping to access data in easy and structured manner.
Python libraries like bs4, BeautifulSoup, Scrapy, Selenium, etc. are generally used for web scraping.
Here I'm willing to apply these libraries and use an effective way of Multiprocessing to speed up Web Scraping.
Multiprocessing is very helpful when multiple URLs are scraped to get the data. It will perform scraping on multiple URLs thus saving our time.

**Comment by ankitanain** [comment]
Approach:
1. Utilize the Instagram API by making a request to the `users/{user_id}` endpoint and extracting the `media_count` field from the response.
2. Alternatively, use web scraping techniques with a library like BeautifulSoup in Python to parse the HTML of the account's profile page and extract the post count from the corresponding HTML element.
@nikhil25803 Sir, please assign this issue to me under GSSOC'23.

**Comment by nikhil25803** [comment]
Go ahead @karthikbhandary2

**Comment by karthikbhandary2** [comment]
Hey @nikhil25803 I just noticed that the Instagram module in scrape up has an error when I am using the `following()` method. 
![error](https://github.com/Clueless-Community/scrape-up/assets/34509856/96032ea3-d3a8-47e8-85a4-7aa05611e274)

**Comment by karthikbhandary2** [comment]
There is an error in the `following()` method. I am following 560 accounts on Instagram but it is showing it as 108.
![error](https://github.com/Clueless-Community/scrape-up/assets/34509856/d61bd306-5d5f-4fb7-98c4-16f80ddf9f39)

**Comment by karthikbhandary2** [comment]
I've observed that the meta tag is not showing the following count. I can change the code so as to show a msg saying "Following count not available" or should I do something else? @nikhil25803 
![following error](https://github.com/Clueless-Community/scrape-up/assets/34509856/49fc467b-1b90-4253-bf23-ff15348b175b)
