### ISSUE TITLE
Scrapping Stock Prices

### ISSUE THREAD

**Issue by brohithkr** [Clueless-Community/scrape-up#221]
**Is your feature request related to a problem? Please describe.**
1. Stock Price data is needed to analyze market and train ai/ml models on stock data.
2. It's difficult to scrape stock price through third party APIs because of api keys , traffic limitation etc.
3. It would be nice to have a stock scrapping tools which use our systems processing power to scrape data we require and export to  file formats we desire.

**Describe the solution you'd like**
I would like to extend the scrape-up package's features to scrape Stock prices through sites like:

- [ Investing.com](https://in.investing.com/)
- [ Google Finance](google.com/finance)
- and others.

**Describe alternatives you've considered**
I am open to feedback and any other features. 

**Additional context**
Please assign this issue to me as a GSSoC'23 contributor if admins think this feature is worth working on. Admin's feedback and thought on this feature is much appreciated.

**Comment by nikhil25803** [comment]
Go ahead @brohithkr

**Comment by brohithkr** [comment]
Hey @nikhil25803 just wondering 😅 you put level 3 tag in PR right? Which tag would they consider level tag in PR or in issue?

**Comment by nikhil25803** [comment]
In PR @brohithkr
