### ISSUE TITLE
Scrapping data from twitter

### ISSUE THREAD

**Issue by riyasachdeva04** [Clueless-Community/scrape-up#222]
Is your feature request related to a problem? Please describe.

Twitter is used by millions of users to display their take on various issues ranging from micro to macro level. I would like to scrape tweets regarding important topics to analyse the take of people over different issues.

Describe the solution you'd like
I am thinking to create a dataset by scrapping all the information regarding the account, likes, bookmarks, retweets and followers so on using official twitter api.

Link from where I want to scrap: https://twitter.com/home

Please allow me to work on this under GSSOC'23

**Comment by nikhil25803** [comment]
Sorry, we are not using any APIs in this project.
