### ISSUE TITLE
adding some more important methods for Github pull_requests

### ISSUE THREAD

**Issue by shivvamm** [Clueless-Community/scrape-up#223]
**Is your feature request related to a problem? Please describe.**
No this feature is an addition or we can say extension to the current feature in the github section 

**Describe the solution you'd like**
I would like to add some more important methods like created_at, updated_at, state, description, merged_at, commits_url, diff_url, html_url

**Describe alternatives you've considered**
there is no alternative i just want to add these important methods 

**Additional context**

**Comment by shivvamm** [comment]
can you please assign this issue to me under GSsoc 23

**Comment by nikhil25803** [comment]
Hey @shivvamm, do not make a PR before getting assigned. It is not a good practice, take care the next time.
Anyways, requested some changes from your side. Please look into it.

**Comment by shivvamm** [comment]
i made the necessary changes please look at the PR
