### ISSUE TITLE
Adding GitLab Scraping Functionality to Scrape-Up

### ISSUE THREAD

**Issue by shivvamm** [Clueless-Community/scrape-up#225]
**Is your feature request related to a problem? Please describe.**
Many users rely on the Scrape-Up tool to fetch details from GitHub, but they also want similar functionality for GitLab, which is a significant platform for hosting code repositories. The current Scrape-Up tool lacks support for GitLab scraping, making it challenging for users to retrieve GitLab-related information.

**Describe the solution you'd like**
I propose adding GitLab scraping functionality to Scrape-Up. By integrating GitLab support, users will gain the ability to fetch various details from GitLab, such as user profiles, project details, and repositories.

To implement this, we can introduce a GitLab class within Scrape-Up. The class will include methods for scraping specific information from GitLab using the BeautifulSoup library. Key methods could include:

get_profile_info(): Retrieves user profile information from GitLab, including name, bio, and avatar URL.
get_repositories(): Fetches repository details from GitLab, including names and descriptions.
get_project_details(project_id): Retrieves project-specific details from GitLab, such as project name and last activity timestamp.

**Additional context**
Adding GitLab scraping functionality to Scrape-Up will expand its capabilities and cater to users who rely on GitLab for their code hosting needs.

**Comment by nikhil25803** [comment]
Go ahead @shivvamm

**Comment by shivvamm** [comment]
> Go ahead @shivvamm 

Okay 👍

**Comment by shivvamm** [comment]
its Done please check the PR

**Comment by shivvamm** [comment]
The PR id #323
