### ISSUE TITLE
Scrapping Medium Data

### ISSUE THREAD

**Issue by karthikbhandary2** [Clueless-Community/scrape-up#228]
**Is your feature request related to a problem? Please describe.**
This feature is about getting data from the blogging platform called Medium.

**Describe the solution you'd like**
I want to get the data like for example the no of blogs written, the followers, etc.,

**Comment by karthikbhandary2** [comment]
ok @nikhil25803

**Comment by karthikbhandary2** [comment]
Hey, @nikhil25803 can you provide any resources to follow?

**Comment by PayalPadmalyaPrusty** [comment]
@nikhil25803 I want to contribute.Please assign me
