### ISSUE TITLE
Updating the following() function in instagram.

### ISSUE THREAD

**Issue by karthikbhandary2** [Clueless-Community/scrape-up#232]
### Description
When I was working on the `posts()` function I came across this issue where my profile was not showing the no of accounts that I was following. I made sure to check with two to three others but they have it. When I try to use the `following()` function it is returning the post count instead of the following count. I want to update the function so as to resolve this. A screenshot of the error.
![error2](https://github.com/Clueless-Community/scrape-up/assets/34509856/0a108872-7d90-4ed3-ad2e-e32e39419fb1)

## To what class it belongs?: 
This belongs to Instagram.

**Comment by nikhil25803** [comment]
Go ahead @karthikbhandary2
