### ISSUE TITLE
 scrape Spotify Data

### ISSUE THREAD

**Issue by samanth2012** [Clueless-Community/scrape-up#233]
Is your feature request related to a problem? 
 By scraping the data, you can perform custom analysis on the playlist, track attributes, and user interactions. This can help you gain deeper insights into your music preferences, track popularity, genre patterns, and more.
Pls assign this issue to me @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @samanth2012  :))
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch all the music of Dua Lipa, `spotify.artist(name-"dua lipa")`.

![DuaLipaCoolGIF](https://github.com/Clueless-Community/scrape-up/assets/93156825/6bcf3d66-c3e3-4eba-8347-9c4d7334e0ea)

**Comment by samanth2012** [comment]
thanks sir

**Comment by nikhil25803** [comment]
Hey @samanth2012, any update?
