### ISSUE TITLE
Scrape Internshala data

### ISSUE THREAD

**Issue by patnaikankit** [Clueless-Community/scrape-up#234]
**Is your feature request related to a problem? Please describe.**
1. When you are looking for internships you often have to go through many posts.
2. It is very difficult to go through all the posts to find an internship which is suitable for you.
3. .It would be nice to have scrapping tools in our system's processing power to scrape data we require and export it to file formats we desire.

**Describe the solution you'd like**
I would like to scrape data from the following websites: 
1. https://internshala.com/student/dashboard
 
If you wish I can scarpe other internships providing websites like  cuvette https://cuvette.tech/

**Describe alternatives you've considered**
I'd appreciate it if you could give me a clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Please assign this issue to me as a GSSoC'23 contributor if admins think this feature is worth working on. Admin's feedback and thoughts on this feature are much appreciated.

**Comment by nikhil25803** [comment]
Go ahead @patnaikankit   :))
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch all the internship openings in data science.
+ `internshala.openings(category="data science")`
