### ISSUE TITLE
Scrape Job Description and matches Resume

### ISSUE THREAD

**Issue by akashg001** [Clueless-Community/scrape-up#237]
**Is your feature request related to a problem? Please describe.**
check the % of resumes matches with the particular job matches or not.

**Describe the solution you'd like**
Provide the JD URL and resume. finding the similarities between both and providing the % resume matches with that particular JD.

**Comment by nikhil25803** [comment]
Hey @akashg001, this doesn't match the goal of the project. Though it is a good idea, you can build this as your project :))
