### ISSUE TITLE
Scrape IMDb website 

### ISSUE THREAD

**Issue by Shreyg-27** [Clueless-Community/scrape-up#239]
**Is your feature request related to a problem? Please describe.**
IMDb (Internet Movie Database) is a popular online database that provides information about movies, TV shows, actors, directors, and other related content. It is one of the most comprehensive sources of information about films and television series.
Scraping data from IMDb using Python can be used for data analysis. 

**Describe the solution you'd like**
I would like to scrape data from : 
1) https://www.imdb.com/search/title/?count=100&groups=top_1000&sort=user_rating
2) https://www.imdb.com/chart/top/

**Comment by Shreyg-27** [comment]
Hi @nikhil25803 !
I have raised this issue under gssoc'23. It would be great if you could assign this issue to me. 
Thank you.

**Comment by nikhil25803** [comment]
Great Idea @Shreyg-27 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on each method, like create a method first to scrape the detail of a movie.
Folder name - `IMDB`
Class name - `movies`
Eg. 
```python
movie = imdb.movie(name="Avengers")
print(movie.details())
```

This returns the JSON format data of the movie of which the instance has been created.

![RobertDowneyJrTonyStarkGIF](https://github.com/Clueless-Community/scrape-up/assets/93156825/a276fd4d-58d6-4a59-af14-ff1503ae5d5e)

Good Luck with the issue :))
