### ISSUE TITLE
Coding questions Scrapper

### ISSUE THREAD

**Issue by singh-anushka** [Clueless-Community/scrape-up#240]
**Is your feature request related to a problem? Please describe.**
Leetcode, Codeforces is one of the most popular platforms to practice several Data Structure questions, and for doing competitive coding.

**Describe the solution you'd like**
Using Python I would like to scrape the Leetcode and Codeforces questions in one place.

I am a GSSoC23 contributor please assign me this issue.
@nikhil25803

**Comment by nikhil25803** [comment]
Great idea @singh-anushka 
But let's cover `Leetcode` first.

**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on each method, like getting the rank of a leetcode with username provided.

Eg.
```python
user = leetcode.user(username="nikhil25803")
user.rank()
```

This returns the leetcode rank of the user.
![CodingGIF](https://github.com/Clueless-Community/scrape-up/assets/93156825/822e3e45-7f27-4f11-8a0d-4a24a6e73210)

All the best with the issue :))
