### ISSUE TITLE
[New Feature] Get number of watches for a repository in Github

### ISSUE THREAD

**Issue by Sar-thak-3** [Clueless-Community/scrape-up#242]
**Is your feature request related to a problem? Please describe.**
I think the number of people watching the repository in Github is still undone.

**Describe the solution you'd like**
I will add the function to get the same. I am already a contributor at this repository so I am completely aware of the guidelines. Kindly assign me the issue under GSSoC 2023.

**Comment by nikhil25803** [comment]
Add this method @Sar-thak-3
