### ISSUE TITLE
Adding the feature to gather real-time data from Twitter by combining web scraping and sentiment analysis

### ISSUE THREAD

**Issue by Nancy248** [Clueless-Community/scrape-up#243]
why this issue?
1. It's crucial to gather real time data, understanding public opinion and analyzing feedback.
2. it can enhance customer satisfaction and getting insights into public tweets.

therefore I would like to work on this issue under Gssoc'23
Kindly assign  me this issue.

**Comment by nikhil25803** [comment]
Sorry @Nancy248 !! This doesn't match the goal of the project.
Though it sounds good for a personal project, you may give it a try there.
