### ISSUE TITLE
Need a proper PR template. 

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#244]
I need a proper PR template for this project which does have fields as mentioned below

### Checks
+ Have you followed the code format of the project?
+ Have you returned the output/response with a message?
+ Have you implemented the tr-catch method?
+ Have you included the method/class in the `documentation? md`

## Screenshots
Upload the screenshot of the output for validation (Compulsory).

You may add more relevant fields accordingly, but these mentioned points must be there.

**Comment by Yashi11** [comment]
May help in this one under gssoc'23?

**Comment by nikhil25803** [comment]
Sure @Yashi11. Go ahead

**Comment by Yashi11** [comment]
Sent pull request for the same. Pls let me know if any changes are needed in the same.
Regards

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by nikhil25803** [comment]
PR for this has already been made @sagnik-p
