### ISSUE TITLE
Scraping Hotel Details from TripAdvisor for Input City

### ISSUE THREAD

**Issue by Yashi11** [Clueless-Community/scrape-up#246]
**Is your feature request related to a problem? Please describe.**
Its quite frustrating to scrape hotel data from websites like TripAdvisor as they can be difficult to navigate specially when we need to scrape information repeatedly for a time frame.

**Describe the solution you'd like**
Description:
As part of our project, we need to implement a data scraping solution to extract hotel details from TripAdvisor for a given input city. This issue aims to develop the necessary functionality and infrastructure to retrieve hotel information from TripAdvisor's website.

Requirements
  - The system should allow the user to input the desired city for hotel scraping.
  -  The solution should utilize web scraping techniques to extract relevant hotel details, such as hotel name, rating, address, and price range.
 -  The scraped data should be stored in a structured format (e.g., JSON, CSV) for further analysis and integration into our project's database.
  - Error handling mechanisms should be implemented to handle potential issues during the scraping process, such as connection errors or unexpected website changes.

**Describe alternatives you've considered**

  **If the TripAdvisor website is not suitable, we may use any other internationally popular website. Range of extracted information can also be limited to location review rating in the start and other information support can be added later.
----**
If this Feature request is accepted, I would like to work on this under GSSOC'23.

**Comment by nikhil25803** [comment]
Sounds good @Yashi11 

**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on each method, like creating a method first to scrape hotels, locations, and current prices.
+ The output must be in JSON format.
