### ISSUE TITLE
Youtube channel scrapper

### ISSUE THREAD

**Issue by okaditya84** [Clueless-Community/scrape-up#255]
**Is your feature request related to a problem? Please describe.**
If a content creator or developer needs stats of Youtube channels to know how other channels are growing, there is no source available that one can get these.

**Describe the solution you'd like**
You-Scrap will be a program that can get these analytics of every youtube channel by just entering channel ID.
Creators and developers can see the relevant figures and also the visuals of the performance of channel.

**Describe alternatives you've considered**
Alternate solution is a tool that can take video's URL and give you the video's summary.

**Comment by nikhil25803** [comment]
Hey @okaditya84, sounds great 

**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on each category, for example create a method to fetch links of all the playlist by a channel.

**Comment by okaditya84** [comment]
> Sir assign me this. I will resolve it.
> 

With all due respect, I already opened a PR with the solution of the issue.

**Comment by PayalPadmalyaPrusty** [comment]
@nikhil25803 I want to contribute.Please assign me
