### ISSUE TITLE
Leetcode Scrapper

### ISSUE THREAD

**Issue by Hansika002** [Clueless-Community/scrape-up#259]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to the problem of efficiently scraping and extracting data from the Leetcode website to enable analysis and insights for developers.

**Describe the solution you'd like**
The feature request is to add the functionality of retrieving the rank of a Leetcode user based on their username, which involves scraping the Leetcode website and extracting the user's rank information for further analysis and display.

**Describe alternatives you've considered**
Enhancing the Leetcode scrapper to include an alternative solution for retrieving user rankings by leveraging the Leetcode API.

I request @nikhil25803  to kindly assign this issue to me under GSSoC'23. 
Thanks You!!

**Comment by Anjali2312-Thombare** [comment]
hey @nikhil25803  please assign me this issue

**Comment by Hansika002** [comment]
@nikhil25803 
I have almost completed the implementation of the task. Could you please assign it to me for further progress and finalization?

**Comment by nikhil25803** [comment]
Go ahead @Hansika002 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the rating or rank of the user with the username provided.

@Anjali2312-Thombare  | You can collaborate with @Hansika002, and work on the issue which @Hansika002 hasn't worked upon.
