### ISSUE TITLE
Get a list of all starred repositories of a user

### ISSUE THREAD

**Issue by codingis4noobs2** [Clueless-Community/scrape-up#26]
### Description
With the help of get_starred_repos(), one can easily scrape out the list of starred repos of any user.

### Example Usage
```python
from scrape_up import github
user =  github.Users(username="nikhil25803")
print(user.get_starred_repos())

# Output - Starts listing all starred repos.......
```
I want to work on this issue under JWOC.

**Comment by nikhil25803** [comment]
Go ahead @codingis4noobs2.
