### ISSUE TITLE
Scraping Educational Website 

### ISSUE THREAD

**Issue by Shreyg-27** [Clueless-Community/scrape-up#263]
**Is your feature request related to a problem? Please describe.**
We can scrape important details from the website, like the different courses and questions, etc.

**Describe the solution you'd like**
It will help in extracting details like - Courses, Tutorial, Blog, Notes, etc.

**Describe alternatives you've considered**
I am open to all the suggestions or improvisations required. 
The link - https://www.codewithharry.com/

**Comment by nikhil25803** [comment]
Go ahead @Shreyg-27 , but you have to generalize or choose one educational website which is common and beneficial for all in general. Choosing a specific website will be a biased decision, right?

Do you have any such website in mind?

**Comment by Shreyg-27** [comment]
Hi! @nikhil25803! 
Right now, I don't have any other website in my mind, and surely, I get your point that generalization is necessary. If you could suggest any website, I can work on that, or if fine, I can work on this issue and raise another issue with more generalized content.

**Comment by nikhil25803** [comment]
You can go for any government educational websites, do a bit of research, and get back to me. I'll assign you this issue.

**Comment by Shreyg-27** [comment]
Hi, @nikhil25803! 
I found this government educational site - https://onlinecourses.nptel.ac.in/ 
This site has courses offered by IITs. for students to learn. 
If this is fine for you, I can work on this. 
Thank you!

**Comment by nikhil25803** [comment]
Go ahead @Shreyg-27 
**Note**
+ Create a separate module for this, as per the folder and project structure
