### ISSUE TITLE
Scraping Steam for Game Description and Current Price

### ISSUE THREAD

**Issue by hard02** [Clueless-Community/scrape-up#265]
**Is your feature request related to a problem? Please describe.**
The proposed feature aims to provide a solution for retrieving important information about games from Steam like description, current game price and current user rating.

**Describe the solution you'd like**
 It will help to scrape steam's game page data like descriptions, current prices and user review which may further be used for archival purposes. This data then can be used to compare prices or to train a predictive model to guess the prices in the nearby future. With the current rating, the user will be able to have a rating system helping to provide insight or to create a ranking system by using our library. 

**Additional context**
Can be provided upon request.

I request @nikhil25803 to kindly assign this issue to me under GSSoC'23.
Cheerios

**Comment by nikhil25803** [comment]
Great idea @hard02, but do mention some website or platform from where you will scrape the data.

**Comment by hard02** [comment]
Apologies. Here's the website which I'm thinking to scrape:
[https://store.steampowered.com/](steam). 

@nikhil25803

**Comment by nikhil25803** [comment]
Hey, one similar issue #290 has been created, you can add a comment there and can collaborate and work on different methods. Closing this one for now, add a comment there if you want to proceed.
