### ISSUE TITLE
Coursera Class | Add docstring and update the documentation for it.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#267]
**Note**
+ Reference line of issue - https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/coursera/courses.py#L9
+ Add the `Coursera` class and its methods in the `documentation.md` file.
+ Add docstring to the class and each of its methods(except the private ones)
>> A perfect docstring looks like
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/579f0c0c-863d-4714-ac9c-c7304f6cf205)

**Comment by karthikbhandary2** [comment]
can I work on this?

**Comment by nikhil25803** [comment]
Go ahead @karthikbhandary2
