### ISSUE TITLE
Finance Class | Functions of the defined class is not working.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#268]
**Note**
+ The `get_latest_price` method is not working properly. Need someone to fix this issue.
+ https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/finance/nse.py#L63

**Comment by karthikbhandary2** [comment]
Can I work on this?

**Comment by nikhil25803** [comment]
Go ahead @karthikbhandary2
