### ISSUE TITLE
Finance Class | Add docstring and update documentation

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#269]
**Note**
+Reference line of the issue - https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/finance/stock_price.py#L46
+ Add docstring to the class and each of its methods(except the private ones)
>> A perfect docstring looks like
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/579f0c0c-863d-4714-ac9c-c7304f6cf205)
+ Also update the `documentation.md` file.

**Comment by Shreya111111** [comment]
@nikhil25803  plz assign this issue to me
I am familiar with the documentation and markdown

**Comment by nikhil25803** [comment]
Hey @Shreya111111, @brohithkr has already started working on this issue. 
Add a comment in issue #270 -- I'll assign you there.
