### ISSUE TITLE
GitHub Class - Add docstring to each method of all the classes

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#270]
+Reference line of the issue - https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/github/issue.py#L11
+ Add docstring to the class and each of its methods(except the private ones)
+ **A perfect docstring looks like**
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/579f0c0c-863d-4714-ac9c-c7304f6cf205)

**Comment by karthikbhandary2** [comment]
can I work on this?

**Comment by nikhil25803** [comment]
Already assigned you two issues, make a PR for them at first :))

**Comment by Shreya111111** [comment]
@nikhil25803 plz assign this issue

**Comment by Shreya111111** [comment]
@nikhil25803 kindly assign this issue to me

**Comment by nikhil25803** [comment]
Sure @Shreya111111 go ahead, make sure you add docstring to all the classes :))
