### ISSUE TITLE
Instagram Class - Methods not working 

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#271]
+ Reference line of the issue
https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/instagram/users.py#L25
+ Method to fetch number of followers and number of posts are not working.

**Comment by karthikbhandary2** [comment]
I would like to work on this

**Comment by nikhil25803** [comment]
Go ahead @karthikbhandary2

**Comment by karthikbhandary2** [comment]
You can close this @nikhil25803
