### ISSUE TITLE
Hacker News | Add docstring

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#272]
+ Add docstring to the class and each of its methods(except the private ones)
+ **A perfect docstring looks like**
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/579f0c0c-863d-4714-ac9c-c7304f6cf205)

+ Reference line
https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/hacker_news/articles.py#L14

**Comment by prady0t** [comment]
Hello @nikhil25803 please assign me this issue. I would love to work on this.

**Comment by Shreya111111** [comment]
hello @nikhil25803  plz assign this issue to me as I am familiar with documentation
