### ISSUE TITLE
Instagram Class | Docstring to the posts method

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#273]
+ The method to fetch the number of posts does not have docstring, please add it.https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/instagram/users.py#L81

+ Add docstring to the class and each of its methods(except the private ones)
+ **A perfect docstring looks like**
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/579f0c0c-863d-4714-ac9c-c7304f6cf205)

**Comment by Tomfernandezp** [comment]
Hi, i would like to contribute.

**Comment by karthikbhandary2** [comment]
I would like to work on this!

**Comment by nikhil25803** [comment]
Go ahead @Tomfernandezp

**Comment by bhavya1857** [comment]
why is this issue still open?

**Comment by nikhil25803** [comment]
Because it wasn't mentioned in the PR hence doesn't close automatically.
