### ISSUE TITLE
Internshala Class | Add dosctring

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#275]
+ Add docstring to the class and each of its methods(except the private ones)
+ **A perfect docstring looks like**
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/579f0c0c-863d-4714-ac9c-c7304f6cf205)

+ Reference 
https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/internshala/internships.py#L24

**Comment by Abhinavcode13** [comment]
Please can you assign me this issue @nikhil25803

**Comment by Abhinavcode13** [comment]
I have implemented this already ;)

**Comment by nikhil25803** [comment]
Go ahead @Abhinavcode13
