### ISSUE TITLE
Kooapp Class | Add docstring

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#276]
+ Add docstring to the class and each of its methods(except the private ones)
+ **A perfect docstring looks like**
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/579f0c0c-863d-4714-ac9c-c7304f6cf205)

+ Reference
https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/kooapp/users.py#L63

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.

**Comment by nikhil25803** [comment]
Go ahead @tarunsamanta2k20

**Comment by Abhinavcode13** [comment]
@nikhil25803 can i take up this issue as there is no response

**Comment by Abhinavcode13** [comment]
?? @nikhil25803
