### ISSUE TITLE
Medium Class | Add docstring 

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#277]
+ Add docstring to the class and each of its methods(except the private ones)
+ **A perfect docstring looks like**
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/579f0c0c-863d-4714-ac9c-c7304f6cf205)

+ Reference
https://github.com/Clueless-Community/scrape-up/blob/c7ac4c8a842b9e2fb43f25257cd3902a0a8625f8/src/scrape_up/medium/publication.py#L14

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.

**Comment by nikhil25803** [comment]
Go ahead @tarunsamanta2k20

**Comment by Abhinavcode13** [comment]
@nikhil25803 can i take up this issue as there is no response

**Comment by Abhinavcode13** [comment]
@nikhil25803 ??

**Comment by nikhil25803** [comment]
Wait for a few more times @Abhinavcode13 | Let @tarunsamanta2k20 take his time. If there's no response within the next 2 days, I'll re-assign it to you.

**Comment by karthikbhandary2** [comment]
Hey if it is not done I can do this!

**Comment by nikhil25803** [comment]
Sure @karthikbhandary2 | Go ahead
