### ISSUE TITLE
Flipcart Scrapper - Web App with Simple UI for Product Reviews

### ISSUE THREAD

**Issue by affaannn** [Clueless-Community/scrape-up#285]
I would like to suggest a new feature for the web scraping project. It would be great to have a web app with a simple user interface where users can enter the name of a product, and the application will fetch reviews from the Flipkart website using web scraping techniques. 
Additionally, it would be helpful if Flask is used to expose APIs for accessing the scraped data and showing it on web app.

I also welcome contributions from frontend developers to help create a user-friendly and visually appealing UI for this web scraping application.

**Comment by nikhil25803** [comment]
This doesn't match the goal of this project :))
