### ISSUE TITLE
Yahoo Finance Scrapper

### ISSUE THREAD

**Issue by surajdeotiwari** [Clueless-Community/scrape-up#287]
**Is your feature request related to a problem? Please describe.**
It is request regarding yahoo finance web scrapper.
Basically it would find the stock related data from the yahoo finance site and then it would get the content and return it in a dataframe format through that any analyst can get the data and do the analysis over it.

**Describe the solution you'd like**
Making a Yahoo finance class which would include methods.

**Additional context**
I have created #280 PR Please have look at them you will get to know about the context.
I personally feel More method needs to be created for all other pages.

**Comment by nikhil25803** [comment]
We do not need this for now, closing the issue and PR for the same.
