### ISSUE TITLE
Adding NASDAQ and BSE scraping support to Finance Module

### ISSUE THREAD

**Issue by brohithkr** [Clueless-Community/scrape-up#293]
### Description
I would like to create a nasdaq.py and bse.py and add ```NASDAQ``` and ```BSE``` classes to the respective files which would handle requests from nasdaq and bse websites. Then the stock_price.py would import these and ```StockPrice``` class can support scraping from these indexes as well.

### Example Usage
The usage would remain same as ```NASDAQ``` and ```BSE``` classes are being imported by ```StockPrice``` 

Please assign this issue to me under GSSoC'23

**Comment by nikhil25803** [comment]
Great idea @brohithkr | Go  ahead.
