### ISSUE TITLE
SCRAPING EMAIL ADDRESS FROM WEBSITES

### ISSUE THREAD

**Issue by kharshita590** [Clueless-Community/scrape-up#294]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nikhil25803** [comment]
Go ahead @kharshita590 
**Note**
+ Create a separate module for this, as per the folder and project structure

**Comment by PayalPadmalyaPrusty** [comment]
@nikhil25803 I want to contribute.Please assign me this issue

**Comment by nikhil25803** [comment]
Go ahead @PayalPadmalyaPrusty
