### ISSUE TITLE
Pinned Repository

### ISSUE THREAD

**Issue by ayushanand308** [Clueless-Community/scrape-up#3]
We can add a method to retrieve the list of pinned repositories for a given user.

**Comment by nikhil25803** [comment]
Sounds good, go ahead @ayushanand308.

**Comment by ayushanand308** [comment]
@nikhil25803 Can you add a difficulty level so that I can get a deadline.

**Comment by ayushanand308** [comment]
I have 2-3 days for this right?

**Comment by nikhil25803** [comment]
> I have 2-3 days for this right?

Yes.
