### ISSUE TITLE
Fix Text in Readme

### ISSUE THREAD

**Issue by Sriparno08** [Clueless-Community/scrape-up#301]
### Description

In the below section:

![Screenshot 2023-06-10 184557](https://github.com/Clueless-Community/scrape-up/assets/89148144/3b7aef4d-282d-4566-854d-cead66af49ba)

This line:

> It enables you to gather data programming

can be changed to:

> It enables you to gather data through programming.

I would like to work on this as part of GSSoC'23.

**Comment by nikhil25803** [comment]
Go ahead @Sriparno08
