### ISSUE TITLE
Add the black linter workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [Clueless-Community/scrape-up#304]
**Is your feature request related to a problem? Please describe.**
As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users.

**Describe the solution you'd like**
An excellent way to do this is by automatic linting checks using GitHub actions. As such I would like to add the black linter workflow to ensure a proper and uniform linting of the codebase.

I would like to work on this project as a part of GSSoC 23.

**Comment by nikhil25803** [comment]
We do have plans for this @metabiswadeep  |  But to not make complex for users, we are not looking forward to add this one.
