### ISSUE TITLE
Update Issue Template & Add issue forms respectively

### ISSUE THREAD

**Issue by dakshsinghrathore** [Clueless-Community/scrape-up#305]
## Proposed Method: [Method Name]
Will add yaml code for every issue form so that contributor can easily fill in the issue with much more ease.

### Description
Currently, the issue template for this repo seems to be basic also it is less visually appealing.👇

![Screenshot 2023-06-11 at 01-40-33 New Issue · Clueless-Community_scrape-up](https://github.com/Clueless-Community/scrape-up/assets/115932772/ab4d6ac8-61fe-4f91-8683-209ffc3b1393)

***Will add some more options under the issue tab along with it, will also add issue form to the same, just like this.👇***

![Screenshot 2023-06-11 at 01-12-48 New Issue · dakshsinghrathore_htmltut](https://github.com/Clueless-Community/scrape-up/assets/115932772/b09a0219-73bb-4de2-9dee-b27b3522dfb1)

![Screenshot 2023-06-11 at 01-15-06 New Issue · dakshsinghrathore_htmltut](https://github.com/Clueless-Community/scrape-up/assets/115932772/889edf9e-ee04-49a1-afdd-132a3ec61aae)

### Example Usage
[Include an example of how the proposed method can be used within the class.]

**Comment by nikhil25803** [comment]
Go ahead @dakshsinghrathore | Can you add the same as the PR template respectively? 
If yes, go ahead. Else add for the issues only.

**Comment by dakshsinghrathore** [comment]
Thanks for assigning @nikhil25803 . Currently am unaware of such a form for Pull Request Template, but yes if I came to know about it will surely raise an issue for the same.
