### ISSUE TITLE
remove all the Grammatical error and spelling errors in entire code

### ISSUE THREAD

**Issue by gulshanjakhon** [Clueless-Community/scrape-up#309]
## Proposed Method: Documentation
I want to remove all the Grammatical error and spelling errors in the entire code
### Description

**Some spelling and grammar mistakes in the readme, Documentation, and Contribution files.**

### Example Usage
# [Include an example of how the proposed method can be used within the class.]

Please assign this issue to me under the gssoc23 label.

**Thank you
GSSOC23 Contributor**

**Comment by nikhil25803** [comment]
Go ahead @gulshanjakhon | `documentation. md` as well as the `contribution. md` has already been fixed. Check in the codebase(docstring to be precise), and fix the typo, if any.

**Comment by gulshanjakhon** [comment]
Hey, please check Resolve typo error #324
