### ISSUE TITLE
Scraping information from Coursera

### ISSUE THREAD

**Issue by S-anonD** [Clueless-Community/scrape-up#315]
**Is your feature request related to a problem? Please describe.**

The suggested feature can be implemented:
1. To find a course at a particular university/organization with ease

2. To find the course of a particular price

3. To find the course or teacher of a particular rating

**Additional context**
Can be provided upon request.

I request @nikhil25803 to kindly assign this issue to me under GSSoC'23.

https://www.coursera.org/

**Comment by nikhil25803** [comment]
Hey @S-anonD | We do already have the Coursera class
https://github.com/Clueless-Community/scrape-up/tree/main/src/scrape_up/coursera
