### ISSUE TITLE
Convert text files to sheets

### ISSUE THREAD

**Issue by Tisha6661** [Clueless-Community/scrape-up#316]
### Description
I would like to add a feature of adding text data automatically to google sheets in this projects, for tabular data.

### Example Usage
It can make it easy to handle the tabular data store din text files, or copied for scraping from sites.

It would work using  Goggle API keys and it would be a good extension to the project, could u please assign me this task.

**Comment by nikhil25803** [comment]
This doesn't match the goal and motive of the project.
