### ISSUE TITLE
Scraping Kindle Website of Amazon

### ISSUE THREAD

**Issue by Tisha6661** [Clueless-Community/scrape-up#317]
## Proposed Method: 
Web scraping on the official website of amazon books.

### Description
As Amazon Kindle is one of the most famous website which is most useful for book nerds, so in this issue I will be dealing with scraping the data on Kindle.

## To what class it belongs?: [Class Name]
Github 

### Example Usage
It would give a great deal of information about the working of the site, also it would tell about the hell lot of books on kindle, with their reviews.

Please assign me this issue, as an active member of GSSOC 23, i would love to work on it.

**Comment by nikhil25803** [comment]
Go ahead @Tisha6661 
**Note**
+ Create a separate module for this, as per the folder and project structure

**Comment by Tisha6661** [comment]
@nikhil25803 pull request has been successfully created, please verify it.

**Comment by Tisha6661** [comment]
Please verify it @nikhil25803 , and inform if any other update is required.
