### ISSUE TITLE
Wikipedia Scraping

### ISSUE THREAD

**Issue by swetha3456** [Clueless-Community/scrape-up#319]
**Is your feature request related to a problem? Please describe.**
Difficulty in reading through entire articles to find information.

**Describe the solution you'd like**
When an article's title is entered, prints list of subheadings within the article. When the user chooses a subheading, prints content. Also lists keywords in the article and under each subheading.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by swetha3456** [comment]
@nikhil25803 I'd like to work on this. Please assign this issue to me. 

Thanks, 
Swetha (GSSoC '23 Contributor)

**Comment by nikhil25803** [comment]
We already do have a dedicated class @swetha3456 
https://github.com/Clueless-Community/scrape-up/tree/main/src/scrape_up/wikipedia
