### ISSUE TITLE
Scrapping information from Netflix

### ISSUE THREAD

**Issue by S-anonD** [Clueless-Community/scrape-up#320]
**Is your feature request related to a problem? Please describe.**
The suggested feature will implement:
1. To provide details about the movie or the series, such as the plot, year of release, cast, directors, etc.
2. To categorize movies and series based on ratings and warnings.
3. To view more information such as movies starring actors and actresses of viewed movies or series, and more movies or series made by the same directors.

**Additional context**
Can be provided upon request.

I request @nikhil25803 to kindly assign this issue to me under GSSoC'23

https://www.netflix.com/in/

**Comment by nikhil25803** [comment]
Go ahead @S-anonD :))
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch all the trending movies.

**Comment by S-anonD** [comment]
Alright, and thank you, Sir.
