### ISSUE TITLE
Adding Cryptocurrency prices scraping support to finance module

### ISSUE THREAD

**Issue by brohithkr** [Clueless-Community/scrape-up#327]
### Describe the feature

I want to add cyptocurrency scraping support to finance module. This would enable `StockPrice` class to scrape latest price and historical price of all cryptocurrencies from [crypto.com](https://crypto.com). I would create a crypto.py file and `CRYPTO` class then intergrate `CRYPTO` class into `StockPrice` class

### Add ScreenShots

Adding this feature would enable add such functionality to `StockPrice` class:
```py
solana = StockPrice("solana","crypto")
latest_price = solana.get_latest_price()
historical_price = solana.get_historical_data("05-06-2023","10-06-2023")
```
(would surely add screenshots after completing the feature)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by brohithkr** [comment]
The `BSE` class is not giving results when multiple requests are made. I would also try to fix this problem under this issue.

**Comment by nikhil25803** [comment]
Go ahead @brohithkr 
**Note**
+ Create a separate module for this, as per the folder and project structure

**Comment by brohithkr** [comment]
@nikhil25803 I'm thinking to add this feature to finance module. So I am thinking to add crypto.py inside finance module and you can use `CRYPTO` class by putting stock_index parameter of `StockPrice` class as "crypto" instead of "nse" or "nasdaq". What do you think about this ?
