### ISSUE TITLE
Booking.com Scraping

### ISSUE THREAD

**Issue by koushik395** [Clueless-Community/scrape-up#329]
### Describe the feature

Booking.com is a website where we can book hotels for our holiday destination. We can scrape the data from the website by extracting the hotel name , price, no. of rooms , facilities of the hotel in a particular journey date and can extract it to a excel sheet.

### Add ScreenShots

By extracting the data of the hotels for our holiday destination we can get a clear picture of information regarding the hotels that is best suited for our holiday destination

I request @nikhil25803 to please assign this to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @koushik395 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch all the hotels of an entered location
