### ISSUE TITLE
Get the main tech stack used for each repository

### ISSUE THREAD

**Issue by PalaVenkiReddy** [Clueless-Community/scrape-up#33]
### Description
with the help of get_techstack_repo(), one can easily know main tech stack used for each repository of given user, in which it helps to pick repositories to contribute based on Tech Stack we are interested in.

### Example Usage

```python
from scrape_up import github
user =  github.Users(username="PalaVenkiReddy")

# Call the techstack function
print(user.get_techstack_repo())

# Output - {repo_name : tech_stack_used , . . . . . . . }
```

**Comment by nikhil25803** [comment]
Hey @PalaVenkiReddy, we will include this in the `Repo` class, not in the users class.
