### ISSUE TITLE
Scraping Internshala platform

### ISSUE THREAD

**Issue by hima-v** [Clueless-Community/scrape-up#331]
### Describe the feature

I plan to provide the following features:
1. Allow user to get data about the internship for the specific skills they have.
2. Save details about the company, when the job was posted, pay amount, type of internship, location, etc
3. Generate the data and store it in a File
4. Automate it to run as per custom time. Eg: every hour or so.

### Add ScreenShots

_I can update and modify as per the requirements. This is the basic template I am aiming for:_

![image](https://github.com/Clueless-Community/scrape-up/assets/79623293/7de61567-6cff-460b-8157-cb2f55ecf314)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @hima-v 
**Note**
+ We already do have a class for the Internshala, just add your method to the existing class.
