### ISSUE TITLE
Bookmyshow.com Scrapping

### ISSUE THREAD

**Issue by Charishma-Bailapudi** [Clueless-Community/scrape-up#332]
### Describe the feature

Bookingmyshow.com is a website where we can book movie tickets . We can scrape the data from the website by extracting the movie details, showtimes and venues,ticket availability,Reviews and Ratings,Event Details and offers  in a particular date and can extract it to a excel sheet.

### Add ScreenShots

By scraping this information, we can gather details about ongoing offers and any associated terms and conditions.

I request @nikhil25803 to please assign this to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Charishma-Bailapudi 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the movie details and availability.

All the best :))

**Comment by nikhil25803** [comment]
Hey @Charishma-Bailapudi, any update?
