### ISSUE TITLE
Wynk Music Scrapping

### ISSUE THREAD

**Issue by HarshAggarwal1** [Clueless-Community/scrape-up#336]
### Describe the feature

Wynk music is a large music platform in India. Millions of people use it on daily basis.

### Add ScreenShots

By doing data scrapping from Wynk Music we can show trending, top rated genres, music, albums etc. on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @HarshAggarwal1 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch an artist's music. 
+ Also try to fetch the links of the music

All the best :))
