### ISSUE TITLE
Scrape GSOC Project information

### ISSUE THREAD

**Issue by hima-v** [Clueless-Community/scrape-up#337]
### Describe the feature

Going through GSOC projects can be overwhelming because of large number of organizations and the specific technology requirements. By scraping GSOC website, the following information can be used:
1. Name of the organization
2. The tech stack specification
3. Topics regarding the project
4. Past project information

### Add ScreenShots

Following information can be generated about the organization:

![image](https://github.com/Clueless-Community/scrape-up/assets/79623293/76e40a1b-f6c4-4199-aa1d-a8a7b6267cbe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey, it is an event-specific idea. We are looking for more generalization.
