### ISSUE TITLE
Feat: Adding a LinkedIn Profile Scrapper

### ISSUE THREAD

**Issue by Mahitej28** [Clueless-Community/scrape-up#339]
### Describe the feature

Hello, I am Mahima Churi a proud contributor at GSSoc ' 23.

I would like to work on this issue by adding a LinkedIn Profile Scrapper.

The LinkedIn Profile Scraper is a web scraping project designed to extract information from LinkedIn user profiles. It allows us to gather data such as names, job titles, companies, education details, skills, and more from public LinkedIn profiles.

If you think it's legit then do assign me this issue under GSSoc ' 23 with a level of PR as well

### Add ScreenShots

None

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by abanindra3** [comment]
HI, I am Abanindra, and I would like to  contribute my code in this issue.

**Comment by nikhil25803** [comment]
Go ahead @Mahitej28 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to scrape the bio of the user


@abanindra3 | You can collaborate with @Mahitej28 and can work on another method, like scraping followers and following.
But do create a separate PR.

**Comment by Mahitej28** [comment]
Sure @nikhil25803
