### ISSUE TITLE
Improve contribution.md file.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#34]
As the folder structure of the project is now changed, you have to make minor changes in the `contribution. md` file.

**Comment by Viveksati5143** [comment]
please assign me this issue.

**Comment by nikhil25803** [comment]
Assigning it to you @Viveksati5143.

**Comment by neokd** [comment]
Hey I would like to work on this issue under JWOC

**Comment by nikhil25803** [comment]
This needs small changes, that's why assigning you 2 issues. Make a PR for it first.

**Comment by neokd** [comment]
Sure
