### ISSUE TITLE
Adding more features to LeetCode Scraper module

### ISSUE THREAD

**Issue by akshaypatel67** [Clueless-Community/scrape-up#341]
### Describe the feature

I would like to add some new features to the LeetCode module such as:

**User related features**
For a given username, in addition to rating and rank, add methods to scrape information such as
- Total no. of problems solved
- Total no. of easy, medium, and hard problems solved
- GitHub and LinkedIn profile links if available
- Community stats of the user

**Coding Problems related features**
- Get top questions for filters like difficulty level, tags, search keywords
- Get upcoming contest details
- Get problem details of daily challenge

### Add ScreenShots

I request @nikhil25803 to please assign this issue to me under GSSoC'23.

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @akshaypatel67 
**Note**
+ Go ahead, add your methods and make a PR.

**Comment by akshaypatel67** [comment]
Thanks @nikhil25803. Can I create two separate classes in separate python files for users and coding problems as per the current project structure?

**Comment by nikhil25803** [comment]
No, a class has already been created to scrape ratings and rankings try adding your method to that class only.
