### ISSUE TITLE
DOC: Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Clueless-Community/scrape-up#344]
### What's wrong with the existing documentation

*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@nikhil25803 please assign me this issue under gssoc'23.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @Anshika-Jain02 | Great idea, but this might cause version conflict in the package, not want to implement it as of now.
