### ISSUE TITLE
DOC: Adding auto_comment.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Clueless-Community/scrape-up#345]
### What's wrong with the existing documentation

*We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance*

@nikhil25803 Please assign me this issue under gssoc'23

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Really not looking for that many bots  action for now, though I want some automation on every PR merge which I also discussed in issue #251 | 
What I want is that on every PR merged, I want the bot to send this message
```md
Great work  @{user_name} !!
Do not forget to
+ Share your contribution on socials(Twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅
```

Do let me know if that is possible, I will assign you the issue.

**Comment by Nishitbaria** [comment]
Hey @nikhil25803 Please Review my PR I have Alreedy Created This PR: https://github.com/Clueless-Community/scrape-up/pull/346
