### ISSUE TITLE
Scraping goodreads platform for books information

### ISSUE THREAD

**Issue by brohithkr** [Clueless-Community/scrape-up#347]
## Proposed Idea
Scraping [goodreads](https://www.goodreads.com) website for book data.

## Description
Many times I want to scrape data about a particular years [goodreads](https://www.goodreads.com)  choice winners or scrape data of top searches based on a particular keyword. I would like to add module that would scrape desired data from [goodreads](https://www.goodreads.com) platform based on book rating or author name.

### Add ScreenShots

You can scrape data about a particular book or scrape data about a particular book or scrape goodreads choice winners or particular year.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by brohithkr** [comment]
@nikhil25803 Please assign this issue to me under GSSoC'23.

**Comment by nikhil25803** [comment]
Go ahead @brohithkr 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the book of a specific writer.
