### ISSUE TITLE
Feat: Scrapping freepik website for the links of Graphical assets

### ISSUE THREAD

**Issue by Garv-it2002** [Clueless-Community/scrape-up#349]
### Describe the feature

Searching graphical assets like vector images or images of some kind requires a lot of scrolling and knowing if it is royalty free to use or a license is necessary. I would like to add a module that will extract the data based on number of downloads and popularity, also providing the information of license and copyright.

### Add ScreenShots

Data of a image of particular kind can be scrapped based on number of downloads along with its license info to let the user know all the steps necessary before using that asset

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Garv-it2002 
**Note**
+ Create a separate module for this, as per the folder and project structure

**Comment by Garv-it2002** [comment]
> Go ahead @Garv-it2002 **Note**
> 
> * Create a separate module for this, as per the folder and project structure

Sure, thanks!
