### ISSUE TITLE
Feat: Add streamlit frontend for user GUI

### ISSUE THREAD

**Issue by ankita0512ghosh** [Clueless-Community/scrape-up#357]
### Describe the feature

Adding streamlit frontend for users to have an interactive GUI 

### Add ScreenShots

No Screenshots yet

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @ankita0512ghosh | We are not looking to add this now.
