### ISSUE TITLE
Feat: Adding a google maps scrapper

### ISSUE THREAD

**Issue by okaditya84** [Clueless-Community/scrape-up#358]
### Describe the feature

This feature will be able to extract name, location, coordinates, phone num etc from google maps.

### Add ScreenShots

<img width="946" alt="Screenshot 2023-06-20 140555" src="https://github.com/Clueless-Community/scrape-up/assets/97025644/7c6cc6b8-67eb-4ac0-987e-884634008188">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @okaditya84 
**Note**
+ Create a separate module for this, as per the folder and project structure
