### ISSUE TITLE
Create test files.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#36]
As the methods of the `Users` class is done, I need someone to make a test file, which can test if all the methods as working correctly or not. 

+ Create a `test` folder in `/src`
+ Within that directory, create a `github_test.py`. 
+ Include all your script there, testing the methods that have been created till now.

**Comment by Viveksati5143** [comment]
please assign me this issue

**Comment by nikhil25803** [comment]
One issue at a time @Viveksati5143.

**Comment by Viveksati5143** [comment]
Yes, I checked I got assigned to that different issue. If I complete it within an hour will i get assigned to it @nikhil25803 ?

**Comment by nikhil25803** [comment]
> Yes, I checked I got assigned to that different issue. If I complete it within an hour will i get assigned to it @nikhil25803 ?

Yes

**Comment by Viveksati5143** [comment]
On it sir

**Comment by Laxmankohar** [comment]
Hey @nikhil25803 , I want to work on this issue under JWOC. Please assign it to me.

**Comment by nikhil25803** [comment]
Go ahead @Laxmankohar  :))

**Comment by nikhil25803** [comment]
Any update @Laxmankohar ?

**Comment by Laxmankohar** [comment]
in progress

> Any update @Laxmankohar ?

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/220253096-24c7c532-2b08-4352-8349-695e9d8da2e3.png)

**Comment by nikhil25803** [comment]
You have to dynamically add the username in the `self.assert()` I guess. Why it is `testuser` there?

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/220312202-4f986b21-ed55-459c-b78f-379fbfa7200a.png)

**Comment by nikhil25803** [comment]
What problem are you facing?

**Comment by Laxmankohar** [comment]
> What problem are you facing?

is it ok or not?  i have pass the username dynamically.

**Comment by nikhil25803** [comment]
Push the changes for now, I will review and request changes accordingly.
