### ISSUE TITLE
Feat: Scrapping up GSSOC'23  Projects

### ISSUE THREAD

**Issue by dev-32** [Clueless-Community/scrape-up#360]
### Describe the feature

I want to add the scrapping code to scrap **gssoc'23  projects** consisting of : 
1) Project Name
2) Authors Name

Assign me (@dev-32) to add this feature.
This feature will also include the conversion of whole data into a **CSV file**.

### Add ScreenShots

<img width="350" alt="Screenshot 2023-06-21 at 1 29 02 AM" src="https://github.com/Clueless-Community/scrape-up/assets/99115141/353e95b8-ca7f-41a2-8bd1-a924fd16ce48">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @dev-32 | We are not looking to add this in our project.
