### ISSUE TITLE
Feat: Scrape Flipkart Website

### ISSUE THREAD

**Issue by Tisha6661** [Clueless-Community/scrape-up#361]
### Describe the feature

To scrape the flipkart website for reaching out to products in an easier way.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/98682478/53e1da45-b184-4717-b580-50c562212484)

flipkart is a famous shopping website, scraping would help to analysis its products easily and in a better way.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Tisha6661 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the electronics items.

**Comment by Tisha6661** [comment]
@nikhil25803 I have created a pull request for this task, please verify it and merge it.

**Comment by Tisha6661** [comment]
@nikhil25803 , I didn't not get points for this project in the Leaderboard, could you please add labels so that I could get points. Please check into it.

**Comment by nikhil25803** [comment]
Sorry @Tisha6661 |My bad, added the labels in the PR/

**Comment by Tisha6661** [comment]
Thank you so much!!
