### ISSUE TITLE
Feat: Add the prettier linter workflow

### ISSUE THREAD

**Issue by metabiswadeep** [Clueless-Community/scrape-up#366]
### Describe the feature

As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions. So I would like to add the prettier linter to ensure proper and uniform linting of the codebase.

I would like to work on this as a part of GSSoC 23.

### Add ScreenShots

![Create linting yml · metabiswadeep_scrape-up@40888c4 - Google Chrome 21-06-2023 22_12_47](https://github.com/Clueless-Community/scrape-up/assets/98874428/804f4194-99f4-484d-9316-e4c8abba6744)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @metabiswadeep
