### ISSUE TITLE
Feat: Add a workflow to close old issues

### ISSUE THREAD

**Issue by abhinav-m22** [Clueless-Community/scrape-up#367]
### Describe the feature

An automated implementation titled the Close Old Issue Bot is intended to quickly locate inactive or resolved issues and close them.

By removing clutter and ensuring active focus on important tasks, it increases the effectiveness of issue management.

The Github actions workflow will be created in the ./github/workflows directory in order to automate the task of closing the old/inactive issues.

The workflow tracks the status of open issues and flags those that haven't been updated in a while.

Promotes a tidy and organized issue tracker by closing out-of-date or resolved issues in accordance with specified criteria.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @abhinav-m22 | We do not need this now
