### ISSUE TITLE
scraping of flipkart data 

### ISSUE THREAD

**Issue by Sushilverma002** [Clueless-Community/scrape-up#375]
### Describe the feature

the scraping data of the mobile phone who came under 50k.
As we know that the mobile phone is very essential thing in day to day like so the data must help to know which phone came with best prize as well as best features.

i will be proving you with :
1. the steps of scarping the data from flipkart in .txt format. 
2. the data in the format of CSV.
3. the code in .py format.

data consist of:-
1. the prizes of the mobile phones.
2. the description of the mobile phones.
3. the most important the REVIEW about the particular phone.
4. the name of mobile phone with the modal name.

** i have checked no project is similar to mine.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/114687502/9ed1cf1f-92fc-4edd-8deb-07e60bea89df)
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @Sushilverma002  | A similar issue is raised #361, you can collab with her(the assigned user) and can work on the same class but different methods.

I

**Comment by Sushilverma002** [comment]
Okay i will.😌
