### ISSUE TITLE
Feat: bookmyshow scraper

### ISSUE THREAD

**Issue by barkhaaroraa** [Clueless-Community/scrape-up#376]
### Describe the feature

this feature would allow the user to see their favourite movie's showtimes in their nearest cinema hall

### Add ScreenShots

<img width="895" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/115429121/a1c46217-a0df-4f29-92f0-89f30ef99bad">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @barkhaaroraa 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the movie details and availability(or method of your choice)
