### ISSUE TITLE
WebScraping TimesJobs for getting to know about Jobs

### ISSUE THREAD

**Issue by tanishkunigiri** [Clueless-Community/scrape-up#379]
### Describe the feature

This feature helps get the job applications of a particular domain. Ex: Python: I will get all the companies that are actively recruiting people for this role. It will be consisting of the Company name, Location of the company, Experience required, how many days before the job was posted and the link for the application to that particular job. 

### Add ScreenShots

![GSSoC](https://github.com/Clueless-Community/scrape-up/assets/106328619/1b713eee-89da-4127-840f-cfea17f3b4ea)
This is how the output looks. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @tanishkunigiri 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the movie details and availability.

All the best 👨‍💻
