### ISSUE TITLE
Stars count of a repository.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#38]
## Proposed Method:
`.stars_count()`

### Description
Create a method to get the number of stars, a repository has.

## To what class it belongs?:
`Repository`

**Comment by neokd** [comment]
Kindly assign me the issue under JWOC

**Comment by nikhil25803** [comment]
Go ahead @neokd  :))

**Comment by neokd** [comment]
thanks ❤️
