### ISSUE TITLE
Feat: [GSSoC'23] GeeksforGeeks portal scraping

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#380]
### Describe the feature

GeeksforGeeks:

-> Scrap trending now section of GFG

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/a5a11662-6a49-4143-855a-42ef504630f2)
I would like to scrap this page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @tanishkunigiri 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the courses available on GFG.

All the best 👨‍💻

**Comment by Juhibhojani** [comment]
Thank you!
