### ISSUE TITLE
Feat: Scrape eazydiner website to scrape restaurant data

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#381]
### Describe the feature

To scrape the [eazydiner](https://www.eazydiner.com/) website and obtain valuable information such as restaurant names, addresses, contact details, ratings, and reviews, etc.

### Add ScreenShots

![eazyDiner](https://github.com/Clueless-Community/scrape-up/assets/42113027/d51a0555-3e48-4598-aef7-a937c772b7d0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the the restaurants of a city mentioned by the user

All the best 👨‍💻

**Comment by Mihan786Chistie** [comment]
> Go ahead @Mihan786Chistie 
> **Note**
> + Create a separate module for this, as per the folder and project structure
> + Work on one method at first, like a method to fetch the the restaurants of a city mentioned by the user
> 
> All the best 👨‍💻

Thanks for assigning
