### ISSUE TITLE
Feat: Adding a video demo inside documentation

### ISSUE THREAD

**Issue by Rancho2002** [Clueless-Community/scrape-up#385]
### Describe the feature

The documentation is well written and organized. But it seems to be incomplete somehow without a video demo. Pls, assign me this issue so that I can quickly fix this thing and make the documentation more efficient and user-friendly.

### Add ScreenShots

Adding Video demo at the end of this page
![image](https://github.com/Clueless-Community/scrape-up/assets/92109154/85177f71-61ca-49cc-addc-ab6a5387af41)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by Rancho2002** [comment]
pls assign this @nikhil25803

**Comment by nikhil25803** [comment]
Hey @Rancho2002 | We do not need this for now
