### ISSUE TITLE
Feat:Add web scraping script for boat-lifestyle.com

### ISSUE THREAD

**Issue by Nishitbaria** [Clueless-Community/scrape-up#386]
### Describe the feature

I would like to propose adding a web scraping script for the boat-lifestyle.com website to this  project. The script allows us to scrape product information, such as product names, prices, image URLs, and ratings, from the boat-lifestyle.com website.

**Features:**
- Retrieves all products from a specific category.
- Retrieves detailed information about a specific product.
- Retrieves the image URL of a specific product.
- Retrieves the price of a specific product.
- Retrieves the rating of a specific product.
- 

**Script Details:**
The script utilizes the `requests` library to send HTTP requests and the `BeautifulSoup` library to parse the HTML response. It has been tested and provides example usage for each functionality.

**Example Usage:**
```python
# Create an instance of the BoatScraper class
boat_scraper = BoatScraper()

# Get all products from a specific category
category_num = 1
products = boat_scraper.get_all_category_products(category_num)

# Print the details of each product in the category
for product in products:
    print('Product:', product['product_name'])
    print('Price:', product['price'])
    print('Image URL:', product['image_url'])
    print('---')

# Get the details of a specific product
product_name = 'airdopes-381-masaba-edition'
product_details = boat_scraper.get_product_details(product_name)
print('Product Details:', product_details)

# Get the image URL of a specific product
image_url = boat_scraper.get_product_image(product_name)
print('Image URL:', image_url)

# Get the price of a specific product
price = boat_scraper.get_product_price(product_name)
print('Price:', price)

# Get the rating of a specific product
rating = boat_scraper.get_product_rating(product_name)
print('Rating:', rating)
```

Please review and provide your thoughts on adding this web scraping script to your project. 

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85815172/e9762828-aa8c-409b-b38c-5fde10defa77)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @Nishitbaria | We are looking to add modules that are common, in a more generalize way. Not specific to be precise.
