### ISSUE TITLE
Feat: Scrape IMDb Website

### ISSUE THREAD

**Issue by Tisha6661** [Clueless-Community/scrape-up#391]
### Describe the feature

IMDb website is famous for maintaining the movies database with all necessary information. I would like to scrape it for movies data.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/98682478/5c838591-a737-48f0-a751-16f61fda70a5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
@Tisha6661 | We already do have a class for IMDB, check [here](https://github.com/Clueless-Community/scrape-up/tree/main/src/scrape_up/imdb1).

Still you can add your method on the top of the same class, creating a new method.

**Comment by Tisha6661** [comment]
@nikhil25803 I have created a pull request regarding this issue, please verify.
