### ISSUE TITLE
Feat: Improve the Ask Ubuntu scraper for other forms of questions

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#395]
### Describe the feature

Have to improve the ask ubuntu website to get the newest question, question with high scores and the active questions.

### Add ScreenShots

![askUbuntu2](https://github.com/Clueless-Community/scrape-up/assets/42113027/163d66ac-681c-4e91-b773-193e6fa98911)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |
