### ISSUE TITLE
Feat: Sports Data scrapping from ESPN

### ISSUE THREAD

**Issue by smty2018** [Clueless-Community/scrape-up#396]
### Describe the feature

Create a scraper that fetches sports-related data such as scores, player statistics, etc from ESPN.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/74114936/503b83f6-ee2c-44e4-874d-0e82910dfd47)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @smty2018 
**Note**
+ Create a separate module for this, as per the folder and project structure
