### ISSUE TITLE
BUG:Add functionality to search for products in any category in Flipkart script and get any product details

### ISSUE THREAD

**Issue by Nishitbaria** [Clueless-Community/scrape-up#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The existing Flipkart class allows users to scrape trending TVs and bestselling books from Flipkart. However, there is a need to expand the functionality of the class to enable users to search for products in any category and retrieve the details of a particular product.

**Proposed Function:**
I suggest adding a new function called `search_products` to the `Flipkart` class. This function would accept two parameters: `category` and `product_name`. Users can specify the category of the product they are searching for and the name of the product. The function would then perform a search on Flipkart and return a list of dictionaries containing the details of the matching products.

The proposed function would have the following signature:

```python
def search_products(self, category, product_name):
```

**Return Value:**
The `search_products` function would return a list of dictionaries, where each dictionary represents a matching product. The dictionary would contain the following keys:

- `"Item_Name"`: The name of the product.
- `"Price"`: The price of the product.
- `"Rating"`: The rating of the product (if available).
- `"Specifications"`: The specifications of the product (if available).

**Example Usage:**
Here's an example of how the `search_products` function can be used:

```python
item = Flipkart()
results = item.search_products("Electronics", "Smartphone")

# Example Output
[
    {
        "Item_Name": "iPhone 12",
        "Price": "₹79,999",
        "Rating": "4.5",
        "Specifications": "6.1 inch Super Retina XDR Display, A14 Bionic Chip, 64GB ROM"
    },
    {
        "Item_Name": "Samsung Galaxy S21",
        "Price": "₹69,999",
        "Rating": "4.7",
        "Specifications": "6.2 inch Dynamic AMOLED 2X Display, Exynos 2100 Processor, 128GB ROM"
    },
    ...
]
```

**Benefits:**
The addition of the `search_products` function would enhance the flexibility of the `Flipkart` class by allowing users to search for products in any category. It would enable users to retrieve detailed information about specific products, making the class more versatile and useful for various use cases.

**Additional Notes:**
Please consider reviewing and incorporating this feature into the project. Your feedback and suggestions are welcome. Thank you for considering this enhancement .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by Nishitbaria** [comment]
@nikhil25803 Please assign me this issue

**Comment by nikhil25803** [comment]
Hey @Nishitbaria | We already do have a `Flipkart` class initiated, do add your new method on top of the existing classes only.

Go ahead :))

**Comment by Nishitbaria** [comment]
@nikhil25803  please review my pull request
