### ISSUE TITLE
Commits made in a repository.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#40]
## Proposed Method:
`.commits()`

### Description
Create a method to get the number of commits made in a repository.

## To what class it belongs?:
`Repository`

**Comment by ayushmorbar** [comment]
I would like to work on this issue, under JWoC

**Comment by nikhil25803** [comment]
Go ahead @ayushmorbar :))

**Comment by codesleep-Beperfect** [comment]
I would like to work on this issue under JWOC

**Comment by nikhil25803** [comment]
Go ahead @codesleep-Beperfect
