### ISSUE TITLE
Feat: Enhance the eazydiner scraper by retrieving restaurants for all different meal periods.

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#400]
### Describe the feature

Have to improve the eazydiner scraper by retrieving restaurants for all different meal periods such as breakfast, lunch and dinner.

### Add ScreenShots

![eazyDiner_mealTime](https://github.com/Clueless-Community/scrape-up/assets/42113027/38f97e1b-c4e8-4798-bbdc-652767366c89)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie

**Comment by Mihan786Chistie** [comment]
Thanks
