### ISSUE TITLE
Feat: Tech Crunch Website Scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#401]
### Describe the feature

To scrape the [TechCrunch](https://techcrunch.com/) website and retrieve the latest news from the website

### Add ScreenShots

![techCrunch](https://github.com/Clueless-Community/scrape-up/assets/42113027/ae91be59-3c6e-4e48-bf1c-6827a322f044)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Sounds good @Mihan786Chistie |
Can you scrape the data based on the category chosen by the user?
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/4bbf7f25-e011-4abf-b75b-3e8598450842)

Eg.
```python
news = TechCrunch(category="AI")
news.headlines()
```

This must returns all the headlines related to AI along with the link

**Comment by Mihan786Chistie** [comment]
I will try doing that 👍
