### ISSUE TITLE
BUG:Add method to get products for specific category in Amazon Web scarping script 

### ISSUE THREAD

**Issue by Nishitbaria** [Clueless-Community/scrape-up#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, the Amazon web scraping script provides methods to fetch product details, images, and customer reviews for a given product name. However, it would be beneficial to have a method that allows fetching products for a specific category.

### Proposed Solution
Add a new method, `get_products_by_category()`, to the `Product` class that takes a category parameter and retrieves a list of products for that category. This method can leverage the existing web scraping logic to fetch the necessary data.

### Example Usage
```python
product = Product()
products = product.get_products_by_category(category="electronics")
for product in products:
    print("Product Name:", product["product_name"])
    print("Product Price:", product["product_price"])
    print("Product Rating:", product["product_rating"])
    print("---")
```

### Acceptance Criteria
- The `get_products_by_category()` method is added to the `Product` class.
- The method retrieves a list of products for the specified category.
- Each product in the list includes the necessary details such as name, price, and rating.

### Additional Information
- This enhancement will provide more flexibility in retrieving products based on specific categories, allowing for more targeted web scraping tasks.

---

please assign me this issue,I will create a pull request today

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @Nishitbaria |
So ahead, but take care that we already do have a class initiated for the `Amazon` class. So add your method on the top of that class only.

**Comment by Nishitbaria** [comment]
@nikhil25803 please review my pr [#410]

**Comment by Nishitbaria** [comment]
@nikhil25803  I have created a new pull request and added a new working amazon web scraping with all methods,please review and assign me appropriate level
