### ISSUE TITLE
Feat: Google News Scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#409]
### Describe the feature

To scrape the google news website to retrieve news information from different sources.

### Add ScreenShots

![googleNews](https://github.com/Clueless-Community/scrape-up/assets/42113027/03b2dd85-bf28-40eb-8b28-518ac5b1aced)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie | Create a separate module for this and make a PR.

**Comment by Mihan786Chistie** [comment]
Thanks
