### ISSUE TITLE
Issues opened in a repository.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#41]
## Proposed Method:
`.issues_count()`

### Description
Create a method to get the number of issues opened in a repository.

## To what class it belongs?:
`Repository`

**Comment by pooranjoyb** [comment]
I would like to work on this issue under JWOC '23. Would be glad to work on this if you assign me. @nikhil25803

**Comment by nikhil25803** [comment]
Sure @pooranjoyb, go ahead :))

**Comment by pooranjoyb** [comment]
@nikhil25803 Thanks for clarification. 
Let me know when you'll be creating the `Issues Class`. I would love to contribute.
As of now I will scrap the no. of Issues & will open another PR within few hrs :)

**Comment by nikhil25803** [comment]
Sure @pooranjoyb. Will update in the discord channel of scrape-up.
