### ISSUE TITLE
Feat: TechCrunch Search Scrapper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#418]
### Describe the feature

To scrape the news from TechCrunch search website

### Add ScreenShots

![techCrunchSearch](https://github.com/Clueless-Community/scrape-up/assets/42113027/da8c94a3-addc-42f4-92ec-7d5da45cc94e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie | Add a new method corresponding to this.

**Comment by Mihan786Chistie** [comment]
Thanks @nikhil25803
