### ISSUE TITLE
Feat: Youtube Channel Scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#425]
### Describe the feature

To scrape the youtube website for users channel info.

### Add ScreenShots

![gitHub](https://github.com/Clueless-Community/scrape-up/assets/42113027/e624bdba-077a-4b87-a5af-381e1b205eca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |
