### ISSUE TITLE
Feat: Instagram Scaper

### ISSUE THREAD

**Issue by Rhythm408** [Clueless-Community/scrape-up#426]
### Describe the feature

Adding Instagram Features like home page, login page, explore section.

### Add ScreenShots

![WhatsApp Image 2023-07-02 at 7 54 04 PM (1)](https://github.com/Clueless-Community/scrape-up/assets/134213459/7494cbf4-6d9f-458c-a853-6c855db08552)
![WhatsApp Image 2023-07-02 at 7 54 04 PM](https://github.com/Clueless-Community/scrape-up/assets/134213459/a77e2a37-9864-42f9-ae78-9e8f486b6083)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey, Instagram does not allow us to scrape data. A few of our contributors tried but failed.

You can give it a try.

**Note**
+ You can use selenium, but not its tools like `webdriver` which is required to be installed on a system initially.

**Comment by SohamMane19** [comment]
I am newbie to open source,can anyone explain me about what is the feature to be implemented?

**Comment by Rhythm408** [comment]
Okay Sir I will try!

**Comment by WhoIsJayD** [comment]
> Hey, Instagram does not allow us to scrape data. A few of our contributors tried but failed.
> 
> You can give it a try.
> 
> **Note**
> 
> * You can use selenium, but not its tools like `webdriver` which is required to be installed on a system initially.

Actually there is a way to scrape but for that the user must be logged in.
I can explain you how you can achieve it !

Take any Instagram URL (For example : https://www.instagram.com/instagram/ )
Now in this url add : `?__a=1&__d=dis`
Like : `https://www.instagram.com/instagram/?__a=1&__d=dis`
You will se the exposed data with all urls : 
This works with any Instagram url (reels,profile,post etc...)

[example_data.txt](https://github.com/Clueless-Community/scrape-up/files/12051143/example_data.txt)

**Comment by Rhythm408** [comment]
Thanks, I'll check it out.

**Comment by WhoIsJayD** [comment]
@nikhil25803 is it possible to work on this?
I may have achieved it without logging in.

![image](https://github.com/Clueless-Community/scrape-up/assets/88286024/23215806-8c86-4e7c-bcd4-370b116a8a22)

**Comment by nikhil25803** [comment]
Scraped using selenium webdriver?

**Comment by WhoIsJayD** [comment]
> Scraped using selenium webdriver?

No just get request

**Comment by WhoIsJayD** [comment]
@nikhil25803

**Comment by nikhil25803** [comment]
Make the PR @WhoIsJayD |

**Comment by WhoIsJayD** [comment]
@nikhil25803 Will it be okay if it requires user login?
It was working yesterday without login but today it is not working so I am working on login system.
It is working just to combine and update the codes

**Comment by WhoIsJayD** [comment]
@nikhil25803 ?

**Comment by nikhil25803** [comment]
No @WhoIsJayD
