### ISSUE TITLE
Feat: Add new Reddit Scrapper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#427]
### Describe the feature

Add new Reddit scrapper as the reddit scrapper folder is empty.

### Add ScreenShots

![reddit](https://github.com/Clueless-Community/scrape-up/assets/42113027/1c45125d-cc7e-458a-ae20-a53754a59bfb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |
