### ISSUE TITLE
Feat: Improve Coursera scraper to return in JSON

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#428]
### Describe the feature

To improve the Coursera scraper to return in JSON and also return other different informations.

### Add ScreenShots

![coursera](https://github.com/Clueless-Community/scrape-up/assets/42113027/1281f1d5-4f58-46fc-8fbf-fa76c8170867)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Fix it @Mihan786Chistie |

**Comment by Mihan786Chistie** [comment]
> Fix it @Mihan786Chistie |

Will do
