### ISSUE TITLE
Feat: Improve the Hacker news scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#429]
### Describe the feature

To improve the Hacker news scraper to retrieve more data in JSON

### Add ScreenShots

![hackerNews](https://github.com/Clueless-Community/scrape-up/assets/42113027/1ac000c7-7a32-45ef-aa7f-019713ab7e53)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |
