### ISSUE TITLE
Feat:Add scraper to scrape 'alternativeto.net'

### ISSUE THREAD

**Issue by mukund1606** [Clueless-Community/scrape-up#431]
### Describe the feature

Scraper to scrape 'alternativeto.net' and provide with alternative for the apps we search for with there features.
Also add filters like shown in image and more(still thinking about more features) 
Will keep on updating about features as soon as get some more ideas

### Add ScreenShots

![Screenshot_2023-07-04-11-27-01-191_com android chrome-edit](https://github.com/Clueless-Community/scrape-up/assets/85615134/7a13687e-4d57-40b0-8fd5-507a95bcfa5a)
![Screenshot_2023-07-04-11-29-12-159_com android chrome-edit](https://github.com/Clueless-Community/scrape-up/assets/85615134/e6baf98f-c78c-46e4-be95-795326e27200)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Sounds good, go ahead @mukund1606 |
