### ISSUE TITLE
Feat: "BEST LAPTOP FOR STUDENTS"data scrap from 'flipkart'

### ISSUE THREAD

**Issue by Sushilverma002** [Clueless-Community/scrape-up#434]
### Describe the feature

as we know that laptop become the necessity of students . like every thing move to online for that students are new to purchase a laptop they must want a data which one is the best laptop with best features. for that the SCARPING OF LAPTOP DATA from flipkart must help to all the students or any one for selecting the best one for them.
data contain 👍 ;
1. product name
2. prize
3. reviews 
4. description 
*try and catch method is flowed for scraping.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/114687502/4bdfaa6d-f22a-4de2-815a-3b887825b7ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by Sushilverma002** [comment]
@nikhil25803 have a look!!!!!!!!!!!!!!1

**Comment by nikhil25803** [comment]
Go ahead @Sushilverma002 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch all the laptops only(no keywords like student, professional, etc).
+ Do not use Selenium `Chrome Web Driver`, they are not compatible with the packages,
