### ISSUE TITLE
Feat: Udemy Scraper

### ISSUE THREAD

**Issue by prathameshParadkar** [Clueless-Community/scrape-up#436]
### Describe the feature

Adding Scraper of Udemy:
- Scrape various courses from udemy 
- Scrape data from a specific course
- Return JSON data

### Add ScreenShots

**Scrape data by searching:**

![image](https://github.com/Clueless-Community/scrape-up/assets/108287510/fb0a9f6f-5f9b-4bfe-8ef6-73c74966f48b)

**Scrape data if a specific selected course like Course Content, Sections, etc**

![image](https://github.com/Clueless-Community/scrape-up/assets/108287510/6ba7c311-6101-4ac5-83f4-ba31028b6e31)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @prathameshParadkar 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Work on one method at first, like a method to fetch the top courses of each category.
+ User will provide the keyword as a constructor to the class and then call a method on it to return the data
