### ISSUE TITLE
Feat:Scrape Cricbuzz for Cricket News

### ISSUE THREAD

**Issue by mukund1606** [Clueless-Community/scrape-up#438]
### Describe the feature

Will scrape cricbuzz to get scores of live matches, past matches etc..
Get details about upcoming series,
Add filters like domestic, international etc..
Also get team details like team stats player stats etc..

### Add ScreenShots

![Screenshot_2023-07-06-18-13-45-288_com android chrome](https://github.com/Clueless-Community/scrape-up/assets/85615134/0a2045c7-ed7a-473a-af5e-214739375b06)
![Screenshot_2023-07-06-18-14-02-084_com android chrome](https://github.com/Clueless-Community/scrape-up/assets/85615134/04b6b8f4-9e61-4c1e-a43a-628eb6a1a9c2)
![Screenshot_2023-07-06-18-14-09-736_com android chrome](https://github.com/Clueless-Community/scrape-up/assets/85615134/add96511-8bb3-46c0-94e9-993a5eb820e4)
![Screenshot_2023-07-06-18-14-24-694_com android chrome](https://github.com/Clueless-Community/scrape-up/assets/85615134/21b0c481-9354-4106-ab93-e9a914ab77ad)
![Screenshot_2023-07-06-18-17-20-037_com android chrome](https://github.com/Clueless-Community/scrape-up/assets/85615134/747e8f39-0b72-4f52-b2c8-99f24f3ce7f4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @mukund1606 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use `Selenium` `Chrome Webdriver`, as they are required to be installed on the local machine to work. Hence not compatible with packages.
