### ISSUE TITLE
Topics mentioned in a repository.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#44]
## Proposed Method:
`.tags()`

### Description
Create a method to get the list of tags used in a repository.

## To what class it belongs?:
`Repository`

**Comment by Sar-thak-3** [comment]
I'm interested, kindly assign it to me under JWOC

**Comment by Sar-thak-3** [comment]
#39 is done kindly review it as soon as possible and assign the next issue.

**Comment by codingis4noobs2** [comment]
@nikhil25803 I want to work on this issue under JWOC.

**Comment by nikhil25803** [comment]
Assigning it to you @codingis4noobs2 :))

**Comment by codingis4noobs2** [comment]
@nikhil25803 the one you mentioned, it's topics pls edit this issue
