### ISSUE TITLE
Feat: Hashnode Search scrapper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#444]
### Describe the feature

To scrape the search results in Hashnode website and return the results in JSON format.

### Add ScreenShots

![hashnodeSearch](https://github.com/Clueless-Community/scrape-up/assets/42113027/4644d360-d811-4038-8a17-1556bd2190cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |

**Comment by pooranjoyb** [comment]
Can I take this issue as it's pending for last 2 weeks? @nikhil25803 😄

**Comment by Mihan786Chistie** [comment]
> Can I take this issue as it's pending for last 2 weeks? @nikhil25803 😄 

I am working on it @pooranjoyb
