### ISSUE TITLE
Feat: YouTube Channel Videos Scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#450]
### Describe the feature

To scrape all the videos published by the channel and present all the details in JSON.

### Add ScreenShots

![githubVideos](https://github.com/Clueless-Community/scrape-up/assets/42113027/f2367ad2-cf38-4454-ab2a-50f75bcae5aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |
Add this method to the `Channel` class you created.
