### ISSUE TITLE
Feat: Youtube Channel Community posts Scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#451]
### Describe the feature

To scrape all the posts in the YouTube channel community page and retrieve all the post details in JSON format.

### Add ScreenShots

![youtubeCommunity](https://github.com/Clueless-Community/scrape-up/assets/42113027/bc70e1e7-b0cf-44bb-a22b-c71deeb82548)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie | Add this one in the `Channel` class as well.

I had made changes in your code, instead of the channel URL, now it asks for the channel username and then it navigates to the required section. So take care of that. Made changes according to that only.

**Comment by Mihan786Chistie** [comment]
> Go ahead @Mihan786Chistie | Add this one in the `Channel` class as well.
> 
> I had made changes in your code, instead of the channel URL, now it asks for the channel username and then it navigates to the required section. So take care of that. Made changes according to that only.

Ok @nikhil25803
