### ISSUE TITLE
Feat: Reddit feed scraper for different tags

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#456]
### Describe the feature

To add different tags in the Reddit feed to be scraped

### Add ScreenShots

![reddit_tags](https://github.com/Clueless-Community/scrape-up/assets/42113027/8e472b3b-bbcf-41e7-aa6c-0308a3b907ef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie
