### ISSUE TITLE
Feat: headphones scrap from flipkart

### ISSUE THREAD

**Issue by Sushilverma002** [Clueless-Community/scrape-up#457]
### Describe the feature

as headphone is like necessary for everyone and it difficult to choose for that data will help everyone for when they buy.
try and catch method is used.
@nikhil25803 have a look!!!!!!!!!!!!!

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/114687502/f3b567b2-9b60-43d5-9a72-6cc9597b65d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Sushilverma002 |
