### ISSUE TITLE
Feat: camera scrap form flipkart

### ISSUE THREAD

**Issue by Sushilverma002** [Clueless-Community/scrape-up#459]
### Describe the feature

the data help customers to choose best one according to there needs.
data contain
product name
description 
review 
prize
off info from actual prize.
@nikhil25803 have a look!!!!!!!!

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/114687502/2c346bdc-2f8a-4784-ae26-f2b8ebe310c7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Sushilverma002
