### ISSUE TITLE
Feat:Scraping Simple wikipedia

### ISSUE THREAD

**Issue by alwenpy** [Clueless-Community/scrape-up#461]
### Describe the feature

Python script for Scraping simple wikipedia.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/94129388/eebf67c9-c0fc-4b2b-8671-64fa071a4e40)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
We already have one Wikipedia module, to scrape the complete page.
