### ISSUE TITLE
Feat: Scraping T-shirts from Flipkart

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#462]
### Describe the feature

I'd scrape the data related to T-shirts from flipkart, which would contain all relevant information about what kind of data it is, and so on. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-12 at 9 54 59 AM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/7aba5845-fcf0-44a0-8cc8-3ec3f20fa67e">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please check out my issue request. Thanks!

**Comment by nikhil25803** [comment]
Go ahead @jaivsh

**Comment by jaivsh** [comment]
@nikhil25803 please review this PR, so that i can start working on other issues asap! Thanks!
