### ISSUE TITLE
Feat: WHO Covid Dashboard scraper 

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#463]
### Describe the feature

I'd scrape all the important information about the covid statistics on the WHO website, and would store it in the form of variables/functions which can be referenced easily. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-12 at 10 17 39 AM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/9d6ba5f2-ed21-427b-9f33-28ddf4dba59d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this. Thanks!

**Comment by nikhil25803** [comment]
Go ahead @jaivsh
