### ISSUE TITLE
Feat:Scraping Myntra

### ISSUE THREAD

**Issue by alwenpy** [Clueless-Community/scrape-up#464]
### Describe the feature

Using Python script ,scrape Myntra an ecommerce platform.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/94129388/a05e5d1d-4d9f-4293-bb50-7dc0b76b37d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @alwenpy
