### ISSUE TITLE
Feat:Scraping Python documention

### ISSUE THREAD

**Issue by alwenpy** [Clueless-Community/scrape-up#465]
### Describe the feature

Scraping python.org.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/94129388/3d317354-652e-470f-b7d0-27c0d3f804c4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
No need of it right-now.
