### ISSUE TITLE
Feature Request: Designing a website for "Scrape Up"

### ISSUE THREAD

**Issue by yaten2302** [Clueless-Community/scrape-up#467]
### Describe the feature

Hi @nikhil25803, I was having an idea for designing a website for promoting "Scrape Up" tool.

Here, we can add all the details, features, showing the steps how to proceed with a demo video. Also, there can be a "Contact page" and "FAQs page", if someone faces a problem, then he/she can first check out the FAQs, if the problem is not resolved, he/she can reach you out easily.

Please assign this issue to me under GSSOC'23, as I want to work on it🙏🙏

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
We are not looking for a website right now. So closing this PR for now.
