### ISSUE TITLE
Feat: Scraping yahoo finance

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#472]
### Describe the feature

I'd scrape the yahoo finance website, and would extract majority of the relevant financial info from the same. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-13 at 11 19 19 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/0e3af951-65df-4fcb-89f4-00fb770affe4">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this!

**Comment by nikhil25803** [comment]
We already have modules from `Finance` class.
