### ISSUE TITLE
Feat: Get all merged prs of a user

### ISSUE THREAD

**Issue by ritik48** [Clueless-Community/scrape-up#473]
### Add ScreenShots

![scrswsddw](https://github.com/Clueless-Community/scrape-up/assets/84488726/11243283-93ee-400f-ac3e-1cfe1c90a1b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by ritik48** [comment]
@nikhil25803 please assign me this issue

**Comment by ritik48** [comment]
@nikhil25803 please assign me this issue

**Comment by nikhil25803** [comment]
Sounds good @ritik48 |
