### ISSUE TITLE
Feat: CNN news source website scraper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#474]
### Describe the feature

I'd scrape the CNN international website, extracting articles, news references, country wise news, most popular international news around the world, and so on. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-13 at 11 41 42 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/dae2ea9f-2b60-4048-999e-0e36a87fbebd">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please check out my issue request. Thanks!

**Comment by nikhil25803** [comment]
Go ahead @jaivsh

**Comment by jaivsh** [comment]
> Go ahead @jaivsh

@nikhil25803 I've put up the PR, can u please check it? Thanks!
