### ISSUE TITLE
Feat: Mediline-Plus medical encyclopedia scraper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#475]
### Describe the feature

I'd scrape all the details from the medical encyclopedia published and maintained by Mediline-Plus, which contains info about all medicines, most famous medicines, their usage, and so on. It also contains a glossary about various medical terms. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-13 at 11 50 43 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/084ab20b-efda-4566-a62a-5e3e9e4a7e93">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please check out my issue request. Thanks!

**Comment by nikhil25803** [comment]
Sounds good, go ahead @jaivsh |

**Comment by jaivsh** [comment]
> Sounds good, go ahead @jaivsh |

thanks!
