### ISSUE TITLE
[DOC] : Adding a small Licenses section to the readme and a MIT Licenses badge 

### ISSUE THREAD

**Issue by 1Shubham7** [Clueless-Community/scrape-up#477]
### What's wrong with the existing documentation

The readme file of the repo should have a Licenses section to make it more professional.

### Add ScreenShots

I can add a licenses section and a MIT License Badge to the readme
![afters](https://github.com/Clueless-Community/scrape-up/assets/116020663/7a28771c-199f-440d-b808-57bc2c788a56)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by nikhil25803** [comment]
Go ahead @1Shubham7 |
