### ISSUE TITLE
Feat: Adding newer functions to Flipkart

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#479]
### Describe the feature

>I'd add the following functions to flipkart class for every product category:
   - bestselling(): It would return the top best selling products list on flipkart
   - range(min,max, type): It would return the products from a specific price range and **type** category
   - rating(reqrating): It would return the products having minimum rating as the specified rating by the user. 
   - newlaunches(category): It would return the newly launched products of a specified category.

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-14 at 7 33 19 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/1910061c-5ccb-4af9-81a7-f8fd7bdd2765">

<img width="1470" alt="Screenshot 2023-07-14 at 7 33 42 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/ff6211ef-a6e4-418f-bdac-8dfd700c17a8">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this!

**Comment by nikhil25803** [comment]
Go ahead @jaivsh | Add the methods following the code convention with proper docstring this time.
