### ISSUE TITLE
Feat: CodeChef Scraper

### ISSUE THREAD

**Issue by vanshiz** [Clueless-Community/scrape-up#481]
### Describe the feature

CodeChef is a site used by numerous coding enthusiast for the purpose of Competitive Programming. The primary objective of the CodeChef Scraper is to automate the process of collecting data from CodeChef's website, including problem statements, test cases, submissions, rankings, and user profiles. 

### Add ScreenShots

<img width="960" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/134791959/4ea9ebde-81f0-434a-b253-9204c5ee8ed2">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @vanshika2910 
**Note**
+ Create a separate module for this, as per the folder and project structure
