### ISSUE TITLE
Feat: Add Module Scrapper for Coursera

### ISSUE THREAD

**Issue by pooranjoyb** [Clueless-Community/scrape-up#482]
### Reason/Context
How will this change help?
Users will be able to scrape **Modules in the specific courses** from the **Coursera Website**. 

#### Description
What changes have to be introduced?
User will type in the `Course Name` and the `API` will return a JSON string with all the modules from the course.

#### Will this be a breaking change?
No, it won't be breaking any change but will add a new feature to the `API`.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/90945182/4f497b11-4e5e-4c54-9d0e-0b828f941919)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @pooranjoyb

**Comment by pooranjoyb** [comment]
> Go ahead @pooranjoyb 
> **Note**
> + Create a separate module for this, as per the folder and project structure

On it! 🚀
