### ISSUE TITLE
Feat: Adding Job Scrapper in Internshala

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#483]
### Describe the feature

I would like to add a new method "jobs" to Internshala class and scrap relevant details

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/df8be8f8-e999-482c-abcd-c8cdfe85d29f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
The Internshala module is already there, see if you can add any method to it. 

Do not create a separate module or class for it.

**Comment by Juhibhojani** [comment]
Yes, I will just be creating a new method in the same module.

**Comment by Juhibhojani** [comment]
Hey @nikhil25803, Can you help me understand how the search_type argument in the Internships method work, as it appears that irrespective of the argument, it generates the same output?
I have successful written code for Jobs method but just confused whether to add search_type argument or not.

**Comment by nikhil25803** [comment]
Yes, I checked it now only.
Can you fix it? Or replace it with your method and raise a PR.

**Comment by Juhibhojani** [comment]
Yes, I won't be using Selenium, just requests library.  Should I create a new issue for correction in the internship method?
