### ISSUE TITLE
Feat: Adding Google News Scrapper

### ISSUE THREAD

**Issue by sunayana-01** [Clueless-Community/scrape-up#484]
### Describe the feature

I want to add a google news scrapper that scrapes:

- Top Stories of the day
- News related to a user-provided word query.
- News related to a user-provided category query.

### Add ScreenShots

<img width="606" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/79215056/a8a8ffe6-bbb4-401d-bd42-df09457f64b1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Google News module is already there @sunayana-01 |
See if you can add any methods to add more functionality and enhance it.

Good luck with the changes @sunayana-01
