### ISSUE TITLE
Feat: Reddit search scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#487]
### Describe the feature

To scrape the search results in reddit website and return the results

### Add ScreenShots

![redditSearch](https://github.com/Clueless-Community/scrape-up/assets/42113027/fcec2483-fb5b-408b-aa70-6e7f7652b412)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |
