### ISSUE TITLE
Feat: Function to get all currently opened issues of a user

### ISSUE THREAD

**Issue by ritik48** [Clueless-Community/scrape-up#489]
### Describe the feature

I would like to add a function in user class of github, which would fetch all the issues that the user has raised and is currently open.

### Add ScreenShots

![iii](https://github.com/Clueless-Community/scrape-up/assets/84488726/3ef6090d-8df2-49b7-aad1-29af006243af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
@ritik48 | I see you used the API in the last PR you made, do not add this time, we are building an API alternative so it doesn't make sense to use APIs beneath.

I will refactor/remove that code as well, try to implement it without using API and, if possible, refactor the previous code.

**Comment by ritik48** [comment]
@nikhil25803 I used the api as it was working faster than parsing the html. Still now worries, I'll refactor the previous code.
Thanks for assigning the issue.

**Comment by nikhil25803** [comment]
Speed is not an issue @ritik48 | APIs do have rate limits, so after a plenty of calls, it requires API keys

**Comment by ritik48** [comment]
okay now I understand why we are not using api . Thanks for clarification @nikhil25803
