### ISSUE TITLE
Feat: Adding Top TV shows in IMDB scrapper

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#491]
### Describe the feature

I would like to add a method in the IMDB class, scraping top tv shows.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/46842d53-0ebe-41a7-b4af-4d890df93a39)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani |
IMBD module is already there, add the functionality you want as a method only.

**Comment by Juhibhojani** [comment]
@nikhil25803, the top_rated method isn't working here.
