### ISSUE TITLE
Feat: Scrapping Flyrobo

### ISSUE THREAD

**Issue by WhoIsJayD** [Clueless-Community/scrape-up#492]
### Describe the feature

Searches for the item and gives all the detailed information

Input : Search item 
Output Json output :
[flyrobu_scraper_results.txt](https://github.com/Clueless-Community/scrape-up/files/12063478/flyrobu_scraper_results.txt)

### Add ScreenShots

Output : 
![image](https://github.com/Clueless-Community/scrape-up/assets/88286024/d840822e-3e5f-4fd8-b94b-7ba4214e6404)

https://www.flyrobo.in/index.php?route=product/search&search=arduino&description=true&limit=100
![image](https://github.com/Clueless-Community/scrape-up/assets/88286024/d16c90df-f24a-4180-b30f-04432375937e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by WhoIsJayD** [comment]
@nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @WhoIsJayD
