### ISSUE TITLE
Feat: Scraping Robu

### ISSUE THREAD

**Issue by WhoIsJayD** [Clueless-Community/scrape-up#497]
### Describe the feature

Searches for the item and gives all the detailed information

Input : search item
Output Json output : [Search item : arduino]
[robu.txt](https://github.com/Clueless-Community/scrape-up/files/12064100/robu.txt)

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/88286024/98fd3d95-31cb-46ac-b792-cf2d037524a4)
![image](https://github.com/Clueless-Community/scrape-up/assets/88286024/550851f6-a363-447e-9d75-7269e849de55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by sovanmohan** [comment]
Hello @nikhil25803 I want to work on this issue
