### ISSUE TITLE
Feat: CodeForces Contest Scrapper

### ISSUE THREAD

**Issue by ojaswi18** [Clueless-Community/scrape-up#498]
### Describe the feature

Most of the students practice competitive programming by given contest on codeforces . I would like to code a scrapper that that scrapes :
 1. Contest Name
 2. Contest type(div)
 3. Start Date and Time and the length of contest
 4. URL that will allow users to directly navigate to registration page

I have provided ss of the page from which I will scrape the above listed. 
@nikhil25803 kindly checkout the issue and assign it to me. 

### Add ScreenShots

![codeforcescontset](https://github.com/Clueless-Community/scrape-up/assets/102872838/84bfc36a-e645-4503-85c9-93f35a3a3942)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @ojaswi18 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.
