### ISSUE TITLE
Feat: Library Genesis Scraper (Book Scraper)

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Clueless-Community/scrape-up#499]
### Describe the feature

This scraper will scrape books and there details from the website .
I will be scraping the site below

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85278243/56da041d-ec7e-494f-aef4-f3ca89f7690e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Swapnil-Singh-99 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

**Comment by Swapnil-Singh-99** [comment]
Sure
