### ISSUE TITLE
Add method for getting readme 

### ISSUE THREAD

**Issue by ayushanand308** [Clueless-Community/scrape-up#50]
**Is your feature request related to a problem? Please describe.**
We may need to have readme file for a user

**Describe the solution you'd like**
Scrape the users profile and get its readme and save it to directory of the user.

**Describe alternatives you've considered**
No alternatives

**Additional context**
--

**Comment by ayushanand308** [comment]
Please assign me this issue under JWOC

**Comment by nikhil25803** [comment]
Sounds good, go ahead @ayushanand308

**Comment by ayushanand308** [comment]
Created a PR for this @nikhil25803

**Comment by nikhil25803** [comment]
Added some comments, check once again @nikhil25803
