### ISSUE TITLE
Feat: Swiggy restraurant details scrapper

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Clueless-Community/scrape-up#500]
### Describe the feature

This Swiggy Scraper will allow you to scrape data of a restraunt listed on Swiggy 
The scrapper will scrape details like name of restraunt and other details.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85278243/a0eaf66c-5097-4f4a-8982-96dbde2ca280)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Swapnil-Singh-99 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

**Comment by Swapnil-Singh-99** [comment]
Ok
