### ISSUE TITLE
Feat: Add getDinnerWith50PercentOff() method in EazyDiner Class to fetch restaurants offering Dinner at 50% off

### ISSUE THREAD

**Issue by Nishitbaria** [Clueless-Community/scrape-up#501]
### Describe the feature

Currently, the `EazyDiner` class provides methods to fetch restaurants based on different meal periods, such as breakfast, lunch, and dinner. However, there is no specific method to fetch restaurants offering dinner with a 50% discount. This feature would be beneficial for users who are interested in finding dinner options at a discounted price.

**Proposed Solution:**
I suggest adding a new method called `getDinnerWith50PercentOff()` to the `EazyDiner` class. This method will fetch restaurants that offer dinner with a 50% discount in the specified location. The method will use the EazyDiner website's API to retrieve relevant information about such restaurants.

**Method Signature:**
```python
def getDinnerWith50PercentOff(self) :
    """
    Fetches a list of restaurants offering dinner at 50% off in the specified location.

    Returns:
    A JSON string containing the details of restaurants.
    """
```

**Example Usage:**
```python
delhi_diner = EazyDiner("Delhi NCR")  # or delhi_diner = EazyDiner("delhi-ncr")
result = delhi_diner.getDinnerWith50PercentOff()
print(result)
```

**Expected Output:**
The `result` variable should contain a JSON string with details of restaurants offering dinner at a 50% discount in Delhi NCR. The JSON structure should include information such as restaurant name, location, rating, cuisine, and price for two people.

@nikhil25803 ,please assign me this issue,I will create pull request asap

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85815172/2a17c87c-8908-4f79-8469-ffafa57d832d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by Nishitbaria** [comment]
@nikhil25803 ,please assign me this issue,I will create pull request asap

**Comment by nikhil25803** [comment]
Go ahead @Nishitbaria 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

**Comment by Nishitbaria** [comment]
@nikhil25803 ,please review and merge my pull request
