### ISSUE TITLE
Feat:Adding a script for google trends

### ISSUE THREAD

**Issue by alwenpy** [Clueless-Community/scrape-up#503]
### Describe the feature

Script using BeautifulSoup to provide you Google search and Trend Result.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/94129388/7ccf6252-2cdb-4b82-ad6b-55ed4b88f59c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @alwenpy 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

**Comment by alwenpy** [comment]
I am using Pytrends library that is an API for Google Trends

**Comment by nikhil25803** [comment]
No no, we are building an API alternative and can not use an API beneath, then what's the point?

Do it with scraping,  using libraries that are  compatible on all the devices like `bs4` and `scrapy`.
