### ISSUE TITLE
Feat: Adding bestsellers in kindle ebook method

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#505]
### Describe the feature

Adding the top ebooks method in the kindle class

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/4d54602c-bb66-4ca3-98a7-8d3953615519)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

**Comment by Juhibhojani** [comment]
So I have to add this as a method in kindle folder right?

**Comment by nikhil25803** [comment]
Yes @Juhibhojani | Add your functionality as a method.
