### ISSUE TITLE
BUG: top_rated() method in IMDB isn't working

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The top_rated() method when called is returning 'Unable to fetch top rate movie' but changes in it should make it work. So i would like to work on it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Yes, I noticed it as well.

Fix it @Juhibhojani
