### ISSUE TITLE
Feat: add Insights page scraper for Github Repository Class

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#511]
### Describe the feature

To add insights page scraper and display all the data in it

### Add ScreenShots

![gtihubRepoInsights](https://github.com/Clueless-Community/scrape-up/assets/42113027/57e1a5fb-15a0-4643-87d7-3073ff112c51)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Sounds good @Mihan786Chistie |

Go ahead @Mihan786Chistie 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.
