### ISSUE TITLE
Feat: Scrape Wikipedia

### ISSUE THREAD

**Issue by malikamujahid** [Clueless-Community/scrape-up#512]
### Describe the feature
wikipedia is a complete unit that stores some huge amount of data from all over the world
Under the label of 
GSSOC'23 allow me to scrape Wikipedia. 

### Add ScreenShots

![WIKIPEDIA](https://github.com/Clueless-Community/scrape-up/assets/110493023/1d317ffa-39bf-4d77-bcb9-216c9c4f1d19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @malikamujahid 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

**Comment by malikamujahid** [comment]
ok got it! Ty!

**Comment by malikamujahid** [comment]
wikipeidia is already present, can i do it for dailymotion?
