### ISSUE TITLE
Feat:Scraping ICC page 

### ISSUE THREAD

**Issue by alwenpy** [Clueless-Community/scrape-up#514]
### Describe the feature

Scraping ICC page for cricket related data like records ,current standings of batsman etc. using `bs4`

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/94129388/7d7b825e-a05c-402d-a68a-619a467a20a5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @alwenpy 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.
