### ISSUE TITLE
Feat: Adding bestsellers method in amazon module

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#519]
### Describe the feature

I would like to add a method that retrieves the top sellers in each category from Amazon webpage

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/d5a89cfa-9fb2-4f8f-bb0d-87a6af82ceaf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
