### ISSUE TITLE
Scrape the tags of a repository.

### ISSUE THREAD

**Issue by Akshat103** [Clueless-Community/scrape-up#52]
## Proposed Method:
`.tags()`
### Description
Create a method to get the tags of a repository, that is the title tags.
## To what class it belongs?: 
`Repository`

**Comment by nikhil25803** [comment]
Go ahead @Akshat103

**Comment by Akshat103** [comment]
Hii I just gone throught code this issue is already resolved as #44.

**Comment by nikhil25803** [comment]
> Hii I just gone throught code this issue is already resolved as #44. Sorry for that.

Tags and topics are different, you may give a try to it :))

**Comment by Akshat103** [comment]
Ok Thanks Let me try.
