### ISSUE TITLE
Feat: eBay scrapper

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#520]
### Describe the feature

Scrapping deals on eBay in different categories

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/798c6863-7a7f-4b95-9c2b-0e1dd3e1d5e3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
