### ISSUE TITLE
Feat: Data Scraping of tablets from 'flipkart' [GSSoc'23]

### ISSUE THREAD

**Issue by kanishkasah20** [Clueless-Community/scrape-up#523]
### Describe the feature

I will do scraping of tablets data from flipkart which consists of product name , prize , reviews , description using try and catch method for scraping.
Under the label of GSSOC'23 allow me to scrape flipkart.

### Add ScreenShots

<img width="945" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/4a89a2f6-64bc-41e7-8153-f3037710def5">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @kanishkasah20 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
