### ISSUE TITLE
Feat: Improve hackerNews scraper to retrieve other articles

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#525]
### Describe the feature

To improve hackerNews scraper to retrieve other articles such as new, past, jobs, etc.

### Add ScreenShots

![hackerNews_otherArticles](https://github.com/Clueless-Community/scrape-up/assets/42113027/41d5bf80-9b9c-48d3-af72-e46f5a51d8bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
