### ISSUE TITLE
Feat: Improve hashnode getFeed()

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#528]
### Describe the feature

To improve the hashnode getFeed() function as the hashnode website elements for each data has changed

### Add ScreenShots

![hasnode_getFeed](https://github.com/Clueless-Community/scrape-up/assets/42113027/e634e89d-03d4-40d5-9e00-82f79c6f3422)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
