### ISSUE TITLE
Feat:Add Method to Retrieve Detailed Product Description and Specification in Flyrobu Class

### ISSUE THREAD

**Issue by Nishitbaria** [Clueless-Community/scrape-up#531]
### Describe the feature

Issue Description:
I would like to propose an enhancement to the `Flyrobu` class in the Flyrobu project. Currently, the `Flyrobu` class provides a method to search for products and get basic product information. However, it lacks a method to retrieve more detailed product descriptions and specifications.

Suggested Enhancement:
I suggest adding a new method called `get_product_details` to the `Flyrobu` class, which will allow users to fetch detailed information about a specific product given its product name or URL on the Flyrobu website.

The proposed `get_product_details` method should be responsible for:

1. Accepting a product name or URL as input.
2. Fetching the product page
3. Extracting the product's detailed description and features from the product page
4. Extracting the technical specifications (if available) of the product.
5. Extracting the current and original prices (if available) of the product.
6. Retrieving the product's image URL.
7. Extracting the "Package Includes" details (if available) from the product description.
8. Returning the extracted details as a JSON object.

Here's a brief outline of the proposed method signature:

```python
def get_product_details(self, product_name: str) -> dict:
    """
    Retrieves detailed product information for the given product name or URL.

    Parameters:
        product_name (str): The name or URL of the product.

    Returns:
               The json data will include keys like 'Description', 'Features', 'Technical Details',
              'Current Price', 'Original Price', 'Image', and 'Package Includes'.
              If any information is not available for the product, the respective key will be missing from the dictionary.
              If an error occurs during fetching, it will return None.
    """
    # Method implementation here
```

### Output
![image](https://github.com/Clueless-Community/scrape-up/assets/85815172/58e943fe-c77f-4d22-8068-b34076a216e3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by Nishitbaria** [comment]
@nikhil25803 ,please assign me this issue ,i will make pr in 5 min

**Comment by nikhil25803** [comment]
Go ahead @Nishitbaria 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻

**Comment by Nishitbaria** [comment]
@nikhil25803 ,please review and merge my pul request
