### ISSUE TITLE
Feat: Scrap UCI machine learning repository

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#534]
### Describe the feature

Scrap datasets from the UCI machine learning repository.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/9a59062e-ce56-416d-bfa7-4d6f4d2537ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
