### ISSUE TITLE
Feat: scrap data formal shirt for men from flipkart

### ISSUE THREAD

**Issue by Sushilverma002** [Clueless-Community/scrape-up#535]
### Describe the feature

data scrap for formal shirt for mens.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/114687502/57ddf38f-f77f-422a-9a4e-c1485f3a2ba0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by Sushilverma002** [comment]
@nikhil25803 have a look!

**Comment by nikhil25803** [comment]
Go ahead @Sushilverma002 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
