### ISSUE TITLE
Feat: Creating Flask Server with a Route for Retrieving HTML Content

### ISSUE THREAD

**Issue by WhoIsJayD** [Clueless-Community/scrape-up#536]
### Describe the feature

We need to build a Flask server from scratch, including a route that allows users to retrieve HTML content from a specified URL. This new route will utilize the Selenium WebDriver to fetch the HTML content, enabling easier data scraping and efficient request management.

Developing a Flask server and implement a new route, `/gethtml`, to handle requests for HTML retrieval. This route will use the Selenium WebDriver to fetch the HTML content from the provided URL and respond with the extracted data.

**Route Details:**

1. Route: `/gethtml`
   - Method: GET
   - Parameters:
     - `url`: The URL from which the HTML content needs to be fetched.
   - Example: `localhost:3000/gethtml?url=https://www.hotstar.com/in/home`
   - Response: The HTML content from the specified URL using the Selenium WebDriver.

**Steps to Implement:**

1. Set up the Flask server with a basic configuration.
2. Install and configure the Selenium WebDriver to interact with web pages.
3. Implement the `/gethtml` route to fetch the HTML content from the specified URL using the Selenium WebDriver.
4. Handle errors gracefully for cases where the provided URL is invalid or inaccessible.
5. Test the route thoroughly to ensure its reliability and compatibility with various URLs and scenarios.

**Benefits:**
The implementation of this new route will provide the following benefits:

1. Simplified data retrieval: Users will have a convenient endpoint for fetching HTML content from any given URL.
2. Streamlined data scraping: The integration of Selenium WebDriver will ensure access to dynamic content and client-side rendered elements, enhancing the effectiveness of data scraping.
3. Improved request management: With a dedicated route for HTML retrieval, the server can efficiently handle incoming requests for data extraction purposes.

### Add ScreenShots

# No screenshots right now

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by WhoIsJayD** [comment]
@nikhil25803 is this feasible to do this?

**Comment by nikhil25803** [comment]
No @WhoIsJayD |
