### ISSUE TITLE
Feat: Adding a CodeChef Details scraper

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Clueless-Community/scrape-up#539]
### Describe the feature

I will be adding a CodeChef scraper that will scrape details of the user vai username and displays it to the user

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85278243/4a2a72c2-daf1-4771-99c2-756ac1395c31)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Swapnil-Singh-99 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
