### ISSUE TITLE
Feat: Improve CNN news scraper with search functionality

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#544]
### Describe the feature

To add search functionality to CNN scraper for the clients to search for a topic

### Add ScreenShots

![cnn_search](https://github.com/Clueless-Community/scrape-up/assets/42113027/44898637-3d02-4639-a323-64ffe2bc0395)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |
