### ISSUE TITLE
Feat: IMDB scraping

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#548]
### Describe the feature

Hi @nikhil25803 

I am a GSSoC '23 contributor, I would like to add an IMDB scraper which can search for a movie name and get a description, rating and actors.

Please assign me this issue.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/e3c43939-89ea-4a6c-a1e3-d2ff10dbdd5c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
