### ISSUE TITLE
Feat: Web Scraping Walmart Data

### ISSUE THREAD

**Issue by RoopakMallik** [Clueless-Community/scrape-up#551]
### Describe the feature

Web Scraping Walmart Data

### Add ScreenShots

I would like to work on this issue and complete the project once it is assigned.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @RoopakMallik 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
