### ISSUE TITLE
Feat: Retrieving contest details from hackerrank

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#555]
### Describe the feature

Scrapping information regarding the contest from Hakerrank

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/8d3ef04c-dddb-426d-b8ba-19181528b8a4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
