### ISSUE TITLE
Feat:Add new method scrape_certification_courses() in Internshala class

### ISSUE THREAD

**Issue by Nishitbaria** [Clueless-Community/scrape-up#560]
### Describe the feature

Description:

Currently, there is no method available in the Internshala class to scrape certification courses from the website. To make it easier for users to extract certification course details, I propose adding a new method called `scrape_certification_courses()` in the Internshala class.

Usage:

```python
url = "https://internshala.com/"
certification_courses = scrape_certification_courses(url)
response_data = json.dumps(certification_courses, indent=4)
print(response_data)
```

The `scrape_certification_courses()` method will take a URL as input and return a JSON array containing the details of valid certification courses found on the page. It will use web scraping techniques with the help of the BeautifulSoup library to parse the HTML content and extract relevant information about each certification course.

By adding this new method, developers using the Internshala class will be able to easily access certification course data and use it for various purposes, such as displaying the information on their website, performing analysis, or storing it in a database.

Implementation Details:

The `scrape_certification_courses()` method can be implemented as follows:
1. Use the `requests` library to make a GET request to the provided URL and fetch the HTML content of the page.
2. Use BeautifulSoup to parse the HTML content and search for the div containing certification courses.
3. Iterate through the certification cards and extract details such as title, duration, rating, learners count, and link for each course.
4. Filter out any cards with missing or incomplete information (e.g., missing title, duration, etc.).
5. Return the valid certification course details as a JSON array.

This new method will be a valuable addition to the Internshala class, enhancing its functionality and usability for developers.

Note: Before implementing the new method, we should ensure that it adheres to Internshala's terms of service and doesn't violate any scraping policies. Additionally, we should handle any potential changes in the website's HTML structure to maintain the stability of the method.

Let me know if you have any questions or need further information.

Thank you for considering this enhancement to the Internshala class!

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85815172/6fe7341e-5472-446c-b7e2-20f8f5eb182d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by Nishitbaria** [comment]
@nikhil25803 ,please assign me this issue ,i wil create pull request asap

**Comment by nikhil25803** [comment]
Go ahead @Nishitbaria 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
