### ISSUE TITLE
Feat: Adding Pixaby Image scraper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#561]
### Describe the feature

I'd implement an image scraper which would be able to scrape any image from the Pixaby (open-image website). The users would also be able to download the image directly from the scraper class through using relevant functions. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-25 at 10 25 01 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/7ac7e6fa-d4ca-4b33-8502-0819efbda64b">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @jaivsh 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
