### ISSUE TITLE
Feat: Forbes Billionaires list scraper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#562]
### Describe the feature

I'd implement a class ```Billionaires``` which would scrape all the data about top 2000 billionaires in Forbes list. It would be helpful to retrive any relevant information about Billionaires, including info about their history, their revenue sources, businesses, and so on. It would also have functions to scrape data about a particular billionaire from Sources like wikipedia, which would allow users to get maximum information about any billionaire on the planet through this class. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-25 at 10 45 31 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/a715e3d4-b6c4-4578-aafa-91ab5c51b5ad">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this!

**Comment by nikhil25803** [comment]
Go ahead @jaivsh 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check whether the module you want to add already exists. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
