### ISSUE TITLE
Feat: Huffington Post Web Scraper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#563]
### Describe the feature

I'd implement a web scraper class which would scrape data from Huffington post news website. It would scrape by date(latest articles), country/continent, and so on. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-25 at 10 52 38 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/3502fb02-605b-40af-880d-e2975975978c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this!

**Comment by nikhil25803** [comment]
We do not need to go that specific, we already do have new scrapers.
