### ISSUE TITLE
Feat: Google News Sceaper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#564]
### Describe the feature

I'd implement a Google news scraper class, which would scrape news info from the GNews website. It would have several helpful functions such as 
- sorting news by start date and end date.
- sorting news by country and continent
- getting top news, full articles, and so on.

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-25 at 10 58 25 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/a9f1e4e4-8dd3-4468-a364-fdf5aec1d2db">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this!

**Comment by nikhil25803** [comment]
we already have it @jaivsh | Check if you can add any methods on the top of it else close the issue.

**Comment by jaivsh** [comment]
okay, I'd add important methods in this project @nikhil25803

**Comment by nikhil25803** [comment]
Add your method on top of the class already built, do not add new class/file in the project.

**Comment by jaivsh** [comment]
> Add your method on top of the class already built, do not add new class/file in the project.

Okay, as you say. I'd add all these search enhancement methods in the previously created class itself. @nikhil25803

**Comment by jaivsh** [comment]
@nikhil25803 please assign!

**Comment by nikhil25803** [comment]
Go ahead @jaivsh 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
