### ISSUE TITLE
Feat: Adding a Job Detail Method in TimesJobs

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Clueless-Community/scrape-up#568]
### Describe the feature

I will be adding a scraper method to scrape Jobs Description in the existing Times JJobs Module

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85278243/2c9c99f8-49b1-4a0f-9fd7-8e7948bcc3d0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Swapnil-Singh-99 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
