### ISSUE TITLE
Feat: Scrap tmdb webpage 

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#571]
### Describe the feature

Scrapping popular movies from the TMDB webpage

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/4bc39f56-380d-4878-96c4-b1e0b2ddb7fb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
We already have IMDB, do not need one more module covering same domain,

**Comment by Juhibhojani** [comment]
Scrap movie news from IMDB 
![Screenshot_2023-07-26-15-09-16-24_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Clueless-Community/scrape-up/assets/89679280/d0ceeda8-14d9-4a2e-a119-be63491ae0f5)

**Comment by nikhil25803** [comment]
we already do have a `IMDB` class @Juhibhojani | Check if you can add some methods.

**Comment by Juhibhojani** [comment]
Okay, I am closing this issue and opening another for the same
