### ISSUE TITLE
Feat: adding a new feature to the imdb scraper

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#572]
### Describe the feature

Hi @nikhil25803 

I am a GSSoC '23 contributor. I would like to add a new feature to the imdb scraper. Given a movie it will scrape and recommend similar movies that may be of interest to the viewer.

Please assign this issue to me.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/1aaea8fa-de6f-4c25-bf89-5c09615ace5c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
