### ISSUE TITLE
Feat: Data scrap from flipkart for printers

### ISSUE THREAD

**Issue by Sushilverma002** [Clueless-Community/scrape-up#574]
### Describe the feature

Data scrap from flipkart for printers

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/114687502/320a72b7-ed15-4498-9629-f1c4920dcf2d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Sushilverma002 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
