### ISSUE TITLE
Feat: IMDB search by actor

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#578]
### Describe the feature

Hi @nikhil25803, 

A new functionality can be added in the imdb scraper, searching by the name of the actor and scraping the movies by them.

I am a GSSoC '23 contributor, kindly assign this issue to me.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/3519825e-130a-4dd0-8362-5bafc76332ef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices as well as cloud platforms.
+ Before making any changes, check if the module you want to add already exists or not. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
