### ISSUE TITLE
Feat: Devpost Hackathon Scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#580]
### Describe the feature

To scrape the hackathons available in Devpost website and retrieve every details 

### Add ScreenShots

![devpost](https://github.com/Clueless-Community/scrape-up/assets/42113027/25ba0a10-fa86-4fac-b787-0018dc72e18c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices and cloud platforms.
+ Before you make any changes, please check whether the module you want to add already exists. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
