### ISSUE TITLE
Feat: Dribble Designs Scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#581]
### Describe the feature

To scrape the illustrations present in Dribble website and retrieve all the data

### Add ScreenShots

![dribble](https://github.com/Clueless-Community/scrape-up/assets/42113027/5d5556ff-fe2c-40ce-9f70-1f15cd0491af)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is not compatible with all devices and cloud platforms.
+ Before you make any changes, please check whether the module you want to add already exists. If yes, then add your functionality as a method only else make a separate module and class for it.

All the best 👨‍💻
