### ISSUE TITLE
Feat: Unstop website scraper

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#582]
### Describe the feature

To scrape the unstop website for hackathons, jobs, internships, hiring challenges, quizzes, competitions, etc. and retrieve all the details

### Add ScreenShots

![unstop_competitions](https://github.com/Clueless-Community/scrape-up/assets/42113027/d6b3b3db-54e6-41d3-8363-46aebc0e646e)
![unstop_hackathons](https://github.com/Clueless-Community/scrape-up/assets/42113027/b41d04e1-eaba-4672-b032-70da3df3e12e)
![unstop_hiringChallenges](https://github.com/Clueless-Community/scrape-up/assets/42113027/a2d748c6-243b-42f5-9442-28cda79f402c)
![unstop_intenship](https://github.com/Clueless-Community/scrape-up/assets/42113027/e15da228-7306-4c13-bcbc-9e56149702e5)
![unstop_jobs](https://github.com/Clueless-Community/scrape-up/assets/42113027/8a564571-8a16-4da6-bb1f-43c99b97c0e3)
![unstop_quiz](https://github.com/Clueless-Community/scrape-up/assets/42113027/7cbe0d43-c290-40b5-a2b9-fcca6e8ab98c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
I do no think, we need to go that specific as we have separate modules to cover what unstops provide.
