### ISSUE TITLE
Feat: Scraoing Nykaa Product Page

### ISSUE THREAD

**Issue by alwenpy** [Clueless-Community/scrape-up#587]
### Describe the feature

Using `bs4` Scrape the product page of Nykaa

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/94129388/6224b8a0-b917-4e25-b97e-8e9966d62a7b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
We already have modules to cover e-commerce stuffs, do not need to go specific.
