### ISSUE TITLE
Feat: TripAdvisor Scrapper

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#591]
### Describe the feature

Fetching details regarding the hotel as per the URL

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/592d6b3d-a21e-4b98-9964-e3a70c6412f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
