### ISSUE TITLE
Feat: WHO scrapper

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#597]
### Describe the feature

Scrapping information from the World Health Organization webpage.  Information like Disease Outbreak News (DONs) or Health topics. 

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/4be11584-f8f0-4115-bcbc-6e480b32f4eb)
![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/e1f7f8ea-fded-41bf-888c-086acd785ee3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by Juhibhojani** [comment]
Hi, @nikhil25803  Please let me know which type of information should i scrap or both of those above mentioned!

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
