### ISSUE TITLE
Feat: add bugmenot.com scrapper

### ISSUE THREAD

**Issue by hashfx** [Clueless-Community/scrape-up#598]
### Describe the feature

bugmenot.com is a website that provides login credentials so that you need not to create a new account every time you visit a website. The main purpose of bugmenot.com is to provide a convenient way for users to bypass registration or subscription requirements on websites, especially when users only need temporary access or do not want to share their personal information. It allows users to find and use publicly available login credentials shared by others.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/69109482/3a51a6f3-3c4c-4f3b-a7cb-dee839f255c6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @hashfx 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
