### ISSUE TITLE
DOC: Adding a socials section and badges to that section in the readme

### ISSUE THREAD

**Issue by 1Shubham7** [Clueless-Community/scrape-up#599]
### What's wrong with the existing documentation

We should have a socials section in the readme. Example -

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/be1693e2-2172-4b6a-9237-810d7082600e)

This would help you improve your project react and your social media profile as well.

### Add ScreenShots

added above

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by nikhil25803** [comment]
This repo is a part of Clueless Community @1Shubham7 | Where we already have mentioned social links. 
We do not need to add this now.
