### ISSUE TITLE
Make an issue and PR template for this repository.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#6]
We need to make an issue and pull a request template for this project. Here are a few things which we need to include 

### Issue template
+ What method and you want to include?
+ To what class it belongs?

### PR Templates
+ Some checkpoints
  + Have you followed the code convention?
  + Have you included the method/function in the `documentation.md` file?

----

This is just a brief, you can include relevant points on your own. But please **do not** dump any random template. Keep it short and precise.

**Comment by codingis4noobs2** [comment]
Hello @nikhil25803 , I want to work on this issue under JWOC 🚀

**Comment by nikhil25803** [comment]
Go ahead @codingis4noobs2.
