### ISSUE TITLE
Feat: scrape data of Boat smartwatch from 'Flipkart' [Gssoc'23]

### ISSUE THREAD

**Issue by kanishkasah20** [Clueless-Community/scrape-up#602]
### Describe the feature

 I will do scraping of boat product data from flipkart which consists of product name , prize , reviews , description using try and catch method for scraping.
Under the label of GSSOC'23 allow me to scrape flipkart.

### Add ScreenShots

<img width="732" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/1c0b435a-350e-4d6f-af2a-e3633e8526d4">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
@kanishkasah20 |
We do not need to go brand specific. Work on some generalized functions/methods. Like scraping watches in general instead of a specific brand.
