### ISSUE TITLE
Feat: Data Scraping of flipkart electronic product 

### ISSUE THREAD

**Issue by kanishkasah20** [Clueless-Community/scrape-up#603]
### Describe the feature

Scrape data of different electronics products (AC, refrigerator) from flipkart using try and catch method.

### Add ScreenShots

<img width="696" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/44ef6fd8-1475-41f8-a02c-7e4e5775016f">
<img width="706" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/f4c7c05a-586c-41c0-ac31-f62d60d92aa0">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
You can add methods for ACs and refrigerators(only if they does not exists already).
