### ISSUE TITLE
Feat: Adding Today's featured article to Wikipedia Module

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#608]
### Describe the feature

I would like to add today's feature article from the Wikipedia page

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/9038ae4a-48e4-472a-b34b-504e3467756e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
