### ISSUE TITLE
Feat: Adding women player and team rankings in ICC module

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#609]
### Describe the feature

I would like to add women's player and team rankings to ICC module

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/e1ee21e5-ea09-49a7-b62d-8004e86979a1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
