### ISSUE TITLE
Feat: Scraping money control

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#610]
### Describe the feature

Hi @nikhil25803 

we can scrape money control to get stocks that are driving the Sensex and the Nifty up or down.

I am a GSSoC '23 contributor, please assign this issue to me.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/d8afd546-7b46-4076-a967-40e4edeb55e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
