### ISSUE TITLE
Feat: Scraping gold rates from money control

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#611]
### Describe the feature

Hi @nikhil25803 

We can scrape gold rates city-wise from moneycontrol

I am a GSSoC '23 contributor, please assign this issue to me.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/15ab4346-8115-4da0-8ae9-adbdae8e8e91)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek |
