### ISSUE TITLE
Feat: Scraping Best shows from RottenTomatoes

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#617]
### Describe the feature

Adding best_shows method in rotten tomatoes class

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/cf81332b-4b20-4c3b-9a19-fe6bbed344b8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
