### ISSUE TITLE
Feat: Scrape indeed.com

### ISSUE THREAD

**Issue by WhoIsJayD** [Clueless-Community/scrape-up#618]
### Describe the feature

It will scrape the job listing from the site

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/88286024/6f313da4-756a-4de7-bb68-5b42952e8ad7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @WhoIsJayD 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
