### ISSUE TITLE
BUG: Movie details method in Rotten Tomatoes isn't working

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The movie details method in rotten tomatoes isn't working. I would like to work on it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani |

**Comment by Juhibhojani** [comment]
Can I add the change in the pull request same as one adding best_shows() method to rotten tomatoes

**Comment by Juhibhojani** [comment]
The change wasn't significant, i am closing this issue and making changes in the previous issue only (Pull request 621)
