### ISSUE TITLE
Feat: Adding method in eBay 

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#623]
### Describe the feature

I would like to scrap deals in particular sectors such as tech or fashion

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/eebb9ab2-fcaa-4943-a2e0-afdcdb01eabe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
I do not think, this will add much value. Also we have modules covering the same.
