### ISSUE TITLE
Feat: Scrape ESPN website for Football

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#632]
### Describe the feature

I would like to scrap ESPN webpage

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/16217810-9329-43ad-9e1c-28a3443760a2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani
