### ISSUE TITLE
Feat: Scrape Inshorts

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#634]
### Describe the feature

Inshorts is a news feed website that gives a small summary about headlines. I would like to add a module to scrape Inshorts.

I am a GSSoC '23 contributor, please assign this issue to me

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/dd6fad47-8aaf-4f81-b005-f2d7604404dd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
I do not think it adds much value, leave it for now.

It is not covering something which we haven't done yet.
