### ISSUE TITLE
Feat: Top gainer and loser stocks

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#643]
### Describe the feature

We can scrape moneycontrol to get the top gainers and losers in stocks for a day.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/c79a0012-2ca6-444e-8e8b-47d5d0b4b943)

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/3869e6a7-0acf-40de-9e5c-4d8ea5935125)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek
