### ISSUE TITLE
Feat: Scraping details of each city from timeanddate.com

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#652]
### Describe the feature

From a given city name we can scrape the country, currency, latitude and logitude, time and weather of the city.

Hi @nikhil25803 
I am a GSSoC '23 contributor, please assign this issue to me.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/bb294d46-3cb4-4968-bf21-c5e73d808e97)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
