### ISSUE TITLE
Feat: Improve GitHub scraper get_insights() function

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#654]
### Describe the feature

Improve the get_insights() function for scraping data for different periods: 24 hours, 3 days, 1 week, 1 month

### Add ScreenShots

![githubInsights_periods](https://github.com/Clueless-Community/scrape-up/assets/42113027/42d39778-1ed7-4601-ad65-58ff89f37842)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Mihan786Chistie |
