### ISSUE TITLE
Feat: Adding NDTV News Scraper

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Clueless-Community/scrape-up#660]
### Describe the feature

I will be adding a NDTV News Scraper that will scrape news using URL

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85278243/7c89bd6f-5300-46be-8a84-7ad1a2a4350f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
I guess the Hindu newspaper module will cover most of the things.
