### ISSUE TITLE
Feat: Stocks at 52 week high and low

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#662]
### Describe the feature

moneycontrol can be scraped to get the stocks at a 52 week high and low

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/5f67a7b6-33a2-4771-98d0-2032fcb25890)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek
