### ISSUE TITLE
Feat: Crypto currency prices from coinmarketcap.com

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#663]
### Describe the feature

coinmarketcap.com can be scraped to get crypto currency prices.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/af7558f9-0269-4e1b-b888-9ac9bf21ed20)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
