### ISSUE TITLE
Feat: Flipkart laptop details Scaper

### ISSUE THREAD

**Issue by filza2112** [Clueless-Community/scrape-up#664]
### Describe the feature

* I will add a scaper to fetch the laptop details available on Flipkart
* I will follow the contributor's guide
* I will upload documentation for the same

### Add ScreenShots

<img width="960" alt="flipkart" src="https://github.com/Clueless-Community/scrape-up/assets/115334313/16bb8065-0282-4b49-925f-aeda7668f1c9">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @filza2112 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
