### ISSUE TITLE
Feat: scrape hackathon website  devfolio [Gssoc'23]

### ISSUE THREAD

**Issue by kanishkasah20** [Clueless-Community/scrape-up#665]
### Describe the feature

I will do scraping data of upcoming hackathons from devfolio website

### Add ScreenShots

<img width="667" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/6c84f5ab-3515-455d-821e-d52ce7625ed9">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @kanishkasah20 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
