### ISSUE TITLE
Feat: Data scraping of new product (Flipkart)

### ISSUE THREAD

**Issue by kanishkasah20** [Clueless-Community/scrape-up#666]
### Describe the feature

I will scrape data and  add new methods of different products from flipkart.

### Add ScreenShots

<img width="908" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/4653f20b-9cf6-4479-8fce-d63e9bcbe1b9">
<img width="944" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/114860158/be1bd4ce-19c6-4caa-b12d-d39ca99f2f56">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
We are not covering all the items listed on Flipkart or any e-commerce platform. It is endless, can't cover them all.

Not looking forward to expanding the e-commerce module, so closing this for now.
