### ISSUE TITLE
Feat: Scrap Cartrade.com

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#669]
### Describe the feature

I would like to scrap cars under a given amount from cartrade.com

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/09fb7712-52fb-47a3-8bf1-04427c6cd08e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
I don't think it will add much value.

Closing this for now...
