### ISSUE TITLE
Feat: Important events in History in timeanddate.com

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#673]
### Describe the feature

timeanddate.com can be scraped to find the important events that happened on history on a specific day.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/b9c6be9d-9b9f-4d12-a5c9-5f4dc9730bee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek |
