### ISSUE TITLE
Feat: Scrap coinmarketcap

### ISSUE THREAD

**Issue by Juhibhojani** [Clueless-Community/scrape-up#674]
### Describe the feature

Scrap cryptocurrency information 

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/89679280/995b20bd-e01c-47b8-afd0-0f2c949b192d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Juhibhojani |
