### ISSUE TITLE
Feat: Navbar Items Hover Effect Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [Clueless-Community/scrape-up#690]
### Describe the feature

The current hover effect on the items of navbar only includes the underline which is not adding much value to the overall design.

### Add ScreenShots

_Current Design_

![i (1)](https://github.com/Clueless-Community/scrape-up/assets/115794049/8de1fbfc-c2b7-402b-bd04-ab79d68859a3)

_Expected Updated Design_

![i (2)](https://github.com/Clueless-Community/scrape-up/assets/115794049/14a368d5-ecf7-4bf3-ade8-af37d8b28a50)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
What 😂😂😂

Are you new to Python?? We do not own the Pypi website that you are suggesting making changes to. It is a public repository for Python packages where all the packages are deployed and installed, even our project. So the issue you raised is irrelevant, do some research next time while raising an issue.
