### ISSUE TITLE
Feat: Current Top Box Office charts

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/scrape-up#692]
### Describe the feature

scraping the movies with current highest box office charts and related information.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/116893588/5bf920d4-972d-43bc-a51b-c2d63cfd2846)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @DyuthiVivek 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
