### ISSUE TITLE
Feat: Yelp web scraper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#706]
### Describe the feature

Yelp is one of the most popular websites in the world which offer food delivery, household daily-chore and construction jobs, and so on. 
I'd create a web scraper of the aforementioned website. The users would be able to view the latest deals based on their location preferences and other inputs proided to get the desired results.

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-08-08 at 4 21 03 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/01cb7a5b-0d70-424f-a295-7bdfef6b2660">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this

**Comment by nikhil25803** [comment]
I do not think this will add much value.
