### ISSUE TITLE
Feat: Pinterest web scraper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#707]
### Describe the feature

I'd add a web-scraper for the pinterest website, which would return the numpy images scraped for a particular query from the pinterest website.

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-08-08 at 4 25 48 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/5abf70b5-331b-4fd0-ab58-504197b1d71e">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this

**Comment by nikhil25803** [comment]
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
