### ISSUE TITLE
Housing.com web scraper

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#708]
### Describe the feature

I'd add a web scraper for housing.com website, which is one of the most popular property listing websites of India. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-08-08 at 4 31 32 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/635d0032-0e09-4e35-904f-9263e7208f2c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this

**Comment by nikhil25803** [comment]
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
