### ISSUE TITLE
Name of the user opened an issue.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#71]
## Proposed Method: 
`.opened_by()`

### Description
Get the name of the user who opened the particular issue.

## To what class it belongs?: 
`Issue`

### Make changes at
`src/scrape_up/github/issue.py`

**Comment by vhadzhiev** [comment]
Can I get the assignment?

**Comment by nikhil25803** [comment]
Sure, go ahead :))
