### ISSUE TITLE
Feat: Scraping the QS World university ranking website

### ISSUE THREAD

**Issue by jaivsh** [Clueless-Community/scrape-up#710]
### Describe the feature

I'd design a web scraper that would return the list and details of top universities by their rankings. The users would also be able to search for rankings of specific universities by subject, region, or cities. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-08-08 at 8 07 07 PM" src="https://github.com/Clueless-Community/scrape-up/assets/93859359/5adc0a50-cb6f-4940-8602-2c50f1f51d4b">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
@nikhil25803 please assign me this

**Comment by nikhil25803** [comment]
They have different parameters of ranking universities, it is not a official organization like NIRF in India. 

Closing this PR for now.
