### ISSUE TITLE
BUG:  Inconsistent indentation and incomplete method signature in the provided code for the tshirts_by_price_range method within the FlipkartClothing class, along with potential exception handling and method invocation concerns.

### ISSUE THREAD

**Issue by tamannaaaaa** [Clueless-Community/scrape-up#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The code snippet lacks consistent indentation, making it unclear whether it's meant to be a method within the FlipkartClothing class. Additionally, the method signature is incomplete, missing the required self parameter. Exception handling is overly broad, catching all exceptions instead of specific ones, leading to potentially hidden errors. Moreover, the tshirts method is invoked, but its implementation is not provided. The URL construction can be improved using f-strings for better readability, and the return values for exceptions could be more informative for debugging purposes.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @tamannaaaaa |
