### ISSUE TITLE
Get the list of assignees assigned in an issue.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#72]
## Proposed Method: 
`.assignees()`

### Description
Returns a list of users, who are assigned to an issue. Else returns an empty list.
 
## To what class it belongs?: 
`Issue`

### Make changes at
`src/scrape_up/github/issue.py`

**Comment by PalaVenkiReddy** [comment]
Please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Go ahead @PalaVenkiReddy
