### ISSUE TITLE
Inadequate Exception Handling

### ISSUE THREAD

**Issue by Shiivvani** [Clueless-Community/scrape-up#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The code employs a generic except block for error handling during the HTTP request and JSON parsing processes. This approach makes it difficult to accurately diagnose and manage specific issues that may arise. It's advisable to implement targeted exception handling to precisely identify errors, aiding in effective troubleshooting and resolution.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Which module you are going to cover first, to implement these changes? Specify that as well/

**Comment by Shiivvani** [comment]
In the billionaires.py module

**Comment by nikhil25803** [comment]
Go ahead @Shiivvani |
