### ISSUE TITLE
Labels given to a particular issue.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#73]
## Proposed Method: 
`.labels()`

### Description
Returns a list of labels given to an issue.

![image](https://user-images.githubusercontent.com/93156825/219954927-88c9e76f-326c-4ea6-9899-da6099e9c788.png)

## To what class it belongs?: 
`Issue`

### Make changes at
`src/scrape_up/github/issue.py`

**Comment by Sar-thak-3** [comment]
Kindly assign it to me under JWOC

**Comment by nikhil25803** [comment]
Go ahead @Sar-thak-3 :))
