### ISSUE TITLE
Feat: Update Copyright Year Dynamically After DOM Load

### ISSUE THREAD

**Issue by tamannaaaaa** [Clueless-Community/scrape-up#734]
### Describe the feature

The current code attempts to dynamically update the copyright year on a web page using JavaScript. However, there is an issue related to the timing of script execution and the DOM content loading. To ensure accurate execution and prevent potential errors, the code needs to be modified to run after the DOM has been fully loaded.

### Add ScreenShots

Not applicable

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
We do not have any involvement in JS and DOM-related stuff, what change you are actually trying to make please explain?

**Comment by tamannaaaaa** [comment]
In the updated code, I've just added an event listener to the DOMContentLoaded event. This ensures that the JavaScript code only executes once the entire DOM has finished loading. This change is crucial to prevent potential errors and ensure that the JavaScript interacts with the fully loaded HTML content.I'm not making changes to your code directly, but I'm providing you with  how to improve the code.

**Comment by nikhil25803** [comment]
Share the screenshot, where you have found this issue. 

There is not even a single line of JS involve in this project.

**Comment by tamannaaaaa** [comment]
I'm so soory I think I think I just raised the issue of some other project in this project's issue section. I'm sorry for taking your time. I will just close this issue. Thank you for cooperating.
