### ISSUE TITLE
Time when the issue was open.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#74]
## Proposed Method: 
`.opened_at()`

### Description
Returns a string containing the time range when the issue was opened, like "yesterday", "last week", etc.

You can find this at 
![image](https://user-images.githubusercontent.com/93156825/219955126-2482c6fd-7b58-4891-b2ce-f043a0dd25f7.png)

 
## To what class it belongs?: 
`Issue`

### Make changes at
`src/scrape_up/github/issue.py`

**Comment by Sar-thak-3** [comment]
Kindly assign it to me under JWOC

**Comment by nikhil25803** [comment]
One issue at a time @Sar-thak-3

**Comment by Rubyseher** [comment]
I am interested to fix this issue , I am participating under JWOC. Can you assign me this issue?

**Comment by nikhil25803** [comment]
Go ahead @Rubyseher
