### ISSUE TITLE
BUG: Unable to import Github

### ISSUE THREAD

**Issue by Mehak2511** [Clueless-Community/scrape-up#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The code : from scrape_up import GitHub

ImportError: cannot import name 'GitHub' from 'scrape_up'

Not sure what im doing wrong here when scrape-up has been installed successfully 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC 23 contributor
- [ ] I want to work on this issue

**Comment by nikhil25803** [comment]
Import is working fine for me

![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/d899fabb-64a4-440a-a125-661fd4bf7756)

**Comment by metflekx** [comment]
Hey, can you please share your code or try to reproduce the error.

**Comment by nikhil25803** [comment]
It is mentioned in `contribution.md` file.

**Comment by metflekx** [comment]
i meant to reply to @Mehak2511

**Comment by metflekx** [comment]
Hey, can you please share your file structure . like with commands 'tree' or 'find'.

**Comment by metflekx** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The code : from scrape_up import GitHub
> 
> ImportError: cannot import name 'GitHub' from 'scrape_up'
> 
> Not sure what im doing wrong here when scrape-up has been installed successfully
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I'm a GSSOC 23 contributor
> * [ ]  I want to work on this issue

Hey, can you please share your file structure . like with commands 'tree' or 'find'.

**Comment by Mehak2511** [comment]
![Uploading Screenshot 2023-08-16 at 8.48.45 pm.png…]()

**Comment by Mehak2511** [comment]
<img width="1066" alt="Screenshot 2023-08-16 at 8 48 45 pm" src="https://github.com/Clueless-Community/scrape-up/assets/66304164/8ac22f20-b6ae-4403-9430-8343f486dca1">

**Comment by metflekx** [comment]
@Mehak2511 

try lowercase.

from scrape_up import github

**Comment by Mehak2511** [comment]
Worked. Thank you!
