### ISSUE TITLE
Feat:Better architecture for Wikipedia module.

### ISSUE THREAD

**Issue by metflekx** [Clueless-Community/scrape-up#748]
hi, shall we go ahead and rewrite this scrape() method.
<img width="457" alt="Screenshot 2023-08-17 at 20 19 37" src="https://github.com/Clueless-Community/scrape-up/assets/106245122/2f569d1b-1806-439c-b0c9-dd1b438e0360">

so that once instance of the Wikipedia class is created it takes the query as an argument, then constructor will store a soup in a private variable to be accessed from within the class.
take this main driver as expected output.

```python
if __name__ == "__main__":
    dog_wiki = WikipediaScraper("dog")
```

this instance dog_wiki will now have a soup object inside : 
```python
def __init__(self, query):
    self.soup = self.scrape(query)
```

then we could start adding methods.

**Comment by nikhil25803** [comment]
Sounds good, go ahead.
