### ISSUE TITLE
Codeforces module isn't working properly.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#751]
The code-forces module isn't working properly and throwing errors on a run. 

You can locate the files at `/src/scrape-up/codeforces/user.py`

**Comment by parag477** [comment]
Hey can you please assign this issue to me.

**Comment by lazyMonk1010** [comment]
hey @nikhil25803 i want to work on this issue ,please do assign me this

**Comment by nikhil25803** [comment]
Hey @parag477, look for some other issues raised or you can raise one if you want to add a new feature or fix a bug.

**Comment by lazyMonk1010** [comment]
@nikhil25803 please check it ! I've solved the issue

**Comment by jaskirat0001** [comment]
hey @nikhil25803 can you assign me this task
