### ISSUE TITLE
Refactor Dev community module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#774]
**Note**
- Currently, the dev community module is working fine but still needs some changes, which are
    - Formatting the response (the response of the methods does contain characters like `"#neo4j\#python\#datascience\#gis"`). Needs to remove `\#` like characters using regex or any other method.
    - Format docstring, for now, it is a bit messed up. Format it properly as well.
    - Test all the methods.

Reference :

https://github.com/Clueless-Community/scrape-up/blob/bd8d87e786293e0ab38ff81ef1e5581fce8e44a7/src/scrape_up/devCommunity/articles.py#L47

**Comment by VividhPandey003** [comment]
Hey, I would like to contribute to this issue. As I am getting the idea of it, we might be using the sub() fn for this. If I get any further doubts, I hope we can work it out.
Thanks

**Comment by nikhil25803** [comment]
Go ahead @VividhPandey003.

Hey @lazyMonk1010, as he asked first so assigning the issue to him. Look for other issues raised or you can raise the same accordingly.

**Comment by VividhPandey003** [comment]
update: still working on it

**Comment by BraxtonElmer** [comment]
Can i be assigned to work on this?

**Comment by nikhil25803** [comment]
Go ahead @BraxtonElmer, make sure you go through all the instructions and comments for this PR. So that you do not repeat the same.

All the best :))
