### ISSUE TITLE
Remove selenium dependency in Devpost module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#778]
The `get_hackathon` methods of the `Devpost` module are dependent on `Selenium` /`ChromeDriver` now, try implementing this using  `BeautifulSoup`. 

- Reference 

https://github.com/Clueless-Community/scrape-up/blob/5def48e11ce34278e1c1d08284f7139fdfa8f43c/src/scrape_up/devpost/devpost.py#L113C9-L113C23

**Comment by iMarble** [comment]
Hi @nikhil25803 , can you assign this to me!

**Comment by nikhil25803** [comment]
Go ahead @iMarble 


All the best 👨‍💻
