### ISSUE TITLE
Test and document finance module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#782]
**Task**
- Test all the methods of the module `finance`, (relative path is `src/scrape_up/finance` ).
- Add docstring to each class and module of the module (can take reference from other published modules like github or Flipkart).
- Test all the methods by running the program and later remove all the print statements from the code.

**Comment by ayan-joshi** [comment]
Can u assign me this issue @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @nikhil25803 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
