### ISSUE TITLE
Feat:Workflow Run to check code formatting

### ISSUE THREAD

**Issue by MannuVilasara** [Clueless-Community/scrape-up#787]
### Describe the feature

Please assign me this under hacktoberfest.

Will be adding CI/CD workflow to check formatting of the code.

### Add ScreenShots

Here's example:
- not formatted code.
![unsuccess](https://github.com/Bulkmailer/BulkMailer-Backend/assets/117009138/ad00dcb0-72bb-4a25-b191-85e1c7b537d5)
- formatted code
![success](https://github.com/Bulkmailer/BulkMailer-Backend/assets/117009138/c9c63dcb-035f-4dc6-a828-d1916e3867d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @MannuVilasara :))
