### ISSUE TITLE
DevPost module documentation update in dev-documentation

### ISSUE THREAD

**Issue by iMarble** [Clueless-Community/scrape-up#788]
### What's wrong with the existing documentation

All methods of DevPost module are not listed in the dev-documentation.

• Reference

https://github.com/Clueless-Community/scrape-up/blob/main/dev-documentation.md#L768

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by iMarble** [comment]
Hi @nikhil25803, can you please assign this to me under hactoberfest tag.

**Comment by nikhil25803** [comment]
Go ahead @iMarble !!

All the best !
