### ISSUE TITLE
Scrape the list of issues in a particular repository

### ISSUE THREAD

**Issue by pooranjoyb** [Clueless-Community/scrape-up#79]
### Description
Scrape the list of issues open in a repository.

### Example Usage
```python
from scrape_up import github
repo =  github.Repository(username="Clueless-Community", repository="scrape-up")
print(repo.get_issues())
```
### Output :
Returns a list of all open issues in the repository.

### Hey @nikhil25803 I would like to work in this issue under DWOC '23 :) 👍

**Comment by nikhil25803** [comment]
Sounds good. But add this in `Repository` class.

**Comment by pooranjoyb** [comment]
Ok Brother, I'll add this to Repository class :) @nikhil25803 
Thanks for assigning 👍

**Comment by pooranjoyb** [comment]
Hey @nikhil25803 I just wanted to ask that if you want me to scrape closed issues too or open issues will work as of now?

**Comment by nikhil25803** [comment]
Only opened issue @pooranjoyb

**Comment by pooranjoyb** [comment]
> Only opened issue @pooranjoyb  

Ok, thanks
