### ISSUE TITLE
BUG:many modules of this library aren't working eg.: imdb , crckbuzz,  Rankings,Academia,BBC News

### ISSUE THREAD

**Issue by AdityaRaj23** [Clueless-Community/scrape-up#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When importing these libraries from the module they are running into import error I ran them on my pc and on a kaggle notebook and they are running into same error.(I have attached the screenshot of the error.)
<img width="1079" alt="Screenshot 2023-10-08 at 4 51 01 PM" src="https://github.com/Clueless-Community/scrape-up/assets/95625520/9ed71786-7763-4cfc-99ac-2753be3e707a">
<img width="1319" alt="Screenshot 2023-10-08 at 4 51 39 PM" src="https://github.com/Clueless-Community/scrape-up/assets/95625520/6fc49936-544f-4a40-9f93-dfe8f3387e8a">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Because they are not yet on PyPi.
This is not a bug, I will update the package on 15th October.
