### ISSUE TITLE
BUG: github pul_request() not working

### ISSUE THREAD

**Issue by kritserv** [Clueless-Community/scrape-up#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was trying to use the `user.pul_request()` function from github, it fail and it seems like the function does not exist in the source code. Could you please look into this? It would be great if this function could be added or if there is an alternative way to achieve the same functionality.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @kritserv , fix it :))

**Comment by samejima-san** [comment]
This method shouldn't be on the User class ``` | `.pul_requests()`   | Return the number of pull requests opened in a repository. ``` it is documented to return pull requests from a repository and there currently is no method ``` .pul_requests()``` on that class.

There is a ``` .pull_request()``` method on the repository class, so this is more of a documentation error and it should be removed from the docs.
