### ISSUE TITLE
Add test file for GitHub module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#804]
**Note**
- Test all the methods of the `github` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by SWAYAMKHANDURI** [comment]
I would love to work on the issue

**Comment by nikhil25803** [comment]
Go ahead @SWAYAMKHANDURI 
**Note**
+ Create a separate file for this test, named `github_test.py` file.
+ Make different classes for different classes existing for `github` module.

All the best 👨‍💻

**Comment by SWAYAMKHANDURI** [comment]
alright thanks :relaxed:

**Comment by MrDBC** [comment]
im new to testing
so i would love to see ur work @SWAYAMKHANDURI 

waiting for ur PR👍
