### ISSUE TITLE
Add test files for Hacker News module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#806]
**Note**
- Test all the methods of the `hackernews` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by patHyatt** [comment]
Should the underlying HTTP request be mocked? Or is the intention to send a live request here?

**Comment by Anantu05** [comment]
I would like to work on this issue!

**Comment by Master-Keshav** [comment]
Hi, please assign this to me.

**Comment by shraddha761** [comment]
@nikhil25803 can you please this issue to me

**Comment by nikhil25803** [comment]
Go ahead @shraddha761.
