### ISSUE TITLE
Add test files for HackerEarth module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#807]
**Note**
- Test all the methods of the `hackerearth` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by rsk2** [comment]
Hi @nikhil25803, can I work on this?

**Comment by nikhil25803** [comment]
Go ahead @rsk2
