### ISSUE TITLE
Add test files for Hashnode module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#809]
**Note**
- Test all the methods of the `hashnode` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by ritik48** [comment]
@nikhil25803 Please assign this issue to me.

**Comment by nikhil25803** [comment]
Go ahead @ritik48, all the best 👨‍💻
