### ISSUE TITLE
Add test files for Academia module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#811]
**Note**
- Test all the methods of the `academia` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by Vishal-Padia** [comment]
Would like to work on this!

**Comment by nikhil25803** [comment]
Go ahead @Vishal-Padia :)

**Comment by Vishal-Padia** [comment]
@nikhil25803 Quick question are all papers from academia supposed to have a summary?

**Comment by Vishal-Padia** [comment]
nvm it's working now!

**Comment by nikhil25803** [comment]
I'll into it by tomorrow.

**Comment by Vishal-Padia** [comment]
Okay, and also check the other PR I created!
