### ISSUE TITLE
Add test file for AskUbuntu module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#812]
**Note**
- Test all the methods of the `askubuntu` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by Vishal-Padia** [comment]
Would like to work on this!

**Comment by BraxtonElmer** [comment]
can I be assigned on this?

**Comment by Master-Keshav** [comment]
Hi, please assign this to me.

**Comment by nikhil25803** [comment]
Go ahead @Vishal-Padia
