### ISSUE TITLE
Add test files for CovidInfo module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#815]
**Note**
- Test all the methods of the `covidinfo` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by Master-Keshav** [comment]
Hi, please assign this to me.

**Comment by nikhil25803** [comment]
Go ahead @KathanrDave

**Comment by KathanrDave** [comment]
hey! @nikhil25803 please check the PR created.
