### ISSUE TITLE
Add test files for Cricbuzz file

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#816]
**Note**
- Test all the methods of the `cricbuzz` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by aliat110** [comment]
Can I work upon this @nikhil25803 ?

**Comment by nikhil25803** [comment]
Go ahead @aliat110
