### ISSUE TITLE
Add test files for Dribble module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#817]
**Note**
- Test all the methods of the `dribble` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by Master-Keshav** [comment]
Hi, please assign this to me.

**Comment by biohazard2117** [comment]
@nikhil25803 Can you assign this to me

**Comment by nikhil25803** [comment]
Go ahead @biohazard2117 !
