### ISSUE TITLE
Add test file for EazyDiner module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#818]
**Note**
- Test all the methods of the `eazydiner` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by Master-Keshav** [comment]
Hi, please assign me this issue.

**Comment by nikhil25803** [comment]
Go ahead @Master-Keshav
