### ISSUE TITLE
Add test file for HealthGrades module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#822]
**Note**
- Test all the methods of the `healthgrades` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by AimenYaseen** [comment]
I want to work on this issue... Please give me some more details about it.

**Comment by nikhil25803** [comment]
Go ahead @AimenYaseen :)
