### ISSUE TITLE
Add test file for IMDB module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#823]
**Note**
- Test all the methods of the `imdb` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `codechef_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by burhanharoon** [comment]
Hi @nikhil25803, just to be sure you want unit tests for [this](https://github.com/Clueless-Community/scrape-up/blob/bc50642077727b2d88dc0918ce4ae1a7f22a2bdb/src/scrape_up/imdb/imdb.py#L5) file. Right?

**Comment by Vishal-Padia** [comment]
@nikhil25803  I encountered some errors while running the test case, please look at the issue created.

**Comment by nikhil25803** [comment]
Hey @Vishal-Padia, will check your bug PR only. And guys, @Vishal-Padia and Vishal, do not start working on an issue before getting assigned, it is not an open-source good practice, to assign this issue to @burhanharoon.

**Comment by Vishal-Padia** [comment]
okay, cool!
