### ISSUE TITLE
Feat: Scraping Dictionary.com for the Word of the Day

### ISSUE THREAD

**Issue by swetha3456** [Clueless-Community/scrape-up#841]
### Describe the feature

Users can view the word of the day on Dictionary.com along with the definition, examples, and pronunciation.

### Add ScreenShots

<img width="376" alt="image" src="https://github.com/Clueless-Community/scrape-up/assets/116883043/82227b17-76a4-4123-b55f-0349ac4d5737">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @swetha3456 
**Note**
+ Create a separate module for this, as per the folder and project structure
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can just add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by samejima-san** [comment]
are you still working on this issue @swetha3456? if not i will pick it up

**Comment by swetha3456** [comment]
@samejima-san Yes, I'm working on it, but maybe you could work on other methods for scraping Dictionary.com, such as getting the definition of a word or finding synonyms?
