### ISSUE TITLE
Feat: Auto comment 

### ISSUE THREAD

**Issue by shraddha761** [Clueless-Community/scrape-up#847]
### Describe the feature

There is no auto comment feature while issue is created and assigned and also pr is created

### Add ScreenShots

Assign this issue to me @nikhil25803 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Because whenever a new issue/PR is created, we have to response differently. So I don't think we will be needed it, for now.
