### ISSUE TITLE
Fix the pull request template.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#85]

**Comment by neokd** [comment]
Can u give the description about this issue?

**Comment by nikhil25803** [comment]
One issue at a time @neokd :))

**Comment by neokd** [comment]
Haan Sure was just excited about it :-)

**Comment by nikhil25803** [comment]
When we make a PR, we have to add details about the PR on our own. What if we provide a template prior so that easy for both contributors as well as maintainers?

![image](https://user-images.githubusercontent.com/93156825/220144850-0691204b-4eaf-4d78-9de2-2594a73bb942.png)

**Comment by nikhil25803** [comment]
Once you are done with the issue assigned to you, do let me know. I'll assign you this as well.

**Comment by Priyamakeshwari** [comment]
Can i work on this issue under JWOC?

**Comment by nikhil25803** [comment]
Assigning this issue to @Priyamakeshwari for time being.

**Comment by Priyamakeshwari** [comment]
Thanks bhaiya !
