### ISSUE TITLE
Add test files for GitHub modules.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#852]
**Note**
- Test all the methods of the `github` module and add a test file.
- Add test file in directory `src/test`.
- Check the `github_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by HavokSahil** [comment]
@nikhil25803 I am working on it. Please assign it to me

**Comment by nikhil25803** [comment]
Go ahead @HavokSahil

**Comment by Dhruv127** [comment]
kindly assign me the issue
