### ISSUE TITLE
Add test files for Hackernews module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#853]
**Note**
- Test all the methods of the `hackernews` module and add a test file for the same.
- Add test file in directory `src/test`.
- Check the `hackernews_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by based-baba** [comment]
Hello! I would like to work on this issue as part of Codepeak23.

**Comment by nikhil25803** [comment]
Go ahead @based-baba.
