### ISSUE TITLE
Add test files for Hashnode

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#854]
**Note**
- Test all the methods of the `hashnode` module and add a test file.
- Add test file in directory `src/test`.
- Check the `hashnode.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by I-MirzaBaig** [comment]
can i work on this under codepeak2023

**Comment by nikhil25803** [comment]
Go ahead @I-MirzaBaig

**Comment by Dhruv127** [comment]
kindly assign me the issue

**Comment by Vaibhav-Kumar10** [comment]
If the issue is currently open, please assign this task to me under GSSoC'24.

**Comment by nikhil25803** [comment]
Go ahead @Vaibhav-Kumar10

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by Vaibhav-Kumar10** [comment]
> Go ahead @Vaibhav-Kumar10

Thank You
