### ISSUE TITLE
Add test files for BBC News module

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#855]
**Note**
- Test all the methods of the `bbc` module and add a test file.
- Add test file in directory `src/test`.
- Check the `bbc_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by Dhruv127** [comment]
kindly assign me the issue

**Comment by onkar-1432** [comment]
Can I work on these issue. Please assign it to me I will do my best.

**Comment by lavi20** [comment]
kindly assign me the issue.....

**Comment by Santhosh-Siddhardha** [comment]
I would like to work on this issue. Please assign me this issue "Add test files for BBC News module #855"

**Comment by code-with-aneesh** [comment]
I'm requesting assignment to this issue. I possess experience with Python and a solid understanding of its concepts.

**Comment by nikhil25803** [comment]
Go ahead @Santhosh-Siddhardha.

Hey @code-with-aneesh, as we follow first come first assign rule you may raise some other issue or find one which suits you.

**Comment by code-with-aneesh** [comment]
> Go ahead @Santhosh-Siddhardha.
> 
> Hey @code-with-aneesh, as we follow the first come first assigned rule you may raise some other issue or find one that suits you.

Ok. No Problem 👍

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by Santhosh-Siddhardha** [comment]
@nikhil25803 Thank you
