### ISSUE TITLE
Add test files for Coin Market Cap module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#856]
**Note**
- Test all the methods of the `coinmarketcap` module and add a test file.
- Add test file in directory `src/test`.
- Check the `coinmarketcap_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by based-baba** [comment]
Hello! I would like to work on this issue as part of Codepeak23.

**Comment by nikhil25803** [comment]
Go ahead @based-baba

**Comment by based-baba** [comment]
The `get_top_cryptocurrencies` method of the `coinmarketcap` module does not work as intended. Should I open a new issue for it or include a fix under this issue itself?

**Comment by nikhil25803** [comment]
Yes, that is why I started to make test files for each module. 
Please create a new issue for this, fix it, and then complete this (creating test files).
