### ISSUE TITLE
Add test files for Cricbuzz module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#857]
**Note**
- Test all the methods of the `cricbuzz` module and add a test file.
- Add test file in directory `src/test`.
- Check the `cricbuzz_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by based-baba** [comment]
Hello! I would like to work on this issue as part of Codepeak23.

**Comment by nikhil25803** [comment]
Go ahead @based-baba

**Comment by Dhruv127** [comment]
kindly assign me the issue

**Comment by yashasvini121** [comment]
Hello, I would like to work on this issue as part of GSSoC'24.
