### ISSUE TITLE
Add test file for Ebay module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#859]
**Note**
- Test all the methods of the `ebay` module and add a test file.
- Add test file in directory `src/test`.
- Check the `ebay_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by based-baba** [comment]
Hello! I would like to work on this issue as part of Codepeak23.

**Comment by nikhil25803** [comment]
Go ahead @nikhil25803.
