### ISSUE TITLE
Get title of a pull request.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#86]
## Proposed Method: 
`.title()`

### Description
Get the title of a pull request.

## To what class it belongs?: 
`PullRequest()`

### Note
Add the method in `github/pull_request.py`

**Comment by PalaVenkiReddy** [comment]
Bhaiya please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Go ahead @PalaVenkiReddy :))
