### ISSUE TITLE
Add test files for IMDB module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#860]
**Note**
- Test all the methods of the `imdb` module and add a test file.
- Add test file in directory `src/test`.
- Check the `imdb_test.py` file as a reference to get an idea about structuring the code.
- Use `unittest` only.

**Comment by sharmajyotirmay** [comment]
I would like to work on this as a part of CODEPEAK2023

**Comment by nikhil25803** [comment]
Go ahead @sharmajyotirmay

**Comment by Dhruv127** [comment]
kindly assign me the issue

**Comment by ayushmorbar** [comment]
Hey, I would like to work on this issue as part of GSSoC'24

**Comment by nikhil25803** [comment]
Go ahead @ayushmorbar!

**Comment by ayushmorbar** [comment]
Yeah for sure ‼️

**Comment by KartikRajOfficial** [comment]
Hey @ayushmorbar I would like to work on this issue as part of GSSoC'24

**Comment by shravanasati** [comment]
May I ask why is only the standard unittest library allowed? pytest is much less verbose and simple.

**Comment by nikhil25803** [comment]
Built-in support of Python and more set of assertion methods (can even be customized).
@shravanasati

**Comment by itssiddhantjain** [comment]
Hello @nikhil25803  , please assign this issue to me as I have already worked on this kind of problem in the past.
