### ISSUE TITLE
Files changed in a pull request.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#87]
## Proposed Method: 
`.files_changed()`

### Description
Get the number of files changed in a PR made.

## To what class it belongs?: 
`PullRequest()`

### Note
Add the method in `github/pull_request.py`

**Comment by Priyamakeshwari** [comment]
i would like to contribute to this issue JWOC

**Comment by Priyamakeshwari** [comment]
Hey, I would like to work on this issue under JWOC please assign it to me

**Comment by nikhil25803** [comment]
One issue at a time @Priyamakeshwari.

**Comment by PalaVenkiReddy** [comment]
Please assign this issue to me under JWOC

**Comment by nikhil25803** [comment]
Go ahead @PalaVenkiReddy
