### ISSUE TITLE
Girlscript Summer of Code Introduction/Tracking

### ISSUE THREAD

**Issue by Princegupta101** [Clueless-Community/scrape-up#874]
👋 Hi @Clueless-Community,

I am Prince,web developer Girlscript Summer of Code. I'll be collaborating with you on preparing your repo for GSSoC'24 Program

Why are these changes required?
After Analysing last year's contributions and feedback it would be great for students to have a couple of standard readme files on the repo to understand what the project is all about and some issues detailing what they can contribute. This will help you to see increased engagement in your repository as well.

As mentioned students get a chance to learn step by step, how to build this project as well as invite mentors to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for Girlscript summer of code 2024 on 10th May.

This issue will serve as a tracking issue to track all issues related to GSSoC'24. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch.

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated.

I look forward to working with you :octocat:

- [x] #869 
- [x] #870 
- [x] #871 
- [x] #872 
- [ ] #873

**Comment by vix2704** [comment]
Hello sir ! I'm interested in contributing to this project under Gssoc 2024 program and have relevant skills for it. Kindly assign it to me.

**Comment by guptaakshitaa** [comment]
Greetings, 
I am keen on applying to this project.

**Comment by ridhi-ahuja** [comment]
Hello , as a Contributor in GS'SOC 2024 I am looking forward on working and contributing in this project .
I've developed skills in JAVA , C , Javascript ,Python , WEB development and basic Machine Learning ,currently under Artificial Intelligence training on implementing AI tools ,exploring more in tech.

**Comment by aditi1807** [comment]
Hey,
Could you please assign me this issue.

**Comment by Divyanshi1002** [comment]
hello, 
I am keen to contribute in this project under GSSOC'24 . I have knowledge in JavaScript, HTML,CSS ,web development and basic of ML and AI .

**Comment by Vallika09** [comment]
I'm interested in contributing to this project under GSSoC 2024 program. Kindly assign it to me.

**Comment by nikhil25803** [comment]
Hey @Vallika09 its not an issue, just a guidelines from the team GSSoC for the project admins.

**Comment by ldneal** [comment]
Hello Sir I would like to under-assig your project contributor role. Can you assign me

**Comment by Rishabh001pawar** [comment]
I'm a GSSoC'24 contributor , I want to work on this issue 
can you assign me!!
