### ISSUE TITLE
[FEATURE] Add Leetcode

### ISSUE THREAD

**Issue by chaitanyarora** [Clueless-Community/scrape-up#876]
### Describe the feature

Will add leetcode current question scraping.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/85432418/4211e863-971a-4426-9063-72bdf838037d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by Jaivignesh-afk** [comment]
I would like to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @chaitanyarora 
**Note**
+ Please create a separate module for this, as in the folder and project structure (if it is not already created).
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by Rhythm1710** [comment]
Hi! Can I work on this issue?

**Comment by Rhythm1710** [comment]
Also Just want to ask in this, it will scrape how many questions a particular person has solve?

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by MohanRamSridhar** [comment]
Hey there I would like to work on this issue please assign it to me cause I have experience with this you could check my GitHub repo.
https://github.com/MohanRamSridhar/codeForces-ratingChanges
In this I have used Codeforces API but I have also worked on a leetcode one too.

**Comment by Cheshta17** [comment]
I would like to contribute to this project. May I?
