### ISSUE TITLE
Feat: Udemy

### ISSUE THREAD

**Issue by rohra-anisha** [Clueless-Community/scrape-up#878]
### Describe the feature
As a part of participating in GSSoC'24 I would like to add following feature for udemy website:

1. Search the courses available by skills.
3. Search the courses available by instructor.

### Add ScreenShots

1. Search by skill:
![javascript](https://github.com/Clueless-Community/scrape-up/assets/150921719/51da8629-7750-4205-a667-ec54ed73e749)

2. Search by instructor
![image](https://github.com/Clueless-Community/scrape-up/assets/150921719/919d10a5-fa05-40ec-96b2-3ccd8838c673)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by SuhaniStark** [comment]
@nikhil25803 i would like to contribute to the repository please assign me this project
