### ISSUE TITLE
Feat: Add feature to spotify module

### ISSUE THREAD

**Issue by rohra-anisha** [Clueless-Community/scrape-up#879]
### Describe the feature

This issue proposes the development of a functionality for the GSSoC'24 project, implement a method to allow specifying a date and find the top 100 Billboard songs for that date.
Integrate with the Spotify API to check if songs are available on the platform.
Generate list of song links on Spotify (which are available).

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/150921719/cab27378-f87d-4a0d-8669-a4005bed3884)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @rohra-anisha 
**Note**
+ Please create a separate module for this, as in the folder and project structure (if it is not already created).
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by sujanMidatani7** [comment]
Hello @nikhil25803 assign me this I will contribute

**Comment by Kritika-2310** [comment]
Heyy @nikhil25803 I wish to contribute here.Please assign me this project.

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by Rajrishi07** [comment]
I can contribute to this project . please assign it to me.

**Comment by KartikRajOfficial** [comment]
Hey I would like to Add feature to spotify module for this repository

**Comment by priyanshch1105** [comment]
Hey I can contribute to this project.please assign it to me.

**Comment by priyanshch1105** [comment]
Hey I can contribute to this project.please assign it to me.

**Comment by Ranit-Bandyopadhyay** [comment]
Hi i am interested on this. Kindly assign it to me
