### ISSUE TITLE
Feat:  Myntra website Web scraping

### ISSUE THREAD

**Issue by ASHWIN492** [Clueless-Community/scrape-up#880]
### Describe the feature

Download entire myntra product descriptions and prices to an cvs file. This can enable you to analyze fluctuation in prices and predict the future pricing.

### Add ScreenShots

![Screenshot 2024-05-10 201917](https://github.com/Clueless-Community/scrape-up/assets/94861259/c3a8e84a-d9bb-4c73-ac63-695f8d2c91d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Nihal-Somarajupalli** [comment]
Hey @nikhil25803 i wish to contribute for this issue
please assign me this task

**Comment by AKASH722** [comment]
Hi @ASHWIN492, I would like to work on this issue. 
- Could you please provide some more details? 
- Do we need to implement the search box type, where the user will search for a product, and we will scrape all the relevant product results? 
- Or do we scrape a single product result via URL? 
- What functionalities should we include?

And one suggestion: please add an easy, medium, or hard tag to the issue. Thank you.

**Comment by pryang007** [comment]
Hello Sir, I want to work on this cause I have some prior experience working with BeautifulSoup and Selenium. Can't wait for your reply to start working.

**Comment by ASHWIN492** [comment]
@nikhil25803 plz look upon it.

**Comment by aditi-sharma-2004** [comment]
Hi, Aditi Sharma this side , I would love to work on this . GSSoC'24

**Comment by kumargautam02** [comment]
hi @ASHWIN492 , please assign this task to me, i have experience with beautifulSoup, python and requests library also i know know data processing using python and spark, i can complete this task.

**Comment by D-Huto** [comment]
Sir, i would like to work on this issue, please assign this task to me.

**Comment by Tanu-120** [comment]
Hello sir,
I have prior knowledge regarding ML. So please assign this to me.

**Comment by nikhil25803** [comment]
Go ahead @ASHWIN492 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
