### ISSUE TITLE
Feat: Add JobScraping From Naukri, FlexJobs  and others.

### ISSUE THREAD

**Issue by AKASH722** [Clueless-Community/scrape-up#881]
### Describe the feature

We can add a search field which allows user to search there desired job title and get all jobs from different job boards.

I have experience in scarping similar sites so please assign this issue to me.

Please add the GSSoC label and The difficulty as u see fit 
- as per me, if there is one site to scrape you can put it in easy or medium else hard

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/57978895/0807a7c7-7bff-4eed-8f14-da734b30d73b)
![image](https://github.com/Clueless-Community/scrape-up/assets/57978895/6c8b6980-0559-4c1f-8862-a3e127b9a56f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AKASH722** [comment]
@nikhil25803 please look upon it and thankyou.

**Comment by anglerfishlyy** [comment]
can you assign me this under GSSOC'24 ?

**Comment by thakurboy004** [comment]
Hi! I am a contributor from GSSoC24 and I would like to ask if you will assign this task to me, it would be helpful if you could add appropriate tags whether it is an easy hard, or medium problem. That would be very helpful

**Comment by AKASH722** [comment]
Hii @nikhil25803 please look at my issue and please assign it to me.

**Comment by nikhil25803** [comment]
Go ahead @AKASH722 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
