### ISSUE TITLE
Feat: Adding a scraping module for Formula1 

### ISSUE THREAD

**Issue by coldn00dles** [Clueless-Community/scrape-up#882]
### Describe the feature

The goal is to make data about Formula 1 accessible by having two routes : 
1) One can get information regarding teams by just typing the team name. Relevant data such as championships won, drivers, total podiums for the team etc. can get extracted (from the official Formula 1 Website)
2) Statistics about individual drivers can also be obtained through another route (using the website www.statsf1.com/)

### Add ScreenShots

1) For Teams
![s1](https://github.com/Clueless-Community/scrape-up/assets/93096256/cac6f976-33f4-477b-9531-c122fa172ddf)
2) For Drivers
![s2](https://github.com/Clueless-Community/scrape-up/assets/93096256/d63f2d35-9a04-4368-a2ce-7baf0801ffeb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by kumargautam02** [comment]
@coldn00dles Please assign this to me, Gssoc-24

**Comment by coldn00dles** [comment]
@nikhil25803 kindly respond in the event that I need to start work.

**Comment by nikhil25803** [comment]
Go ahead @coldn00dles 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
