### ISSUE TITLE
DOC: fixing typing errors in CONTRIBUTING.md

### ISSUE THREAD

**Issue by iamanolive** [Clueless-Community/scrape-up#883]
### What's wrong with the existing documentation

There's a typo in the existing CONTRIBUTING.md document (screenshot attached)
In the "Let's say you want to scrape the avatar URL of **and** user" line, the "and" needs to be replaced with "a"

Also, the "steps applying which we can do this" has a weird sentence structure, and I'd like to change it to "The steps to apply in order to achieve this are as follows:"

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/153769363/7eec162d-7445-4b0a-acd2-1242944839a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by kumargautam02** [comment]
@iamanolive Please assign this task to me, for GssoC'24

**Comment by RangojuNandini** [comment]
I would like to work on this under GSSoC 2024.please assign this task to me.

**Comment by SuhaniStark** [comment]
I would like to contribute to this issue please assign me this project
