### ISSUE TITLE
Feat: Add scraping module for wuzzuf site

### ISSUE THREAD

**Issue by msabry1** [Clueless-Community/scrape-up#884]
### Describe the feature

I can enhance the project by incorporating web scraping functionality for the Wuzzuf website. Wuzzuf is a popular job portal that offers a wide range of job listings across various countries. By scraping data from Wuzzuf, we can expand the job search capabilities of the application.

## Implementing Search Filters

To make the job search more efficient and user-friendly, I will implement filters that allow users to refine their search based on specific criteria. The filters will include options such as:
- Workplace (e.g., remote, on-site, hybrid)
- Country
- City
- Career Level (e.g., entry-level, mid-level, senior)
- Years of experience
- And more

By providing these filters, users can narrow down the job listings to find opportunities that align with their preferences and qualifications.

## Flexible Data Retrieval Options

Furthermore, to ensure flexibility and reusability of the scraped data, I will provide two options for data retrieval:
1. **JSON format**: The scraped job data can be returned in JSON format, which is widely supported and easy to integrate with other applications or systems.
2. **CSV file**: Alternatively, the scraped data can be saved to a CSV file. This allows users to easily export the job listings and perform further analysis or manipulation using spreadsheet software or other tools.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/86538943/56cb3546-f75a-49e4-9ca8-f1ae8153cb50)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by msabry1** [comment]
Can you assign this task to me 
@nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @msabry1 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
