### ISSUE TITLE
Feat: Add scraping logic for car aggregator websites to fetch Car Price based on Model

### ISSUE THREAD

**Issue by KJ173** [Clueless-Community/scrape-up#885]
### Describe the feature

Will fetch car price based on brand, model and price and store it in an excel from OLX website by scraping the data.

### Add ScreenShots

![Screenshot 2024-05-11 095550](https://github.com/Clueless-Community/scrape-up/assets/92749776/63bd6fe1-1c6f-4ee8-ac3c-4b494bd1dc9c)

sample excel of data scraped from OLX website. Input passed is brand name and model, make of the car.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @KJ173 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by palayushi293** [comment]
i want to work on this issue ,, pls assign this to me
Waiting for your response

**Comment by KJ173** [comment]
@nikhil25803 Please assign the level for this issue for GSSOC'24
