### ISSUE TITLE
Feat: Steam Store

### ISSUE THREAD

**Issue by iABn0rma1** [Clueless-Community/scrape-up#886]
### Describe the feature

I propose a Steam Store scraper to fetch the list of games, Top Sellers, and Special Offers.

### Add ScreenShots

1. Games Available on Steam
![Screenshot 2024-05-11 103954](https://github.com/Clueless-Community/scrape-up/assets/75512370/8e0f04e2-d474-419e-9492-939ede929928)
2. Top Selling Games
![Screenshot 2024-05-11 104046](https://github.com/Clueless-Community/scrape-up/assets/75512370/c41c8722-c515-4ed8-aadc-efec91893544)
3. Current Offers
![Screenshot 2024-05-11 105750](https://github.com/Clueless-Community/scrape-up/assets/75512370/318bff30-c787-4712-9e81-79690f5e16c5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @iABn0rma1 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
