### ISSUE TITLE
Feat: Create test file for Coursera

### ISSUE THREAD

**Issue by Celaena24** [Clueless-Community/scrape-up#887]
### Describe the feature

Test all the methods of the Coursera module and add a test file.
Add test file in directory src/test

### Add ScreenShots

No test file for Coursera

![image](https://github.com/Clueless-Community/scrape-up/assets/86319907/eaee60b5-75a7-4566-92e8-bda446db61b9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by SAISUPRIYAPAVARALA** [comment]
I am currently participating in the GSSoc 2024, and I would like to work on this issue. I already have some prior experience in writing the test file, while working on my project, which is the part of my product development internship. Could you please assign me this task?

**Comment by Celaena24** [comment]
I would like to work on this issue if it is approved

**Comment by Rishabh001pawar** [comment]
I'm a GSSoC'24 contributor, I want to work on this issue .
Assigned me

**Comment by Jashwanth05** [comment]
i am a gssoc 24 contributor , please assign me this work.

**Comment by AgnivaMaiti** [comment]
Hi! I'm a gssoc'24 contributor, please assign this issue to me, thank you!

**Comment by nikhil25803** [comment]
Go ahead @Celaena24
