### ISSUE TITLE
Feat: Add test file for Amazon

### ISSUE THREAD

**Issue by TrijoySinha** [Clueless-Community/scrape-up#888]
### Describe the feature

Adding a test file amazon_test.py for Amazon to src/test directory

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/71444393/beb13342-93e7-4484-9b9a-350aa9ecb99a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by SAISUPRIYAPAVARALA** [comment]
I am currently participating in the GSSoc 2024, and I would like to work on this issue. I already have some prior experience in writing the test file, while working on my project, which is the part of my product development internship. Could you please assign me this task @nikhil25803 ?

**Comment by AgnivaMaiti** [comment]
Hi! I'm a gssoc'24 contributor, please assign this issue to me, thank you! @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @TrijoySinha.

**Comment by TrijoySinha** [comment]
I have created amazon_test.py file but the code of amazon.py sometimes gives 503 error due to which the tests are failing.
The Tests themselves are correct.
I am pulling request, please review it.
![image](https://github.com/Clueless-Community/scrape-up/assets/71444393/9df27d6a-6e42-4758-9efc-386e8285e8b4)
