### ISSUE TITLE
Feat: Addition of Scrapping Module for Youtube GSSOC 24

### ISSUE THREAD

**Issue by yusuf-khaan** [Clueless-Community/scrape-up#889]
### Describe the feature

**This Feature will allow the user to Scrape data from Youtube Channels** GSSOC 24

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/142320884/826a52f3-8475-46f5-9718-4cec3ca20bd4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Nithincoderboy** [comment]
Hello @yusuf-khaan I want to work on this issue under GSSOC 24 so plz...assign to me

**Comment by yusuf-khaan** [comment]
@nikhil25803 , I have created a new issue and would like to make it a reality, i would be glad to contribute to it so please assign it to me.

Thank You

**Comment by nikhil25803** [comment]
@yusuf-khaan It seems like you are not scraping the data but using API which is exactly opposite to the goal of this project.

If you can scrape it without using software dependency tools like `Selenium` you can give it a try, closing this issue for now.
