### ISSUE TITLE
Reviewers requested for review in a PR

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#89]
## Proposed Method: 
`.reviewers()`

### Description
Get the list of reviewers assigned in a PR, if any.

## To what class it belongs?: 
`PullRequest()`

### Note
Add the method in `github/pull_request.py`

**Comment by neokd** [comment]
i Would like to contribute to this issue under JWOC

**Comment by nikhil25803** [comment]
Go ahead @neokd  :_)

**Comment by neokd** [comment]
Thanks
