### ISSUE TITLE
BUG: Fixed courses.py in Coursera

### ISSUE THREAD

**Issue by Celaena24** [Clueless-Community/scrape-up#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Coursera does not work currently. The class names used are inaccurate and on printing the courses the functions return an empty list.

![image](https://github.com/Clueless-Community/scrape-up/assets/86319907/d48bb172-0a7b-49e9-a7fb-286c9891e089)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Celaena24** [comment]
I have fixed the code in this file. Can you assign me this issue @nikhil25803 so that I can make a PR?

**Comment by nikhil25803** [comment]
Go ahead @Celaena24 

**Note**
- Do not use the `selenium web driver as it is incompatible with most of the devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by Celaena24** [comment]
I had a question. For the fetch_modules() function what do you want to return for each module? Just the module name?
For reference, here is a pictures of the modules from a course on coursera.

![image](https://github.com/Clueless-Community/scrape-up/assets/86319907/f434a699-f640-439b-a36c-613b25481545)

**Comment by nikhil25803** [comment]
Return a dictionary of module like Module 1 is python Basics.

**Comment by Celaena24** [comment]
> Return a dictionary of module like Module 1 is python Basics.

I have return a list of dictionaries with module name and module description. Is that fine?

**Comment by Celaena24** [comment]
Some courses have specializations instead of modules. Do you want me to return them in the same format?
Ex: Specialization 1 : Python Data Structures
Or do you want me to include the link for specializations

**Comment by Celaena24** [comment]
What I have implemented is -

For Modules:
 {
   Module 1: Python Basics, 
   Module 2: Python Advanced
}

For Specializations:
{
Specialization 1: {
                             Title: Python Basics, 
                             Link: https://.......
                            },
Specialization 2: {
                            Title: Python Advanced, 
                             Link: https://......
                            }
}

Is this format fine?

**Comment by nikhil25803** [comment]
Yes, great work @Celaena24
