### ISSUE TITLE
README: Add all websites that can be scraped

### ISSUE THREAD

**Issue by Programmer-Arvind** [Clueless-Community/scrape-up#891]
### What's wrong with the existing documentation

The existing documentation has all the websites that can be scraped using ```scrape-up```. However the readme file does not reflect all the websites that can be scraped with it. Adding the list of websites in the README will help more people find this and increase the users of ```scrape-up```. 
README is the first thing anyone sees in any repository so I would be happy to help add the list of websites in the README and even provide with a simple code snippet of every scrappable website using this.

### Add ScreenShots

No place in readme mentions all of the website it supports. It is very vague of what other websites it is capable of scraping.
![image](https://github.com/Clueless-Community/scrape-up/assets/96773379/7196b580-243e-4a20-bbb1-a1b63822094a)
![image](https://github.com/Clueless-Community/scrape-up/assets/96773379/0667c53c-a3a8-47e0-b56c-41a08b79e0d6)
![image](https://github.com/Clueless-Community/scrape-up/assets/96773379/0ce811c9-9eed-4222-bc70-866b7f87be79)
Documentation has it all but everyone sees the README file first so a quick glimpse into the list will help.
![image](https://github.com/Clueless-Community/scrape-up/assets/96773379/2231e205-ea08-4d23-944f-fa7ae0518f16)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by PlanetDestroyyer** [comment]
We can even scrape website like ambitionboֶx to scrape website and show the top companies

**Comment by nikhil25803** [comment]
You can raise a separate issue for that @PlanetDestroyyer.

**Comment by nikhil25803** [comment]
@Programmer-Arvind we already maintaining `documentation.md` and `dev-documentation.md` for this. So no need to include it in the README.md file
