### ISSUE TITLE
Feat:Scraping for Spotify 

### ISSUE THREAD

**Issue by Ranit-Bandyopadhyay** [Clueless-Community/scrape-up#892]
### Describe the feature

Describe the feature
This Feature will allow the user to Scrape data(such as followers,history) Spotify accounts under  GSSOC 24

### Add ScreenShots

![Screenshot (123)](https://github.com/Clueless-Community/scrape-up/assets/53428538/378090cf-1b9a-438b-ae8c-1e8506c38d37)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Nithincoderboy** [comment]
hello @nikhil25803 I like to work on this issue under GSSOC 24 pls assign me this

**Comment by Ranit-Bandyopadhyay** [comment]
@nikhil25803 i have created the above issue to work on it. Kindly assign it to me

**Comment by nikhil25803** [comment]
An issue has already been created for this module. @Nithincoderboy and @Ranit-Bandyopadhyay
