### ISSUE TITLE
Feat: Optimized Web scraping using OCR software .

### ISSUE THREAD

**Issue by litesh1123** [Clueless-Community/scrape-up#893]
### Describe the feature

Problem - Data scrapped from the website would be insufficient and inaccurate with only usage of  beautiful soap for scrapping.

solution- I propose the usage of selenium and OCR software called Tesseract , which would extract text from images , selenium has a feature where it can take couple of screenshots of website ,this will be given to tesseract for extraction.
would like to add this feature to amazon 
Please assign me this issue

### Add ScreenShots

![selenium screenshot](https://github.com/Clueless-Community/scrape-up/assets/139573484/1e660b12-812c-467f-8db9-206831d89062)
this screenshot contain python code with selenium b4 soap and screenshot shown in output
screenshots of websites would be taken and given to OCR software for text extraction would increase accuracy of scrapping

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
We are building this package so that people can scrape and collect data in the simplest manner possible, using selenium and OCR software is good for developers' end, but users may find some issues because they need additional config apart from just importing the package also they are not easy to set up and deploy on cloud.

**Comment by litesh1123** [comment]
ok but I suggest using Selenium because beautiful soap doesn't work dynamically , it sometime  needs html tags to be set but in selenium this problem can be solved ,if u consider this i will update it. 
 collecting data with accuracy would be important .
