### ISSUE TITLE
Feat: Add new module with cricket Live Scores and news. 

### ISSUE THREAD

**Issue by Arnav17Sharma** [Clueless-Community/scrape-up#896]
### Describe the feature

1. This module will show live scores of cricket matches currently being played. (Using ESPNCricinfo website.)
2. It will have latest cricket news. 

### Add ScreenShots

1. Live Scores
![image](https://github.com/Clueless-Community/scrape-up/assets/58596929/87fc4adb-1496-41c8-b319-87da44202708)

2. News
![image](https://github.com/Clueless-Community/scrape-up/assets/58596929/24c317d5-4504-4cb5-a971-6de7f49cf962)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Arnav17Sharma 
**Note**
+ Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
