### ISSUE TITLE
Feat: Add MyAnimeList support

### ISSUE THREAD

**Issue by shravanasati** [Clueless-Community/scrape-up#899]
### Describe the feature

Hi there! I would like to add support for [MyAnimeList](https://myanimelist.net), a popular anime and manga database. I've previously contributed to a similar [repository](https://github.com/DriftAsimov/animec), but it's no longer maintained and I need it for one of my projects.

I will add appropriate tests too.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/69118069/97d7f98c-d975-454f-8ecd-0bb5e8907cb4)
![image](https://github.com/Clueless-Community/scrape-up/assets/69118069/44e46f49-258a-4eea-97e1-cfd6b6898f55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by A-Ashh** [comment]
i would like to work on this with u.

**Comment by nikhil25803** [comment]
@A-Ashh, I suggest you look for any other issue or module you want to add. Because I'll not be able to give points to both of you corresponding to a single PR.

**Comment by nikhil25803** [comment]
Go ahead @shravanasati 
**Note**
+ Please create a separate module for this, as in the folder and project structure (if it is not already created).
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by shravanasati** [comment]
Thank you @nikhil25803, I might be able to deliver this feature by the next weekend.
