### ISSUE TITLE
Labels given to a pull request.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#90]
## Proposed Method: 
`.labels()`

### Description
Returns the list of labels given in a PR, return an empty list of no labels are given.

## To what class it belongs?: 
`PullRequest()`

### Note
Add the method in `github/pull_request.py`

**Comment by madmaverickminion** [comment]
Hi, 
Please assign this issue to me .

**Comment by nikhil25803** [comment]
Sure @madmaverickminion
