### ISSUE TITLE
DOC:

### ISSUE THREAD

**Issue by Celaena24** [Clueless-Community/scrape-up#901]
### What's wrong with the existing documentation

documentation.md does not contain Coursera

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/86319907/71584973-9578-418c-b579-6b359c09e02c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey `documentation.md` files contain the modules that are deployed package version only. The `dev-documentation. md` contains the documentation of all the modules available.
