### ISSUE TITLE
We can even scrape website like ambitionboֶx to scrape website and show the top companies

### ISSUE THREAD

**Issue by PlanetDestroyyer** [Clueless-Community/scrape-up#902]
### Describe the feature

This feature will allow us to scrape websites like AmbitionBox to find companies based on their ratings. This could be a valuable feature for developers to add functionality to their projects.

### Add ScreenShots

![IMG_20240512_082043](https://github.com/Clueless-Community/scrape-up/assets/59405252/8d3f2084-b543-46ea-9b92-a9cc0bfaa2ef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @PlanetDestroyyer 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by PlanetDestroyyer** [comment]
@nikhil25803 Thank you

**Comment by PlanetDestroyyer** [comment]
@nikhil25803 can i use scarpy framework?? casue with bs4 the website is blocking the crawler and not able to scrape the data but with scarpy i m able to scrape the data but if i m doing with scrapy i need to modify bit files i g

**Comment by PlanetDestroyyer** [comment]
I did PR review and merge it
