### ISSUE TITLE
Feat: Scrapping data from Indiantrekking

### ISSUE THREAD

**Issue by Anshika14528** [Clueless-Community/scrape-up#904]
### Describe the feature

As a part of GSSOC 24, I'd like to add a All trails module with the following functionalities:

https://www.alltrails.com/trail/india/delhi/lodhi-garden-trail

Users will be providing the name of the trail and we will be able to return them.
1. The length of a trail 
2. Elevation gain
3. Route type

Please assign under the appropriate gssoc and level label.
Thanks!

### Add ScreenShots

<img width="1194" alt="Screenshot 2024-05-12 at 11 06 30 AM" src="https://github.com/Clueless-Community/scrape-up/assets/168436423/53976171-6ef3-4f48-95e5-f527be469c6b">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Anshika14528 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by Anshika14528** [comment]
Thankyou sir

**Comment by Anshika14528** [comment]
@nikhil25803  sir, I tried scraping data from All trails but i am getting blocked, the website doesn't allow scraping and I am having a hard time doing that. I am fairly new to this, so didn't have much clue about how to proceed.

So i looked for an Indian trekking website and was able to get all the info i need, please allow me to scrape that website instead.
https://www.indiantrekking.com/chopta-chandrashila-trek.html 

<img width="914" alt="Screenshot 2024-05-14 at 10 36 23 AM" src="https://github.com/Clueless-Community/scrape-up/assets/168436423/c808ae17-53f4-48ad-a4c2-12068255f2a7">
