### ISSUE TITLE
DOC: Updating All Platforms Names in Documentation File

### ISSUE THREAD

**Issue by AK-AN** [Clueless-Community/scrape-up#905]
### What's wrong with the existing documentation

Current Documentation does not show all the platforms covered till now in "The platforms we cover" section. 

### Add ScreenShots

![Screenshot (9)](https://github.com/Clueless-Community/scrape-up/assets/125082638/9ca9904a-cb12-487f-8981-74c5f02bf29d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by m-alam13** [comment]
Hi, I want to work on this issue. Please assign me.

**Comment by nikhil25803** [comment]
Hey @AK-AN, `documentation.md` files contain the modules that are available in the deployed version of the package only.
