### ISSUE TITLE
BUG: Fix YahooFinance.py 

### ISSUE THREAD

**Issue by TrijoySinha** [Clueless-Community/scrape-up#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

YahooFinance.py not working.
Returning None
![image](https://github.com/Clueless-Community/scrape-up/assets/71444393/a497abfb-5ea7-46a2-909f-359b6d47a728)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Fix it and raise a PR for the changes.
