### ISSUE TITLE
Feat:Module to Scrape Chrome Web Store

### ISSUE THREAD

**Issue by AakilAhamed** [Clueless-Community/scrape-up#907]
### Describe the feature

[Chrome web store ](https://chromewebstore.google.com) can be scraped to obtain publicly available info about a extension or a theme like....
- Star Rating
- No of Downloads
- Latest Version
- File size
- Languages Supported 
- Compatibility and so on

We can also scrape details about extensions and themes available under certain keywords with filters

Under GSsoC'24, i would like to contribute to this repo under this issue @nikhil25803 

### Add ScreenShots

![66407c52f90de05b6c17196d](https://github.com/Clueless-Community/scrape-up/assets/70323033/4eead4db-f703-41d2-b408-2f96b00c3ebe)
![66407c7c1875b67c75419e2d](https://github.com/Clueless-Community/scrape-up/assets/70323033/087d539e-baa4-40cb-9543-bb445c72f929)
![66407cf4f691805d1354ad3f](https://github.com/Clueless-Community/scrape-up/assets/70323033/6bce8d48-2969-460d-baa9-e7c8e3ab8c59)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [x] I want to work on this issue

**Comment by Alokita004** [comment]
Hello please assign this issue to me

**Comment by nikhil25803** [comment]
Go ahead @AakilAhamed 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
