### ISSUE TITLE
DOC: Code of Conduct.md

### ISSUE THREAD

**Issue by TheNaiveSamosa** [Clueless-Community/scrape-up#908]
### What's wrong with the existing documentation

The existing documentation was thorough, but we made some refinements to improve readability and clarity. We adjusted the wording to align more closely with our community's tone and style, ensuring that it is easily understood by all. Additionally, we added a few sentences to emphasize our commitment to creating a positive environment and to provide clarity on the enforcement process. These changes were made to enhance the overall effectiveness and inclusivity of our code of conduct.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/112872086/61d80135-4023-4da4-88a4-c706983d5f65)
![image](https://github.com/Clueless-Community/scrape-up/assets/112872086/c929468b-4a8c-4443-8b46-7d639c5398b9)
And a few other changes.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Raise a PR for these changes @TheNaiveSamosa
