### ISSUE TITLE
BUG: Inadequate and Inconsistent Documentation in Product Scraping Class @ src/scrape_up/amazon/products.py

### ISSUE THREAD

**Issue by TheNaiveSamosa** [Clueless-Community/scrape-up#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The existing documentation is lacking in several areas:

1. **Clarity**: The existing docstrings are not very clear and concise. They should provide clear examples and explanations of how to use the class and its methods.

2. **Consistency**: The formatting of the existing docstrings is inconsistent. For example, some docstrings use triple quotes for code blocks, while others use single quotes.

3. **Completeness**: Some methods lack docstrings entirely, such as the `fetch_product_page` method.

4. **Error Handling**: The documentation does not mention anything about error handling or what exceptions might be raised by the methods.

5. **Examples**: The examples provided in the docstrings are minimal and could be expanded to cover more use cases.

Overall, the existing documentation could be improved by providing more detailed and consistent explanations, including error handling information, and expanding the examples to cover a wider range of scenarios.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @TheNaiveSamosa
