### ISSUE TITLE
Feat: Create a GUI or a website so that other non coders can also use it

### ISSUE THREAD

**Issue by ashwin-j-r** [Clueless-Community/scrape-up#912]
### Describe the feature

We can create a website and give a input field or choices and return it to csv or txt file and the users could download so that , users will not need to download the whole code , they can do it in the website itself.

### Add ScreenShots

I can share some of the screenshots of other websites 
![Screenshot 2024-05-12 161207](https://github.com/Clueless-Community/scrape-up/assets/75122684/b2b56569-c810-4d00-ab78-3f43b0ad3f89)

Just like this , instead of link , we can create the input field for the details in which we can use .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by PranavTyagi-3** [comment]
I would love to contribute to this issue and can surely complete it

**Comment by nikhil25803** [comment]
Hey @ashwin-j-r, we are not looking for a website to this package now.
