### ISSUE TITLE
Feat: scrape-up for Unstop.com 

### ISSUE THREAD

**Issue by Disha-Baghel** [Clueless-Community/scrape-up#913]
### Describe the feature

Scrape the details of upcoming contests / jobs from unstop.com

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/107053261/e67bc7ee-ab71-4c16-82c0-a88aab7e6c39)
![image](https://github.com/Clueless-Community/scrape-up/assets/107053261/7e027718-bf69-42bc-b3f6-692fa647aeb1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Nithincoderboy** [comment]
@nikhil25803 Assign this issue to me I would able to work on it

**Comment by nikhil25803** [comment]
Go ahead @Disha-Baghel 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by Cheshta17** [comment]
@nikhil25803 Could you assign this issue to me. I want to work on this project.

**Comment by Disha-Baghel** [comment]
> @nikhil25803 Could you assign this issue to me. I want to work on this project.

Hello,

I wanted to kindly inform you that I am already actively working on the issue at hand. Thank you for your understanding

**Comment by Arnav717** [comment]
is this done?
