### ISSUE TITLE
BUG: inside academia research topics scraper function

### ISSUE THREAD

**Issue by GbCderr14** [Clueless-Community/scrape-up#916]
### Is there an existing issue for this?

- [x] I have searched the existing issues there is no existing issue for this

### What happened?

In academia.py file current scrapping function of get_research_topics() is returning None. Debugged the code already and want to fix it as a contributor. Also this issue can be seen by running its test file.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @GbCderr14
