### ISSUE TITLE
Feat:Adding test files

### ISSUE THREAD

**Issue by GbCderr14** [Clueless-Community/scrape-up#917]
### Describe the feature

Wish to add test files for other scrapping functions as well currently there exists only 18-20 test files while there are so many scrapping modules available whose test files do not exist so want to add them as a contributor.

### Add ScreenShots

Just like these--
![image](https://github.com/Clueless-Community/scrape-up/assets/114488917/d4c2a32a-6bfd-43b0-b539-9a4d61611649)
want to add test files for other scrapping modules as well.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
I can not assign someone to add all the test cases, you can pick one module and add test file of it.
