### ISSUE TITLE
Feat: Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [Clueless-Community/scrape-up#919]
### Describe the feature

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/50082154/1931e0d2-ce72-44f1-a63e-22d4c0c730f5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @sanmarg.

**Comment by sanmarg** [comment]
Please add the level for this issue considering its complexity.

**Comment by sanmarg** [comment]
Task Completed

**Comment by sanmarg** [comment]
Could you please assign labels to it ?
