### ISSUE TITLE
Feat: Adding Blogger Scraper 

### ISSUE THREAD

**Issue by MavSneha** [Clueless-Community/scrape-up#921]
### Describe the feature

The scraper will allow users to retrieve articles from Google Blogger based on a specified topic. The feature will include a Blogger class with a method that scrapes article titles and links from the Google Blogger search results page for the given topic.

### Add ScreenShots

![Screenshot 2024-05-13 032914](https://github.com/Clueless-Community/scrape-up/assets/130782754/07c93038-af2b-4832-85e5-c3fc47835497)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @MavSneha, I just checked that the Blogger module is not working, so it doesn't make any sense to write test case for a module that is not working.

Fix it if you can (raise a separate issue for that) then we can continue with this issue.
Closing it for now!

**Comment by MavSneha** [comment]
@nikhil25803 Sir should I contact project mentors to get this resolved?

Sugam Arora 
Yashwanth R
