### ISSUE TITLE
Feat: Add test files for Instagram module

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [Clueless-Community/scrape-up#925]
### Describe the feature

- Test all the methods of the instagram module and add a test file.
- Will add test file in directory src/test.
- Will Check the users.py file as a reference to get an idea about structuring the code.
- Will use unittest only.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/103999924/61e054f7-e0b0-4993-bb99-87ed6145c815)

Similar to above files

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
We are not continuing with Instagram module, hence you can skip this.
