### ISSUE TITLE
Feat: Add tests for the reddit scraper

### ISSUE THREAD

**Issue by Celaena24** [Clueless-Community/scrape-up#926]
### Describe the feature

There is currently no test file for reddit.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/86319907/92d1a666-36a6-4d9f-a2dd-cafb4a280d3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Celaena24
