### ISSUE TITLE
Feat: I would Like to add feature of codechef contest related 

### ISSUE THREAD

**Issue by agastya3636** [Clueless-Community/scrape-up#927]
### Describe the feature

I would Like to add features of CodeChef contest related like the upcoming , live and past contests.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/124435030/17fc5868-8923-41f7-a3d9-773bc6dc6856)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Prnasin** [comment]
please assign this issue to me 
i would want to work on It
