### ISSUE TITLE
Feat: Scraping data from geeksforgeeks

### ISSUE THREAD

**Issue by agastya3636** [Clueless-Community/scrape-up#928]
### Describe the feature

I want to add scraping for geeks for geeks it will fetch the data of the username provided.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/124435030/75db3543-4cfc-408a-a686-6f0b6436a0f9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by agastya3636** [comment]
@nikhil25803 could you please assign the issue to me

**Comment by nikhil25803** [comment]
Go ahead @agastya3636 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
