### ISSUE TITLE
Feat: Scraping data from Linkedin

### ISSUE THREAD

**Issue by prasannakumarvg** [Clueless-Community/scrape-up#929]
### Describe the feature

[Linkedin ](https://www.linkedin.com/)can be scraped to obtain publicly available info about a user like....

Name
Email
Education
Experience
Skills
External links like Portfolio, etc..

We can also scrape details about user under certain keywords.

Under GSsoC'24, i would like to contribute to this repo under this issue @nikhil25803

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/123349921/00288aed-2bbc-4c91-bc6b-0c72e7b428cf)
![image](https://github.com/Clueless-Community/scrape-up/assets/123349921/be933c87-e3db-4a20-bc68-1e4772c073c3)

### Record

- [x] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @prasannakumarvg 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by AshishKumarKhandual** [comment]
please assign me this project i want to contribute .

**Comment by akashlogics** [comment]
i am interested in this issue can you assign to contribute

**Comment by kart2004** [comment]
Hi @nikhil25803, can you please assign this to me ?

**Comment by sophiaodigie1** [comment]
Hello @nikhil25803 I am interested into contributing in this project

**Comment by Vidulaa05** [comment]
Hi @nikhil25803, I am interested in working on this project! I will try my best to complete the required work for this project within the stipulated time. Would you please assign this work to me?

**Comment by itssiddhantjain** [comment]
##Hello @nikhil25803 , please assign this issue to me as I have already worked on this kind of problem in the past.

**Comment by C-Nubela** [comment]
Rather than putting the effort into building your own scraping and dealing with bypassing LinkedIn's complex authwall mechanisms (IPs, cookies, browser fingerprinting, etc.), [you could use something like Proxycurl](https://nubela.co/proxycurl/?utm_campaign=content_amplification&utm_source=reddit&utm_medium=social&utm_content=comments), which is a B2B enrichment service that scrapes the data for you. Give it a look and see if that's up your alley.

P.S. Yes, I do work there!
