### ISSUE TITLE
Feat: Scrape data from SystemRequirementsLab

### ISSUE THREAD

**Issue by KunalG-Zol** [Clueless-Community/scrape-up#934]
### System Requirements Lab contains all the requirements for most of the available video games.

In this proposed module: 
1. The user will search some keywords for a game.
2. Select one from the best matching names.
3. The requirements will be extracted.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/94951050/1fdfbbe5-a2c7-4621-8b16-9806f7f93b84)
![image](https://github.com/Clueless-Community/scrape-up/assets/94951050/a1bcece7-f644-45fd-948b-1c9e5dd30f6f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by KunalG-Zol** [comment]
@nikhil25803 please assign this issue to me.

**Comment by KunalG-Zol** [comment]
@nikhil25803 Kindly tell me if I can work on this feature or if there is any problem with it.

**Comment by nikhil25803** [comment]
Go ahead @KunalG-Zol 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
