### ISSUE TITLE
Feat: I would like to add codeforces contest schedule and data

### ISSUE THREAD

**Issue by kart2004** [Clueless-Community/scrape-up#935]
### Describe the feature

Right now, the existing codeforces folder only has user.py which gives user data. However most people would prefer to know contest data: upcoming, live or past. While a few have raised issues regarding codechef or gfg, no one has raised this about codeforces. I have worked on a similar feature and I can implement it under gssoc'24.
Thanks 

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/111494403/820d3310-3c21-4901-8778-dada494037f7)
![image](https://github.com/Clueless-Community/scrape-up/assets/111494403/c378de4d-4a7c-48c4-8dff-5c650e70e79b)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by kart2004** [comment]
@nikhil25803 could you please assign the issue to me

**Comment by nikhil25803** [comment]
Go ahead @kart2004 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
