### ISSUE TITLE
Feat: Scrapping Pubmed Data using BioPython and Beautiful Soup

### ISSUE THREAD

**Issue by VarsaGupta** [Clueless-Community/scrape-up#937]
### Describe the feature

Problem:
PubMed offers crucial insights in life sciences, but extracting data conventionally can be slow, particularly with extensive research papers using the library like Beautiful Soup and Selenium.
Solution:
BioPython emerges as a game-changer in this scenario, offering a faster and more efficient solution. With specialized functionalities tailored for biological data analysis, BioPython streamlines the process of scraping PubMed data, enabling researchers to access valuable insights in few seconds.

My approach:
I will provide the python script for both Beautiful Soup and BioPython for scrapping extensive research papers of Pubmed, showcasing the efficiency of BioPython.

### Add ScreenShots

![Uploading Screenshot 2024-05-03 205138.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by kashishrajputt** [comment]
i would like to work on this issue. please assign it to me.

**Comment by nikhil25803** [comment]
Hey @VarsaGupta, the reason why you use `Beautiful Soup` is that it is lightweight. Packages like `BioPython` are much heavier. If you want to give it a try without using `BioPython` you can continue with the issue else can close this.

**Comment by VarsaGupta** [comment]
@nikhil25803 , okk i will give a try using Beautiful Soup.
