### ISSUE TITLE
Feat:Add test file for wikipedia.py module

### ISSUE THREAD

**Issue by GbCderr14** [Clueless-Community/scrape-up#939]
### Describe the feature

Want to add  test file for wikipedia module just like other modules.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/114488917/034c081e-f063-4bf1-aa06-6b697a93907e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @GbCderr14 
- Add test file in directory `src/test`.
- Use `unittest` only.

**Comment by yashpawar6849** [comment]
I want to work on this issue please assign me the task.
