### ISSUE TITLE
Feat: Scraping data from LeetCode

### ISSUE THREAD

**Issue by Shraman-jain** [Clueless-Community/scrape-up#944]
### Describe the feature

I want to add scrapper  for LeetCode it will fetch the data of the username provided. Like the no of problems solved and various ranks and badges the user got. Please Assign this to me   

### Add ScreenShots

![leetcode](https://github.com/Clueless-Community/scrape-up/assets/60072287/d0f271b5-52c8-4a45-a75d-1a18d006625b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Cheshta17** [comment]
I would like to work on this project. Please assign it to me

**Comment by nikhil25803** [comment]
Go ahead @Shraman-jain 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by itssiddhantjain** [comment]
Hello @nikhil25803  please assign this issue to me as I have already worked on this kind of problem in the past.

**Comment by Shraman-jain** [comment]
@nikhil25803 Can you guide me how to scrape dynamic content without using selenium as I can't find a way to do so. I have tried multiple approaches but can't find a suitable one
