### ISSUE TITLE
Feat: Add data extraction from CodeForces

### ISSUE THREAD

**Issue by Arghya-Banerjee** [Clueless-Community/scrape-up#946]
### Describe the feature

This feature will extract data from the codeforces profile of an user when the username is provided. It will extrac info like last contest the user participated, when he registered and many more information about that profile.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/72212592/51dd0959-d199-4455-9ea1-2e0a3a1c3db0)

Like we can see from this image the profile part alone contains many information. I will implement single functions as well as one compact function that will show all the information about the user in a structured manner.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by kashishrajputt** [comment]
i would like to work on this issue. please assign it to me.

**Comment by imsuraj675** [comment]
I would like to work on this issue, please assign it to me.
