### ISSUE TITLE
DOC:dev-documentation.md

### ISSUE THREAD

**Issue by chinmaiyee** [Clueless-Community/scrape-up#950]
### What's wrong with the existing documentation

Fix certain grammatical errors. eg: return is there instead of returns and capitalise a few lines in order to maintain proper format.
Kindly assign me with this task so that I can provide an error-free documentation!

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/34850110/4e2db963-95ec-40cb-a40f-8a94e8253d7c)
![image](https://github.com/Clueless-Community/scrape-up/assets/34850110/ab2a1129-0ce6-43f7-abb0-b3117107154e)
![image](https://github.com/Clueless-Community/scrape-up/assets/34850110/b444a88c-9ef6-41ab-9868-c0c68416bd74)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @chinmaiyee

**Comment by chinmaiyee** [comment]
Thanks will report to u!

**Comment by Divya-1612-reddy** [comment]
I would like to improve this. please assign me this issue.
