### ISSUE TITLE
Feat: Add more features to the pinterest module

### ISSUE THREAD

**Issue by priyankeshh** [Clueless-Community/scrape-up#951]
### Describe the feature

I am adding 2 features to the pinterest module:

**Feature 1: Search Pins by Keyword**
Description:
Add functionality to search for pins containing a specific keyword on Pinterest. Users will be able to provide a keyword, and the script will scrape pins related to that keyword, including details such as pin title, description, link, and image URL.

**Feature 2: Get Pin Details**

Description:
Implement a feature to fetch details about a specific pin on Pinterest. Users can provide the URL of a pin, and the script will extract information such as pin title, description, number of saves, and number of comments.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/102135464/a882747e-9146-4df3-89d8-fb3e908c8512)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by priyankeshh** [comment]
@nikhil25803 please assign this to me

**Comment by nikhil25803** [comment]
Go ahead @priyankeshh 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by priyankeshh** [comment]
Due to some errors, I have closed this PR, I am making a new PR for this issue. Please check that out #999
