### ISSUE TITLE
Feat: Add test file for pinterest.py

### ISSUE THREAD

**Issue by priyankeshh** [Clueless-Community/scrape-up#952]
### Describe the feature

I want to add a pinterest_test.py which uses all the methods of the pinterest module 

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/102135464/edd210f7-be21-46bf-ba22-8df67b5c3b11)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by priyankeshh** [comment]
@nikhil25803 can you assign this to me please

**Comment by Rajneeshkarya** [comment]
@nikhil25803  could you assign to me this issue?
