### ISSUE TITLE
Feat: Add lichess module 

### ISSUE THREAD

**Issue by msabry1** [Clueless-Community/scrape-up#954]
### Output  :  the matches he played:
- white player name , rank , score .
- black player name , rank , score .
- PGN of the match

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/86538943/e82167e5-01e5-42ad-bdd0-e2c5b012c508)
![image](https://github.com/Clueless-Community/scrape-up/assets/86538943/ae3b37b3-02bf-432d-9415-d8d5be8ff7ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @msabry1 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
