### ISSUE TITLE
Feat: Scrapper for Indeed

### ISSUE THREAD

**Issue by Subhoshri** [Clueless-Community/scrape-up#956]
### Describe the feature

I want to add a scrapper for Indeed that will allow one to fetch company details that include functions for CEO Name, Company size and revenue, Industry associated with, and locations where the job is available.
This is a beneficial idea as it would allow one to choose among many companies by comparing the right pieces of information.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/138369802/28c3c34a-0249-4ce8-9f0e-b51cd38a2619)

To collect only the required data from this site.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Subhoshri** [comment]
Please assign me this issue. I am not working currently on any other issues, so I am free to take upon this.

**Comment by nikhil25803** [comment]
Go ahead @Subhoshri 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
