### ISSUE TITLE
BUG: Fix bug in IMDB module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

All modules of the `IMDB` class is not working properly, debug and fix them.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by SkSadaf** [comment]
@nikhil25803 Can I work on this, under GSSoC'24?

**Comment by Cralsic123** [comment]
@nikhil25803 please assign me this issue. I would be able to solve this.

**Comment by kart2004** [comment]
Hi @nikhil25803, can you assign this to me under GGSoC'24?

**Comment by ChethanaPotukanam** [comment]
Please assign this to me under gssoc24 @nikhil25803 . I want to work on this issue.And also add labels like level 1 , 2 or 3.

**Comment by nikhil25803** [comment]
Go ahead @SkSadaf

**Comment by SkSadaf** [comment]
Thank you for assigning the issue, I am working on it.

**Comment by RohanJobanputra** [comment]
@nikhil25803 Hey, can you assign me this task? I am eager to work on it.

**Comment by thecloudcode** [comment]
Can I work on this issue, I have worked on such issues earlier.

**Comment by Aastha204** [comment]
Hi I want to work on this issue, kindly assign me this under gssoc'24
