### ISSUE TITLE
Add test files for GFG module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#960]
### Describe the feature

A new module GFG has been added, I want someone to write test files for it.

### Add ScreenShots

--

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by SkSadaf** [comment]
I'm interested in contributing to this issue. Could you please assign it to me? I believe I can make a valuable contribution.

**Comment by Cralsic123** [comment]
Please add me as a contributor for this issue @nikhil25803

**Comment by kart2004** [comment]
Hi @nikhil25803 , can you assign this to me under GGSoC'24?

**Comment by Cralsic123** [comment]
> Please add me as a contributor for this issue @nikhil25803

@nikhil25803 would love to contribute here, please assign me.

**Comment by AshmitaBarthwal** [comment]
@nikhil25803 I would like to work on this issue. Please assign it to me.

**Comment by iamanolive** [comment]
hi @nikhil25803 i'd love to work on this!

**Comment by sammyyyyy12** [comment]
Hello @nikhil25803! I would like to contribute to this issue. I am good at Python and Python libraries, and contributing to this issue under GSSoC'24 would be a great delight.

**Comment by AgnivaMaiti** [comment]
Hii, can you please assign this to me?

**Comment by kart2004** [comment]
Hi @nikhil25803, can you please assign this to me. I would love to work on this.
Thanks in advance!!
