### ISSUE TITLE
Add test files for Wuzzuf module.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/scrape-up#961]
### Describe the feature

A new module `wuzzuf` as been added to the package, I want someone to write test files for it so that we can check the integrity of them overtime.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/b1ff7bf1-b3fd-4256-aefe-eb77302fa554)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by Cralsic123** [comment]
I would love to contribute to this issue. Please assign me this issue @nikhil25803.

**Comment by kart2004** [comment]
Hi @nikhil25803 , can you assign this to me under GGSoC'24?

**Comment by Santhosh-Siddhardha** [comment]
Hey @nikhil25803 , Could you please assign this issue to me.

**Comment by Rajneeshkarya** [comment]
hey @nikhil25803 I would like to work on this issue. Could you assign this issue to me under GSSOC'24?

**Comment by Cralsic123** [comment]
> I would love to contribute to this issue. Please assign me this issue @nikhil25803.

Hi @nikhil25803 any updates?

**Comment by iamanolive** [comment]
hi @nikhil25803 i would love to work on this issue

**Comment by Vrisha213** [comment]
I would like to work on this issue.
Please assign it to me @nikhil25803 .

**Comment by TohitCU** [comment]
I can help you with that ! @nikhil25803

**Comment by anupa-rb** [comment]
Hello there, I would like to work on this issue as a contributor at GSSOC'24. Please assign this to me.

**Comment by sreesti07** [comment]
Hello @nikhil25803, I would like to work on this issue as a contributor at GSSOC'24. Could you please assign this to me?

**Comment by anshikaag3379** [comment]
Hey @nikhil25803 I could possible solve this issue!
