### ISSUE TITLE
Feat: Add module for leetcode

### ISSUE THREAD

**Issue by agastya3636** [Clueless-Community/scrape-up#966]
### Describe the feature

Add module for leetcode

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/124435030/f9a423a8-62a4-4898-93a7-f6b90aa337bf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by agastya3636** [comment]
@nikhil25803 could you please assign the issue to me

**Comment by nikhil25803** [comment]
One more issue is opened regarding this, please make sure you both do not work on the same functionality. 
You can coordinate with him/her.

**Comment by agastya3636** [comment]
@nikhil25803 will there be any issue if I  complete it as he is not part of gssoc24 as you can see
![image](https://github.com/Clueless-Community/scrape-up/assets/124435030/3970555f-9d6f-4832-ab06-444a0c1af4c2)
