### ISSUE TITLE
Feat:Scrape from walmart

### ISSUE THREAD

**Issue by merciajeno** [Clueless-Community/scrape-up#969]
### Describe the feature

I am interested in developing this feature as it will help us find best products of lower price

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/113104600/1f11f7cd-6fc9-4556-b346-7fcc960d96eb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by satwika10** [comment]
I would like to scrape data from walmart. I am already doing this kind of project and interested to scrape data from more websites. Please assign this project to me under Gssoc'2024

**Comment by nikhil25803** [comment]
Go ahead @merciajeno 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻

**Comment by merciajeno** [comment]
@nikhil25803 , Can you assign this to @satwika10 as I am not free for now.

**Comment by nikhil25803** [comment]
Sure.

**Comment by DivyaVijay1234** [comment]
Greetings, 
I would like to work on this issue. I have experience with similar projects.  Please assign this issue to me. I look forward to working with you and contributing towards your organization.

**Comment by pranjalipilankar** [comment]
hello @nikhil25803 ,
I would like to work on this issue as a part of GSSOC'24. I agree to follow this project's Code of Conduct.
Please assign this issue to me.

**Comment by a-di-ti** [comment]
Hi, this is a great issue that I'd love to tackle and I'm a GSSOC'24 contributor. Looking forward to being assigned!
