### ISSUE TITLE
Feat: I would like to add  module for atcoder to fetch user data

### ISSUE THREAD

**Issue by agastya3636** [Clueless-Community/scrape-up#971]
### Describe the feature

I would like to add  module for atcoder to fetch user data

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/124435030/14dc0b01-be23-4083-9098-16c850b6a42d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by agastya3636** [comment]
@nikhil25803 could you please assign the issue to me

**Comment by nikhil25803** [comment]
Go ahead @agastya3636 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
