### ISSUE TITLE
Feat: I would like to scrape contest page of atcoder

### ISSUE THREAD

**Issue by agastya3636** [Clueless-Community/scrape-up#974]
### Describe the feature

I would like to scrape contest page of atcoder

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/124435030/11645edf-283d-47f2-b06b-6e0b59ea47ee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by satwika10** [comment]
Hello @nikhil25803. I would like to scrape contest page of atcoder. I am already scraping few websites and want to learn more about it. Kindly please assign this issue to me under Gssoc'2024.

**Comment by agastya3636** [comment]
@nikhil25803 could you please assign the issue to me

**Comment by nikhil25803** [comment]
Go ahead @agastya3636 

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
