### ISSUE TITLE
DOC:update

### ISSUE THREAD

**Issue by RiyaaBhatt** [Clueless-Community/scrape-up#981]
### What's wrong with the existing documentation

Hello PA
adding contributors in readme under gssoc'24 please assign this to me

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/128878008/d1f88017-65cf-4a3d-be45-00f8028aca99)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
This section was there in the README.md earlier, I removed it on purpose.
