### ISSUE TITLE
Feat: Add new module for FIDE (International Chess Federation) website.

### ISSUE THREAD

**Issue by Arnav17Sharma** [Clueless-Community/scrape-up#985]
### Describe the feature

![image](https://github.com/Clueless-Community/scrape-up/assets/58596929/3813ae95-32ab-435e-ab6d-f4b7dd623635)

1. This module will be made by scraping the official website of [FIDE (International Chess Federation)](https://www.fide.com/)
2. It will have stats for current top 100 players.
3. Details about the latest chess and fide news.
4. Dates and names of all the tier-1 events of 2024.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/58596929/213285eb-65ac-48e5-81df-c843ae531597)
![image](https://github.com/Clueless-Community/scrape-up/assets/58596929/871e39d7-d87e-49b5-89dd-ce959d3b3144)
![image](https://github.com/Clueless-Community/scrape-up/assets/58596929/c7a6f965-c053-475b-8ae6-203933f650cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Go ahead @Arnav17Sharma

**Note**
- Please create a separate module for this, as in the folder and project structure (if it is already created, just add your features as functions in the same module).
- Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
- Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
