### ISSUE TITLE
BUG:geeksforgeeks module does not return json format

### ISSUE THREAD

**Issue by agastya3636** [Clueless-Community/scrape-up#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

geeksforgeeks module does not return JSON format as it was updated by one of our fellow mates.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by agastya3636** [comment]
@nikhil25803  please assign it to me

**Comment by nikhil25803** [comment]
Go ahead @agastya3636

**Comment by agastya3636** [comment]
@nikhil25803 i have resolved this issue in pull request #1004  but I forgot to mention it

**Comment by agastya3636** [comment]
could you help me
